/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kuka_kr_120_sat_M_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};

/* M:(i0[6])->(o0[6x6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a7, a8, a9;
  a0=1.3983700000000001e+01;
  a1=arg[0]? arg[0][1] : 0;
  a2=sin(a1);
  a3=5.6097200000000029e+00;
  a4=1.6684699999999992e+00;
  a5=3.3203700000000003e-01;
  a6=2.2791000000000000e-01;
  a7=4.5065329524113181e+01;
  a8=2.2532661132056589e+01;
  a9=arg[0]? arg[0][5] : 0;
  a10=sin(a9);
  a11=(a8*a10);
  a12=3.8076495003996386e-08;
  a9=cos(a9);
  a13=(a12*a9);
  a11=(a11+a13);
  a13=(a11*a10);
  a14=(a12*a10);
  a15=2.2532668392056593e+01;
  a16=(a15*a9);
  a14=(a14+a16);
  a16=(a14*a9);
  a13=(a13+a16);
  a7=(a7-a13);
  a8=(a8*a9);
  a16=-9.0000310721263031e-18;
  a17=(a12*a10);
  a16=(a16-a17);
  a8=(a8+a16);
  a16=(a8*a9);
  a12=(a12*a9);
  a17=1.4561428152148776e-18;
  a15=(a15*a10);
  a17=(a17-a15);
  a12=(a12+a17);
  a17=(a12*a10);
  a16=(a16-a17);
  a7=(a7-a16);
  a17=7.5005128020000001e+01;
  a7=(a7+a17);
  a6=(a6+a7);
  a7=3.4790612923820404e+01;
  a15=-8.7109785173560301e-13;
  a18=(a15*a10);
  a19=-4.4455825482730761e-24;
  a20=(a19*a9);
  a18=(a18+a20);
  a20=casadi_sq(a18);
  a21=-5.8999999999999997e-02;
  a22=(a15*a9);
  a23=-5.1522422238038889e-13;
  a24=(a19*a10);
  a23=(a23-a24);
  a22=(a22+a23);
  a22=(a21+a22);
  a23=casadi_sq(a22);
  a20=(a20+a23);
  a20=(a7*a20);
  a6=(a6+a20);
  a20=2.0158699999999999e-01;
  a16=(a16+a17);
  a20=(a20+a16);
  a16=1.9500000000000001e-01;
  a23=4.8966386501092529e-12;
  a24=(a23*a9);
  a15=(a15*a24);
  a25=1.0521998031627131e-01;
  a26=(a23*a10);
  a19=(a19*a26);
  a25=(a25-a19);
  a15=(a15+a25);
  a15=(a16+a15);
  a25=casadi_sq(a15);
  a19=casadi_sq(a18);
  a25=(a25+a19);
  a25=(a7*a25);
  a20=(a20+a25);
  a6=(a6-a20);
  a25=3.2025999999999999e-01;
  a13=(a13+a17);
  a25=(a25+a13);
  a13=casadi_sq(a15);
  a19=casadi_sq(a22);
  a13=(a13+a19);
  a13=(a7*a13);
  a25=(a25+a13);
  a25=(a25-a20);
  a13=(a6+a25);
  a19=arg[0]? arg[0][4] : 0;
  a27=sin(a19);
  a28=(a27*a6);
  a19=cos(a19);
  a29=-7.7882700000000006e-05;
  a11=(a11*a24);
  a14=(a14*a26);
  a11=(a11-a14);
  a14=1.4868799999999882e-07;
  a30=(a14*a9);
  a31=-9.1900094281262672e-07;
  a32=(a31*a10);
  a30=(a30+a32);
  a11=(a11-a30);
  a29=(a29+a11);
  a11=(a7*a15);
  a11=(a11*a18);
  a29=(a29-a11);
  a11=(a19*a29);
  a28=(a28+a11);
  a11=(a28*a27);
  a30=(a27*a29);
  a32=(a19*a25);
  a30=(a30+a32);
  a32=(a30*a19);
  a11=(a11+a32);
  a13=(a13-a11);
  a25=(a27*a25);
  a32=-1.2790999999999999e-04;
  a33=(a8*a10);
  a34=(a12*a9);
  a33=(a33+a34);
  a34=(a14*a24);
  a35=(a31*a26);
  a34=(a34+a35);
  a33=(a33-a34);
  a32=(a32+a33);
  a33=(a7*a18);
  a33=(a33*a22);
  a32=(a32-a33);
  a33=(a32+a32);
  a33=(a23*a33);
  a25=(a25+a33);
  a33=(a19*a29);
  a25=(a25-a33);
  a33=(a25*a27);
  a29=(a27*a29);
  a34=2.;
  a35=5.6005899999999997e-02;
  a8=(a8*a24);
  a12=(a12*a26);
  a8=(a8-a12);
  a31=(a31*a9);
  a14=(a14*a10);
  a31=(a31-a14);
  a8=(a8-a31);
  a35=(a35+a8);
  a7=(a7*a15);
  a7=(a7*a22);
  a35=(a35-a7);
  a7=(a34*a35);
  a7=(a23*a7);
  a29=(a29+a7);
  a6=(a19*a6);
  a29=(a29-a6);
  a6=(a29*a19);
  a33=(a33-a6);
  a13=(a13-a33);
  a13=(a13+a20);
  a5=(a5+a13);
  a13=1.8221774061420795e+01;
  a6=9.3085251970088045e-01;
  a15=(a6*a15);
  a7=(a27*a15);
  a18=(a6*a18);
  a8=(a19*a18);
  a7=(a7+a8);
  a8=casadi_sq(a7);
  a31=-3.4150000000000003e-01;
  a14=(a27*a18);
  a6=(a6*a22);
  a22=(a23*a6);
  a14=(a14+a22);
  a22=(a19*a15);
  a14=(a14-a22);
  a14=(a31+a14);
  a22=casadi_sq(a14);
  a8=(a8+a22);
  a8=(a13*a8);
  a5=(a5+a8);
  a8=4.6258300000000002e-02;
  a33=(a33+a20);
  a8=(a8+a33);
  a33=5.8999999999999997e-02;
  a22=(a23*a19);
  a12=(a22*a15);
  a36=(a23*a27);
  a37=(a36*a18);
  a37=(a6-a37);
  a12=(a12+a37);
  a12=(a33+a12);
  a37=casadi_sq(a12);
  a38=casadi_sq(a7);
  a37=(a37+a38);
  a37=(a13*a37);
  a8=(a8+a37);
  a5=(a5-a8);
  a37=3.3070999999999995e-01;
  a11=(a11+a20);
  a37=(a37+a11);
  a11=casadi_sq(a12);
  a38=casadi_sq(a14);
  a11=(a11+a38);
  a11=(a13*a11);
  a37=(a37+a11);
  a37=(a37-a8);
  a11=(a5+a37);
  a38=arg[0]? arg[0][3] : 0;
  a39=sin(a38);
  a40=(a39*a5);
  a38=cos(a38);
  a41=3.8385800000000003e-06;
  a28=(a28*a22);
  a30=(a30*a36);
  a28=(a28-a30);
  a30=(a19*a32);
  a42=(a27*a35);
  a30=(a30+a42);
  a28=(a28+a30);
  a41=(a41+a28);
  a28=(a13*a12);
  a28=(a28*a7);
  a41=(a41-a28);
  a28=(a38*a41);
  a40=(a40+a28);
  a28=(a40*a39);
  a30=(a39*a41);
  a42=(a38*a37);
  a30=(a30+a42);
  a42=(a30*a38);
  a28=(a28+a42);
  a11=(a11-a28);
  a5=(a38*a5);
  a42=1.5100100000000000e-02;
  a43=(a29*a22);
  a44=(a25*a36);
  a43=(a43-a44);
  a44=(a19*a35);
  a45=(a27*a32);
  a44=(a44-a45);
  a43=(a43-a44);
  a42=(a42+a43);
  a43=(a13*a12);
  a43=(a43*a14);
  a42=(a42-a43);
  a43=(a34*a42);
  a43=(a23*a43);
  a44=(a39*a41);
  a43=(a43-a44);
  a5=(a5+a43);
  a43=(a5*a38);
  a41=(a38*a41);
  a44=-8.3409500000000002e-06;
  a29=(a29*a27);
  a25=(a25*a19);
  a29=(a29+a25);
  a25=(a22*a32);
  a45=(a36*a35);
  a25=(a25+a45);
  a29=(a29-a25);
  a44=(a44+a29);
  a13=(a13*a7);
  a13=(a13*a14);
  a44=(a44-a13);
  a13=(a44+a44);
  a13=(a23*a13);
  a37=(a39*a37);
  a13=(a13-a37);
  a41=(a41+a13);
  a13=(a41*a39);
  a43=(a43-a13);
  a11=(a11-a43);
  a11=(a11+a8);
  a4=(a4+a11);
  a11=1.3173985034014498e+02;
  a13=-1.1500000000000000e-01;
  a37=9.6628789931967618e-01;
  a12=(a37*a12);
  a29=(a39*a12);
  a7=(a37*a7);
  a25=(a38*a7);
  a29=(a29+a25);
  a29=(a13+a29);
  a25=casadi_sq(a29);
  a45=9.5000000000000001e-02;
  a46=(a38*a12);
  a37=(a37*a14);
  a14=(a23*a37);
  a47=(a39*a7);
  a14=(a14-a47);
  a46=(a46+a14);
  a46=(a45+a46);
  a14=casadi_sq(a46);
  a25=(a25+a14);
  a25=(a11*a25);
  a4=(a4+a25);
  a25=1.4909100000000000e+01;
  a43=(a43+a8);
  a25=(a25+a43);
  a43=8.7849999999999995e-01;
  a14=(a23*a38);
  a47=(a14*a12);
  a48=(a23*a39);
  a49=(a48*a7);
  a49=(a49+a37);
  a47=(a47-a49);
  a47=(a43+a47);
  a49=casadi_sq(a47);
  a50=casadi_sq(a29);
  a49=(a49+a50);
  a49=(a11*a49);
  a25=(a25+a49);
  a4=(a4-a25);
  a49=1.4978899999999999e+01;
  a28=(a28+a8);
  a49=(a49+a28);
  a28=casadi_sq(a47);
  a50=casadi_sq(a46);
  a28=(a28+a50);
  a28=(a11*a28);
  a49=(a49+a28);
  a49=(a49-a25);
  a28=(a4+a49);
  a50=arg[0]? arg[0][2] : 0;
  a51=sin(a50);
  a4=(a51*a4);
  a50=cos(a50);
  a52=1.5618399999999999e-02;
  a40=(a40*a14);
  a30=(a30*a48);
  a40=(a40-a30);
  a30=(a38*a44);
  a53=(a39*a42);
  a30=(a30+a53);
  a40=(a40-a30);
  a52=(a52+a40);
  a40=(a11*a47);
  a40=(a40*a29);
  a52=(a52-a40);
  a40=(a50*a52);
  a4=(a4+a40);
  a40=(a4*a51);
  a52=(a51*a52);
  a49=(a50*a49);
  a52=(a52+a49);
  a49=(a52*a50);
  a40=(a40+a49);
  a28=(a28-a40);
  a28=(a28+a25);
  a3=(a3+a28);
  a28=2.2815276210139692e+02;
  a49=7.6448484166629904e-01;
  a30=(a49*a47);
  a53=(a51*a30);
  a54=(a49*a29);
  a55=(a50*a54);
  a53=(a53+a55);
  a55=casadi_sq(a53);
  a56=-9.5000000000000001e-02;
  a49=(a49*a46);
  a57=(a56+a49);
  a58=casadi_sq(a57);
  a55=(a55+a58);
  a55=(a28*a55);
  a3=(a3+a55);
  a55=6.4941400000000002e+01;
  a55=(a55+a25);
  a58=1.1499999999999999e+00;
  a59=(a50*a30);
  a60=(a51*a54);
  a59=(a59-a60);
  a59=(a58+a59);
  a60=casadi_sq(a59);
  a61=casadi_sq(a53);
  a60=(a60+a61);
  a60=(a28*a60);
  a55=(a55+a60);
  a3=(a3-a55);
  a3=(a2*a3);
  a1=cos(a1);
  a60=1.8095600000000001e-01;
  a4=(a4*a50);
  a52=(a52*a51);
  a4=(a4-a52);
  a60=(a60+a4);
  a4=(a28*a59);
  a4=(a4*a53);
  a60=(a60-a4);
  a4=(a1*a60);
  a52=4.3700299999999999e+00;
  a61=-3.7419400000000003e-01;
  a62=(a5*a14);
  a63=(a41*a48);
  a62=(a62-a63);
  a63=(a38*a42);
  a64=(a39*a44);
  a63=(a63-a64);
  a62=(a62-a63);
  a61=(a61+a62);
  a47=(a11*a47);
  a47=(a47*a46);
  a61=(a61-a47);
  a47=(a34*a61);
  a62=(a47*a50);
  a63=9.9506100000000000e-02;
  a5=(a5*a39);
  a41=(a41*a38);
  a5=(a5+a41);
  a41=(a14*a44);
  a64=(a48*a42);
  a41=(a41+a64);
  a5=(a5-a41);
  a63=(a63+a5);
  a11=(a11*a29);
  a11=(a11*a46);
  a63=(a63-a11);
  a11=(a63+a63);
  a46=(a11*a51);
  a62=(a62-a46);
  a46=(a50*a61);
  a29=(a51*a63);
  a46=(a46-a29);
  a62=(a62-a46);
  a52=(a52+a62);
  a62=(a28*a59);
  a62=(a62*a57);
  a52=(a52-a62);
  a34=(a34*a52);
  a34=(a23*a34);
  a4=(a4+a34);
  a3=(a3+a4);
  a3=(a3*a2);
  a60=(a2*a60);
  a4=6.5632599999999996e+01;
  a40=(a40+a25);
  a4=(a4+a40);
  a40=casadi_sq(a59);
  a34=casadi_sq(a57);
  a40=(a40+a34);
  a40=(a28*a40);
  a4=(a4+a40);
  a4=(a4-a55);
  a4=(a1*a4);
  a40=-6.5738799999999998e-03;
  a47=(a47*a51);
  a11=(a11*a50);
  a47=(a47+a11);
  a11=(a50*a63);
  a34=(a51*a61);
  a11=(a11+a34);
  a47=(a47-a11);
  a40=(a40+a47);
  a28=(a28*a53);
  a28=(a28*a57);
  a40=(a40-a28);
  a28=(a40+a40);
  a28=(a23*a28);
  a4=(a4+a28);
  a60=(a60+a4);
  a60=(a60*a1);
  a3=(a3+a60);
  a3=(a3+a55);
  a0=(a0+a3);
  a3=2.0539432028848071e+02;
  a60=3.3000000000000002e-01;
  a4=6.8818549896659387e-01;
  a59=(a4*a59);
  a28=(a1*a59);
  a53=(a4*a53);
  a47=(a2*a53);
  a28=(a28-a47);
  a28=(a60+a28);
  a47=casadi_sq(a28);
  a11=(a23*a2);
  a34=(a11*a59);
  a62=(a23*a1);
  a46=(a62*a53);
  a4=(a4*a57);
  a46=(a46-a4);
  a34=(a34+a46);
  a46=casadi_sq(a34);
  a47=(a47+a46);
  a3=(a3*a47);
  a0=(a0+a3);
  a3=1.3177948799999999e+03;
  a47=8.0681894893991390e-01;
  a28=(a47*a28);
  a28=casadi_sq(a28);
  a47=(a47*a34);
  a47=casadi_sq(a47);
  a28=(a28+a47);
  a3=(a3*a28);
  a0=(a0+a3);
  if (res[0]!=0) res[0][0]=a0;
  a0=1.0632218799999998e+03;
  a3=(a0*a59);
  a3=(a3*a4);
  a52=(a52-a3);
  a52=(a2*a52);
  a3=(a0*a53);
  a3=(a3*a4);
  a40=(a40-a3);
  a40=(a1*a40);
  a3=casadi_sq(a59);
  a4=casadi_sq(a53);
  a3=(a3+a4);
  a3=(a0*a3);
  a55=(a55+a3);
  a3=(a23*a55);
  a40=(a40+a3);
  a52=(a52+a40);
  a40=-1.0632218799999998e+03;
  a40=(a40*a53);
  a40=(a11*a40);
  a0=(a0*a59);
  a0=(a62*a0);
  a40=(a40+a0);
  a40=(a60*a40);
  a52=(a52+a40);
  if (res[0]!=0) res[0][1]=a52;
  a40=7.3169387999999981e+02;
  a0=(a40*a30);
  a0=(a0*a49);
  a61=(a61-a0);
  a0=(a50*a61);
  a59=(a40*a54);
  a59=(a59*a49);
  a63=(a63-a59);
  a59=(a51*a63);
  a0=(a0-a59);
  a59=-7.3169387999999981e+02;
  a59=(a59*a54);
  a49=(a51*a59);
  a53=(a40*a30);
  a3=(a50*a53);
  a49=(a49+a3);
  a3=(a56*a49);
  a0=(a0-a3);
  a0=(a2*a0);
  a61=(a51*a61);
  a63=(a50*a63);
  a61=(a61+a63);
  a59=(a50*a59);
  a53=(a51*a53);
  a59=(a59-a53);
  a53=(a56*a59);
  a61=(a61+a53);
  a61=(a1*a61);
  a30=casadi_sq(a30);
  a54=casadi_sq(a54);
  a30=(a30+a54);
  a40=(a40*a30);
  a25=(a25+a40);
  a40=(a58*a49);
  a40=(a25+a40);
  a30=(a23*a40);
  a61=(a61+a30);
  a0=(a0+a61);
  a59=(a11*a59);
  a49=(a62*a49);
  a59=(a59+a49);
  a59=(a60*a59);
  a0=(a0+a59);
  if (res[0]!=0) res[0][2]=a0;
  a59=5.5936887999999988e+02;
  a49=(a59*a12);
  a49=(a49*a37);
  a42=(a42-a49);
  a49=(a14*a42);
  a61=(a59*a7);
  a61=(a61*a37);
  a44=(a44-a61);
  a61=(a48*a44);
  a37=casadi_sq(a12);
  a30=casadi_sq(a7);
  a37=(a37+a30);
  a37=(a59*a37);
  a8=(a8+a37);
  a61=(a61+a8);
  a49=(a49-a61);
  a61=-5.5936887999999988e+02;
  a61=(a61*a7);
  a7=(a38*a61);
  a59=(a59*a12);
  a12=(a39*a59);
  a7=(a7-a12);
  a12=(a13*a7);
  a37=(a39*a61);
  a30=(a38*a59);
  a37=(a37+a30);
  a30=(a45*a37);
  a12=(a12-a30);
  a49=(a49+a12);
  a12=(a50*a49);
  a30=(a39*a42);
  a54=(a38*a44);
  a30=(a30+a54);
  a61=(a14*a61);
  a59=(a48*a59);
  a61=(a61-a59);
  a59=(a45*a61);
  a54=(a43*a7);
  a59=(a59-a54);
  a30=(a30+a59);
  a59=(a51*a30);
  a12=(a12-a59);
  a59=(a51*a61);
  a54=(a50*a37);
  a59=(a59+a54);
  a54=(a56*a59);
  a12=(a12-a54);
  a12=(a2*a12);
  a49=(a51*a49);
  a30=(a50*a30);
  a49=(a49+a30);
  a30=(a50*a61);
  a54=(a51*a37);
  a30=(a30-a54);
  a54=(a56*a30);
  a53=(a58*a7);
  a54=(a54-a53);
  a49=(a49+a54);
  a49=(a1*a49);
  a42=(a38*a42);
  a54=(a23*a8);
  a44=(a39*a44);
  a54=(a54-a44);
  a42=(a42+a54);
  a37=(a43*a37);
  a61=(a13*a61);
  a37=(a37-a61);
  a42=(a42+a37);
  a37=(a58*a59);
  a37=(a42+a37);
  a61=(a23*a37);
  a49=(a49+a61);
  a12=(a12+a49);
  a30=(a11*a30);
  a59=(a62*a59);
  a59=(a59-a7);
  a30=(a30+a59);
  a30=(a60*a30);
  a12=(a12+a30);
  if (res[0]!=0) res[0][3]=a12;
  a30=5.4051137999999992e+02;
  a59=(a30*a15);
  a59=(a59*a6);
  a35=(a35-a59);
  a59=(a22*a35);
  a7=casadi_sq(a15);
  a49=casadi_sq(a18);
  a7=(a7+a49);
  a7=(a30*a7);
  a20=(a20+a7);
  a7=(a30*a18);
  a7=(a7*a6);
  a32=(a32-a7);
  a7=(a36*a32);
  a7=(a20-a7);
  a59=(a59+a7);
  a7=-5.4051137999999992e+02;
  a7=(a7*a18);
  a18=(a27*a7);
  a30=(a30*a15);
  a15=(a19*a30);
  a18=(a18+a15);
  a15=(a31*a18);
  a59=(a59-a15);
  a15=(a14*a59);
  a6=(a27*a35);
  a49=(a19*a32);
  a6=(a6+a49);
  a49=(a22*a7);
  a61=(a36*a30);
  a49=(a49-a61);
  a61=(a31*a49);
  a30=(a27*a30);
  a7=(a19*a7);
  a30=(a30-a7);
  a7=(a33*a30);
  a61=(a61-a7);
  a6=(a6+a61);
  a61=(a48*a6);
  a32=(a27*a32);
  a7=(a23*a20);
  a32=(a32+a7);
  a35=(a19*a35);
  a32=(a32-a35);
  a35=(a33*a18);
  a32=(a32+a35);
  a61=(a61+a32);
  a15=(a15-a61);
  a61=(a38*a49);
  a35=(a23*a30);
  a7=(a39*a18);
  a35=(a35-a7);
  a61=(a61+a35);
  a35=(a13*a61);
  a7=(a39*a49);
  a54=(a38*a18);
  a7=(a7+a54);
  a54=(a45*a7);
  a35=(a35-a54);
  a15=(a15+a35);
  a35=(a50*a15);
  a54=(a39*a59);
  a44=(a38*a6);
  a54=(a54+a44);
  a49=(a14*a49);
  a18=(a48*a18);
  a18=(a18+a30);
  a49=(a49-a18);
  a18=(a45*a49);
  a30=(a43*a61);
  a18=(a18-a30);
  a54=(a54+a18);
  a18=(a51*a54);
  a35=(a35-a18);
  a18=(a51*a49);
  a30=(a50*a7);
  a18=(a18+a30);
  a30=(a56*a18);
  a35=(a35-a30);
  a35=(a2*a35);
  a15=(a51*a15);
  a54=(a50*a54);
  a15=(a15+a54);
  a54=(a50*a49);
  a30=(a51*a7);
  a54=(a54-a30);
  a30=(a56*a54);
  a44=(a58*a61);
  a30=(a30-a44);
  a15=(a15+a30);
  a15=(a1*a15);
  a59=(a38*a59);
  a30=(a23*a32);
  a6=(a39*a6);
  a30=(a30-a6);
  a59=(a59+a30);
  a7=(a43*a7);
  a49=(a13*a49);
  a7=(a7-a49);
  a59=(a59+a7);
  a7=(a58*a18);
  a7=(a59+a7);
  a49=(a23*a7);
  a15=(a15+a49);
  a35=(a35+a15);
  a54=(a11*a54);
  a18=(a62*a18);
  a18=(a18-a61);
  a54=(a54+a18);
  a54=(a60*a54);
  a35=(a35+a54);
  if (res[0]!=0) res[0][4]=a35;
  a54=-9.1904705873289762e-07;
  a18=(a54*a24);
  a61=-7.5005128020000001e+01;
  a15=1.4868799999999858e-07;
  a49=(a15*a26);
  a61=(a61-a49);
  a18=(a18+a61);
  a61=2.2367343103292906e-21;
  a49=(a61*a10);
  a30=-4.3828101974802797e-10;
  a6=(a30*a9);
  a49=(a49+a6);
  a6=(a21*a49);
  a18=(a18-a6);
  a6=(a22*a18);
  a44=(a54*a9);
  a53=3.6727300881912449e-10;
  a63=(a15*a10);
  a53=(a53-a63);
  a44=(a44+a53);
  a53=(a16*a49);
  a44=(a44+a53);
  a54=(a54*a10);
  a15=(a15*a9);
  a54=(a54+a15);
  a24=(a61*a24);
  a26=(a30*a26);
  a24=(a24-a26);
  a21=(a21*a24);
  a61=(a61*a9);
  a30=(a30*a10);
  a61=(a61-a30);
  a16=(a16*a61);
  a21=(a21-a16);
  a54=(a54+a21);
  a21=(a36*a54);
  a21=(a44-a21);
  a6=(a6+a21);
  a21=(a27*a24);
  a16=(a19*a49);
  a21=(a21+a16);
  a16=(a31*a21);
  a6=(a6-a16);
  a16=(a14*a6);
  a30=(a27*a18);
  a10=(a19*a54);
  a30=(a30+a10);
  a22=(a22*a24);
  a36=(a36*a49);
  a36=(a61-a36);
  a22=(a22+a36);
  a31=(a31*a22);
  a49=(a27*a49);
  a61=(a23*a61);
  a49=(a49+a61);
  a24=(a19*a24);
  a49=(a49-a24);
  a24=(a33*a49);
  a31=(a31-a24);
  a30=(a30+a31);
  a31=(a48*a30);
  a27=(a27*a54);
  a54=(a23*a44);
  a27=(a27+a54);
  a19=(a19*a18);
  a27=(a27-a19);
  a33=(a33*a21);
  a27=(a27+a33);
  a31=(a31+a27);
  a16=(a16-a31);
  a31=(a38*a22);
  a33=(a23*a49);
  a19=(a39*a21);
  a33=(a33-a19);
  a31=(a31+a33);
  a33=(a13*a31);
  a19=(a39*a22);
  a18=(a38*a21);
  a19=(a19+a18);
  a18=(a45*a19);
  a33=(a33-a18);
  a16=(a16+a33);
  a33=(a50*a16);
  a18=(a39*a6);
  a54=(a38*a30);
  a18=(a18+a54);
  a14=(a14*a22);
  a48=(a48*a21);
  a48=(a48+a49);
  a14=(a14-a48);
  a45=(a45*a14);
  a48=(a43*a31);
  a45=(a45-a48);
  a18=(a18+a45);
  a45=(a51*a18);
  a33=(a33-a45);
  a45=(a51*a14);
  a48=(a50*a19);
  a45=(a45+a48);
  a48=(a56*a45);
  a33=(a33-a48);
  a2=(a2*a33);
  a16=(a51*a16);
  a18=(a50*a18);
  a16=(a16+a18);
  a50=(a50*a14);
  a51=(a51*a19);
  a50=(a50-a51);
  a56=(a56*a50);
  a51=(a58*a31);
  a56=(a56-a51);
  a16=(a16+a56);
  a1=(a1*a16);
  a38=(a38*a6);
  a6=(a23*a27);
  a39=(a39*a30);
  a6=(a6-a39);
  a38=(a38+a6);
  a43=(a43*a19);
  a13=(a13*a14);
  a43=(a43-a13);
  a38=(a38+a43);
  a58=(a58*a45);
  a58=(a38+a58);
  a23=(a23*a58);
  a1=(a1+a23);
  a2=(a2+a1);
  a11=(a11*a50);
  a62=(a62*a45);
  a62=(a62-a31);
  a11=(a11+a62);
  a60=(a60*a11);
  a2=(a2+a60);
  if (res[0]!=0) res[0][5]=a2;
  if (res[0]!=0) res[0][6]=a52;
  if (res[0]!=0) res[0][7]=a55;
  if (res[0]!=0) res[0][8]=a40;
  if (res[0]!=0) res[0][9]=a37;
  if (res[0]!=0) res[0][10]=a7;
  if (res[0]!=0) res[0][11]=a58;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a40;
  if (res[0]!=0) res[0][14]=a25;
  if (res[0]!=0) res[0][15]=a42;
  if (res[0]!=0) res[0][16]=a59;
  if (res[0]!=0) res[0][17]=a38;
  if (res[0]!=0) res[0][18]=a12;
  if (res[0]!=0) res[0][19]=a37;
  if (res[0]!=0) res[0][20]=a42;
  if (res[0]!=0) res[0][21]=a8;
  if (res[0]!=0) res[0][22]=a32;
  if (res[0]!=0) res[0][23]=a27;
  if (res[0]!=0) res[0][24]=a35;
  if (res[0]!=0) res[0][25]=a7;
  if (res[0]!=0) res[0][26]=a59;
  if (res[0]!=0) res[0][27]=a32;
  if (res[0]!=0) res[0][28]=a20;
  if (res[0]!=0) res[0][29]=a44;
  if (res[0]!=0) res[0][30]=a2;
  if (res[0]!=0) res[0][31]=a58;
  if (res[0]!=0) res[0][32]=a38;
  if (res[0]!=0) res[0][33]=a27;
  if (res[0]!=0) res[0][34]=a44;
  if (res[0]!=0) res[0][35]=a17;
  return 0;
}

CASADI_SYMBOL_EXPORT int M(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int M_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int M_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void M_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int M_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void M_release(int mem) {
}

CASADI_SYMBOL_EXPORT void M_incref(void) {
}

CASADI_SYMBOL_EXPORT void M_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int M_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int M_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real M_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* M_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* M_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* M_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* M_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int M_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int M_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
