/* This file was automatically generated by CasADi 3.6.3+.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kuka_kr_250_M_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};

/* M:(i0[6])->(o0[6x6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a7, a8, a9;
  a0=1.3983700000000001e+01;
  a1=arg[0]? arg[0][1] : 0;
  a2=sin(a1);
  a3=5.6097200000000029e+00;
  a4=1.6684699999999992e+00;
  a5=3.3203700000000003e-01;
  a6=3.6729200000000001e-01;
  a7=-1.5006717238748473e-02;
  a8=-7.5114186201820764e-03;
  a9=arg[0]? arg[0][5] : 0;
  a10=sin(a9);
  a11=(a8*a10);
  a12=2.7440399677331648e-07;
  a9=cos(a9);
  a13=(a12*a9);
  a11=(a11+a13);
  a13=(a11*a10);
  a14=(a12*a10);
  a15=-7.4952986185663970e-03;
  a16=(a15*a9);
  a14=(a14+a16);
  a16=(a14*a9);
  a13=(a13+a16);
  a7=(a7-a13);
  a8=(a8*a9);
  a16=2.3181824207758778e-18;
  a17=(a12*a10);
  a16=(a16-a17);
  a8=(a8+a16);
  a16=(a8*a9);
  a12=(a12*a9);
  a17=2.2876882631721649e-18;
  a15=(a15*a10);
  a17=(a17-a15);
  a12=(a12+a17);
  a17=(a12*a10);
  a16=(a16-a17);
  a7=(a7-a16);
  a17=1.5602500002566057e-02;
  a7=(a7+a17);
  a6=(a6+a7);
  a7=2.8944134484323061e+00;
  a15=2.2443299999999999e-05;
  a18=4.5718723091879198e-05;
  a19=(a18*a10);
  a20=-2.1795350793974585e-05;
  a21=(a20*a9);
  a19=(a19+a21);
  a15=(a15-a19);
  a21=casadi_sq(a15);
  a22=-1.2657699999999999e-02;
  a23=-5.8999999999999997e-02;
  a24=(a18*a9);
  a25=-5.7775455033809454e-14;
  a26=(a20*a10);
  a25=(a25-a26);
  a24=(a24+a25);
  a24=(a23+a24);
  a22=(a22-a24);
  a25=casadi_sq(a22);
  a21=(a21+a25);
  a21=(a7*a21);
  a6=(a6+a21);
  a21=3.7838899999999998e-01;
  a16=(a16+a17);
  a21=(a21+a16);
  a16=5.7693399999999999e-02;
  a25=2.0999999999999999e-01;
  a26=4.8966386501092529e-12;
  a27=(a26*a9);
  a18=(a18*a27);
  a28=1.1799003186097952e-02;
  a29=(a26*a10);
  a20=(a20*a29);
  a28=(a28-a20);
  a18=(a18+a28);
  a18=(a25+a18);
  a16=(a16-a18);
  a28=casadi_sq(a16);
  a20=casadi_sq(a15);
  a28=(a28+a20);
  a28=(a7*a28);
  a21=(a21+a28);
  a6=(a6-a21);
  a28=5.3328399999999998e-01;
  a13=(a13+a17);
  a28=(a28+a13);
  a13=casadi_sq(a16);
  a17=casadi_sq(a22);
  a13=(a13+a17);
  a13=(a7*a13);
  a28=(a28+a13);
  a28=(a28-a21);
  a13=(a6+a28);
  a17=arg[0]? arg[0][4] : 0;
  a20=sin(a17);
  a30=(a20*a6);
  a17=cos(a17);
  a31=-1.1269800000000000e-04;
  a11=(a11*a27);
  a14=(a14*a29);
  a11=(a11-a14);
  a14=2.3359782359283573e-07;
  a32=(a14*a9);
  a33=2.3671160835241077e-07;
  a34=(a33*a10);
  a32=(a32+a34);
  a11=(a11-a32);
  a31=(a31+a11);
  a11=(a7*a16);
  a11=(a11*a15);
  a31=(a31-a11);
  a11=(a17*a31);
  a30=(a30+a11);
  a11=(a30*a20);
  a32=(a20*a31);
  a34=(a17*a28);
  a32=(a32+a34);
  a34=(a32*a17);
  a11=(a11+a34);
  a13=(a13-a11);
  a28=(a20*a28);
  a34=-4.2569199999999999e-05;
  a35=(a8*a10);
  a36=(a12*a9);
  a35=(a35+a36);
  a36=(a14*a27);
  a37=(a33*a29);
  a36=(a36+a37);
  a35=(a35-a36);
  a34=(a34+a35);
  a15=(a7*a15);
  a15=(a15*a22);
  a34=(a34-a15);
  a15=(a34+a34);
  a15=(a26*a15);
  a28=(a28+a15);
  a15=(a17*a31);
  a28=(a28-a15);
  a15=(a28*a20);
  a31=(a20*a31);
  a35=2.;
  a36=1.0983999999999999e-01;
  a8=(a8*a27);
  a12=(a12*a29);
  a8=(a8-a12);
  a33=(a33*a9);
  a14=(a14*a10);
  a33=(a33-a14);
  a8=(a8-a33);
  a36=(a36+a8);
  a7=(a7*a16);
  a7=(a7*a22);
  a36=(a36-a7);
  a7=(a35*a36);
  a7=(a26*a7);
  a31=(a31+a7);
  a6=(a17*a6);
  a31=(a31-a6);
  a6=(a31*a17);
  a15=(a15-a6);
  a13=(a13-a15);
  a13=(a13+a21);
  a5=(a5+a13);
  a13=1.2867841502290386e+01;
  a6=4.4148300000000000e-06;
  a7=5.3225478853624497e-02;
  a22=7.7442500292503172e-02;
  a18=(a22*a18);
  a7=(a7+a18);
  a18=(a20*a7);
  a16=2.0705234733185261e-05;
  a19=(a22*a19);
  a16=(a16+a19);
  a19=(a17*a16);
  a18=(a18+a19);
  a6=(a6-a18);
  a19=casadi_sq(a6);
  a8=-1.7462100000000000e-01;
  a33=-3.4150000000000003e-01;
  a14=(a20*a16);
  a12=-1.1677456064047581e-02;
  a22=(a22*a24);
  a12=(a12+a22);
  a22=(a26*a12);
  a14=(a14+a22);
  a22=(a17*a7);
  a14=(a14-a22);
  a14=(a33+a14);
  a8=(a8-a14);
  a22=casadi_sq(a8);
  a19=(a19+a22);
  a19=(a13*a19);
  a5=(a5+a19);
  a19=4.6258300000000002e-02;
  a15=(a15+a21);
  a19=(a19+a15);
  a15=4.4925099999999999e-03;
  a22=5.8999999999999997e-02;
  a24=(a26*a17);
  a37=(a24*a7);
  a38=(a26*a20);
  a39=(a38*a16);
  a39=(a12-a39);
  a37=(a37+a39);
  a37=(a22+a37);
  a15=(a15-a37);
  a39=casadi_sq(a15);
  a40=casadi_sq(a6);
  a39=(a39+a40);
  a39=(a13*a39);
  a19=(a19+a39);
  a5=(a5-a19);
  a39=3.3070999999999995e-01;
  a11=(a11+a21);
  a39=(a39+a11);
  a11=casadi_sq(a15);
  a40=casadi_sq(a8);
  a11=(a11+a40);
  a11=(a13*a11);
  a39=(a39+a11);
  a39=(a39-a19);
  a11=(a5+a39);
  a40=arg[0]? arg[0][3] : 0;
  a41=sin(a40);
  a42=(a41*a5);
  a40=cos(a40);
  a43=3.8385800000000003e-06;
  a30=(a30*a24);
  a32=(a32*a38);
  a30=(a30-a32);
  a32=(a17*a34);
  a44=(a20*a36);
  a32=(a32+a44);
  a30=(a30+a32);
  a43=(a43+a30);
  a30=(a13*a15);
  a30=(a30*a6);
  a43=(a43-a30);
  a30=(a40*a43);
  a42=(a42+a30);
  a30=(a42*a41);
  a32=(a41*a43);
  a44=(a40*a39);
  a32=(a32+a44);
  a44=(a32*a40);
  a30=(a30+a44);
  a11=(a11-a30);
  a5=(a40*a5);
  a44=1.5100100000000000e-02;
  a45=(a31*a24);
  a46=(a28*a38);
  a45=(a45-a46);
  a46=(a17*a36);
  a47=(a20*a34);
  a46=(a46-a47);
  a45=(a45-a46);
  a44=(a44+a45);
  a15=(a13*a15);
  a15=(a15*a8);
  a44=(a44-a15);
  a15=(a35*a44);
  a15=(a26*a15);
  a45=(a41*a43);
  a15=(a15-a45);
  a5=(a5+a15);
  a15=(a5*a40);
  a43=(a40*a43);
  a45=-8.3409500000000002e-06;
  a31=(a31*a20);
  a28=(a28*a17);
  a31=(a31+a28);
  a28=(a24*a34);
  a46=(a38*a36);
  a28=(a28+a46);
  a31=(a31-a28);
  a45=(a45+a31);
  a13=(a13*a6);
  a13=(a13*a8);
  a45=(a45-a13);
  a13=(a45+a45);
  a13=(a26*a13);
  a39=(a41*a39);
  a13=(a13-a39);
  a43=(a43+a13);
  a13=(a43*a41);
  a15=(a15-a13);
  a11=(a11-a15);
  a11=(a11+a19);
  a4=(a4+a11);
  a11=4.4156843565123232e+01;
  a13=-1.1350499999999999e-01;
  a39=-1.1500000000000000e-01;
  a8=1.4269442236534754e-03;
  a6=6.8237261048868547e-01;
  a37=(a6*a37);
  a8=(a8+a37);
  a37=(a41*a8);
  a31=1.4022709280362364e-06;
  a18=(a6*a18);
  a31=(a31+a18);
  a18=(a40*a31);
  a37=(a37+a18);
  a37=(a39+a37);
  a13=(a13-a37);
  a18=casadi_sq(a13);
  a28=8.6968199999999996e-02;
  a46=9.5000000000000001e-02;
  a47=(a40*a8);
  a48=-5.5464412383855244e-02;
  a6=(a6*a14);
  a48=(a48+a6);
  a6=(a26*a48);
  a14=(a41*a31);
  a6=(a6-a14);
  a47=(a47+a6);
  a47=(a46+a47);
  a28=(a28-a47);
  a6=casadi_sq(a28);
  a18=(a18+a6);
  a18=(a11*a18);
  a4=(a4+a18);
  a18=1.4909100000000000e+01;
  a15=(a15+a19);
  a18=(a18+a15);
  a15=3.7510700000000002e-01;
  a6=8.7849999999999995e-01;
  a14=(a26*a40);
  a49=(a14*a8);
  a50=(a26*a41);
  a51=(a50*a31);
  a51=(a51+a48);
  a49=(a49-a51);
  a49=(a6+a49);
  a15=(a15-a49);
  a51=casadi_sq(a15);
  a52=casadi_sq(a13);
  a51=(a51+a52);
  a51=(a11*a51);
  a18=(a18+a51);
  a4=(a4-a18);
  a51=1.4978899999999999e+01;
  a30=(a30+a19);
  a51=(a51+a30);
  a30=casadi_sq(a15);
  a52=casadi_sq(a28);
  a30=(a30+a52);
  a30=(a11*a30);
  a51=(a51+a30);
  a51=(a51-a18);
  a30=(a4+a51);
  a52=arg[0]? arg[0][2] : 0;
  a53=sin(a52);
  a4=(a53*a4);
  a52=cos(a52);
  a54=1.5618399999999999e-02;
  a42=(a42*a14);
  a32=(a32*a50);
  a42=(a42-a32);
  a32=(a40*a45);
  a55=(a41*a44);
  a32=(a32+a55);
  a42=(a42-a32);
  a54=(a54+a42);
  a42=(a11*a15);
  a42=(a42*a13);
  a54=(a54-a42);
  a42=(a52*a54);
  a4=(a4+a42);
  a42=(a4*a53);
  a54=(a53*a54);
  a51=(a52*a51);
  a54=(a54+a51);
  a51=(a54*a52);
  a42=(a42+a51);
  a30=(a30-a42);
  a30=(a30+a18);
  a3=(a3+a30);
  a30=1.3638178224691441e+02;
  a51=9.3673499999999995e-04;
  a32=2.7898896071851048e-01;
  a55=2.5624165713113733e-01;
  a49=(a55*a49);
  a32=(a32+a49);
  a49=(a53*a32);
  a56=-8.4420290707330259e-02;
  a37=(a55*a37);
  a56=(a56+a37);
  a37=(a52*a56);
  a49=(a49+a37);
  a51=(a51-a49);
  a37=casadi_sq(a51);
  a57=-2.2289300000000001e-01;
  a58=-9.5000000000000001e-02;
  a59=6.4683324314287818e-02;
  a55=(a55*a47);
  a59=(a59+a55);
  a55=(a58+a59);
  a57=(a57-a55);
  a47=casadi_sq(a57);
  a37=(a37+a47);
  a37=(a30*a37);
  a3=(a3+a37);
  a37=6.4941400000000002e+01;
  a37=(a37+a18);
  a47=4.4928299999999999e-01;
  a60=1.1499999999999999e+00;
  a61=(a52*a32);
  a62=(a53*a56);
  a61=(a61-a62);
  a61=(a60+a61);
  a47=(a47-a61);
  a62=casadi_sq(a47);
  a63=casadi_sq(a51);
  a62=(a62+a63);
  a62=(a30*a62);
  a37=(a37+a62);
  a3=(a3-a37);
  a3=(a2*a3);
  a1=cos(a1);
  a62=1.8095600000000001e-01;
  a4=(a4*a52);
  a54=(a54*a53);
  a4=(a4-a54);
  a62=(a62+a4);
  a4=(a30*a47);
  a4=(a4*a51);
  a62=(a62-a4);
  a4=(a1*a62);
  a54=4.3700299999999999e+00;
  a63=-3.7419400000000003e-01;
  a64=(a5*a14);
  a65=(a43*a50);
  a64=(a64-a65);
  a65=(a40*a44);
  a66=(a41*a45);
  a65=(a65-a66);
  a64=(a64-a65);
  a63=(a63+a64);
  a15=(a11*a15);
  a15=(a15*a28);
  a63=(a63-a15);
  a15=(a35*a63);
  a64=(a15*a52);
  a65=9.9506100000000000e-02;
  a5=(a5*a41);
  a43=(a43*a40);
  a5=(a5+a43);
  a43=(a14*a45);
  a66=(a50*a44);
  a43=(a43+a66);
  a5=(a5-a43);
  a65=(a65+a5);
  a11=(a11*a13);
  a11=(a11*a28);
  a65=(a65-a11);
  a11=(a65+a65);
  a28=(a11*a53);
  a64=(a64-a28);
  a28=(a52*a63);
  a13=(a53*a65);
  a28=(a28-a13);
  a64=(a64-a28);
  a54=(a54+a64);
  a64=(a30*a47);
  a64=(a64*a57);
  a54=(a54-a64);
  a35=(a35*a54);
  a35=(a26*a35);
  a4=(a4+a35);
  a3=(a3+a4);
  a3=(a3*a2);
  a62=(a2*a62);
  a4=6.5632599999999996e+01;
  a42=(a42+a18);
  a4=(a4+a42);
  a47=casadi_sq(a47);
  a42=casadi_sq(a57);
  a47=(a47+a42);
  a47=(a30*a47);
  a4=(a4+a47);
  a4=(a4-a37);
  a4=(a1*a4);
  a47=-6.5738799999999998e-03;
  a15=(a15*a53);
  a11=(a11*a52);
  a15=(a15+a11);
  a11=(a52*a65);
  a42=(a53*a63);
  a11=(a11+a42);
  a15=(a15-a11);
  a47=(a47+a15);
  a30=(a30*a51);
  a30=(a30*a57);
  a47=(a47-a30);
  a30=(a47+a47);
  a30=(a26*a30);
  a4=(a4+a30);
  a62=(a62+a4);
  a62=(a62*a1);
  a3=(a3+a62);
  a3=(a3+a37);
  a0=(a0+a3);
  a3=1.7532655976481567e+02;
  a62=-2.9919600000000001e-02;
  a4=3.3000000000000002e-01;
  a30=2.6445994953898183e-01;
  a57=4.1137334477605025e-01;
  a61=(a57*a61);
  a30=(a30+a61);
  a61=(a1*a30);
  a51=5.5138718988120654e-04;
  a49=(a57*a49);
  a51=(a51+a49);
  a49=(a2*a51);
  a61=(a61-a49);
  a61=(a4+a61);
  a62=(a62-a61);
  a62=casadi_sq(a62);
  a49=-4.4684000000000000e-03;
  a15=(a26*a2);
  a11=(a15*a30);
  a42=(a26*a1);
  a35=(a42*a51);
  a64=-1.3120076106283182e-01;
  a57=(a57*a55);
  a64=(a64+a57);
  a35=(a35-a64);
  a11=(a11+a35);
  a49=(a49-a11);
  a49=casadi_sq(a49);
  a62=(a62+a49);
  a3=(a3*a62);
  a0=(a0+a3);
  a3=8.1779588000000001e+02;
  a62=-9.3137205959022452e-03;
  a49=6.8870838527579770e-01;
  a61=(a49*a61);
  a62=(a62+a61);
  a62=casadi_sq(a62);
  a61=-1.3909754512336258e-03;
  a49=(a49*a11);
  a61=(a61+a49);
  a61=casadi_sq(a61);
  a62=(a62+a61);
  a3=(a3*a62);
  a0=(a0+a3);
  if (res[0]!=0) res[0][0]=a0;
  a0=5.6322288000000003e+02;
  a3=(a0*a30);
  a3=(a3*a64);
  a54=(a54-a3);
  a54=(a2*a54);
  a3=(a0*a51);
  a3=(a3*a64);
  a47=(a47-a3);
  a47=(a1*a47);
  a3=casadi_sq(a30);
  a64=casadi_sq(a51);
  a3=(a3+a64);
  a3=(a0*a3);
  a37=(a37+a3);
  a3=(a26*a37);
  a47=(a47+a3);
  a54=(a54+a47);
  a47=-5.6322288000000003e+02;
  a47=(a47*a51);
  a47=(a15*a47);
  a0=(a0*a30);
  a0=(a42*a0);
  a47=(a47+a0);
  a47=(a4*a47);
  a54=(a54+a47);
  if (res[0]!=0) res[0][1]=a54;
  a47=2.3169487999999998e+02;
  a0=(a47*a32);
  a0=(a0*a59);
  a63=(a63-a0);
  a0=(a52*a63);
  a30=(a47*a56);
  a30=(a30*a59);
  a65=(a65-a30);
  a30=(a53*a65);
  a0=(a0-a30);
  a30=-2.3169487999999998e+02;
  a30=(a30*a56);
  a59=(a53*a30);
  a51=(a47*a32);
  a3=(a52*a51);
  a59=(a59+a3);
  a3=(a58*a59);
  a0=(a0-a3);
  a0=(a2*a0);
  a63=(a53*a63);
  a65=(a52*a65);
  a63=(a63+a65);
  a30=(a52*a30);
  a51=(a53*a51);
  a30=(a30-a51);
  a51=(a58*a30);
  a63=(a63+a51);
  a63=(a1*a63);
  a32=casadi_sq(a32);
  a56=casadi_sq(a56);
  a32=(a32+a56);
  a47=(a47*a32);
  a18=(a18+a47);
  a47=(a60*a59);
  a47=(a18+a47);
  a32=(a26*a47);
  a63=(a63+a32);
  a0=(a0+a63);
  a30=(a15*a30);
  a59=(a42*a59);
  a30=(a30+a59);
  a30=(a4*a30);
  a0=(a0+a30);
  if (res[0]!=0) res[0][2]=a0;
  a30=5.9369880000000002e+01;
  a59=(a30*a8);
  a59=(a59*a48);
  a44=(a44-a59);
  a59=(a14*a44);
  a63=(a30*a31);
  a63=(a63*a48);
  a45=(a45-a63);
  a63=(a50*a45);
  a48=casadi_sq(a8);
  a32=casadi_sq(a31);
  a48=(a48+a32);
  a48=(a30*a48);
  a19=(a19+a48);
  a63=(a63+a19);
  a59=(a59-a63);
  a63=-5.9369880000000002e+01;
  a63=(a63*a31);
  a31=(a40*a63);
  a30=(a30*a8);
  a8=(a41*a30);
  a31=(a31-a8);
  a8=(a39*a31);
  a48=(a41*a63);
  a32=(a40*a30);
  a48=(a48+a32);
  a32=(a46*a48);
  a8=(a8-a32);
  a59=(a59+a8);
  a8=(a52*a59);
  a32=(a41*a44);
  a56=(a40*a45);
  a32=(a32+a56);
  a63=(a14*a63);
  a30=(a50*a30);
  a63=(a63-a30);
  a30=(a46*a63);
  a56=(a6*a31);
  a30=(a30-a56);
  a32=(a32+a30);
  a30=(a53*a32);
  a8=(a8-a30);
  a30=(a53*a63);
  a56=(a52*a48);
  a30=(a30+a56);
  a56=(a58*a30);
  a8=(a8-a56);
  a8=(a2*a8);
  a59=(a53*a59);
  a32=(a52*a32);
  a59=(a59+a32);
  a32=(a52*a63);
  a56=(a53*a48);
  a32=(a32-a56);
  a56=(a58*a32);
  a51=(a60*a31);
  a56=(a56-a51);
  a59=(a59+a56);
  a59=(a1*a59);
  a44=(a40*a44);
  a56=(a26*a19);
  a45=(a41*a45);
  a56=(a56-a45);
  a44=(a44+a56);
  a48=(a6*a48);
  a63=(a39*a63);
  a48=(a48-a63);
  a44=(a44+a48);
  a48=(a60*a30);
  a48=(a44+a48);
  a63=(a26*a48);
  a59=(a59+a63);
  a8=(a8+a59);
  a32=(a15*a32);
  a30=(a42*a30);
  a30=(a30-a31);
  a32=(a32+a30);
  a32=(a4*a32);
  a8=(a8+a32);
  if (res[0]!=0) res[0][3]=a8;
  a32=4.0512380000000000e+01;
  a30=(a32*a7);
  a30=(a30*a12);
  a36=(a36-a30);
  a30=(a24*a36);
  a31=casadi_sq(a7);
  a59=casadi_sq(a16);
  a31=(a31+a59);
  a31=(a32*a31);
  a21=(a21+a31);
  a31=(a32*a16);
  a31=(a31*a12);
  a34=(a34-a31);
  a31=(a38*a34);
  a31=(a21-a31);
  a30=(a30+a31);
  a31=-4.0512380000000000e+01;
  a31=(a31*a16);
  a16=(a20*a31);
  a32=(a32*a7);
  a7=(a17*a32);
  a16=(a16+a7);
  a7=(a33*a16);
  a30=(a30-a7);
  a7=(a14*a30);
  a12=(a20*a36);
  a59=(a17*a34);
  a12=(a12+a59);
  a59=(a24*a31);
  a63=(a38*a32);
  a59=(a59-a63);
  a63=(a33*a59);
  a32=(a20*a32);
  a31=(a17*a31);
  a32=(a32-a31);
  a31=(a22*a32);
  a63=(a63-a31);
  a12=(a12+a63);
  a63=(a50*a12);
  a34=(a20*a34);
  a31=(a26*a21);
  a34=(a34+a31);
  a36=(a17*a36);
  a34=(a34-a36);
  a36=(a22*a16);
  a34=(a34+a36);
  a63=(a63+a34);
  a7=(a7-a63);
  a63=(a40*a59);
  a36=(a26*a32);
  a31=(a41*a16);
  a36=(a36-a31);
  a63=(a63+a36);
  a36=(a39*a63);
  a31=(a41*a59);
  a56=(a40*a16);
  a31=(a31+a56);
  a56=(a46*a31);
  a36=(a36-a56);
  a7=(a7+a36);
  a36=(a52*a7);
  a56=(a41*a30);
  a45=(a40*a12);
  a56=(a56+a45);
  a59=(a14*a59);
  a16=(a50*a16);
  a16=(a16+a32);
  a59=(a59-a16);
  a16=(a46*a59);
  a32=(a6*a63);
  a16=(a16-a32);
  a56=(a56+a16);
  a16=(a53*a56);
  a36=(a36-a16);
  a16=(a53*a59);
  a32=(a52*a31);
  a16=(a16+a32);
  a32=(a58*a16);
  a36=(a36-a32);
  a36=(a2*a36);
  a7=(a53*a7);
  a56=(a52*a56);
  a7=(a7+a56);
  a56=(a52*a59);
  a32=(a53*a31);
  a56=(a56-a32);
  a32=(a58*a56);
  a45=(a60*a63);
  a32=(a32-a45);
  a7=(a7+a32);
  a7=(a1*a7);
  a30=(a40*a30);
  a32=(a26*a34);
  a12=(a41*a12);
  a32=(a32-a12);
  a30=(a30+a32);
  a31=(a6*a31);
  a59=(a39*a59);
  a31=(a31-a59);
  a30=(a30+a31);
  a31=(a60*a16);
  a31=(a30+a31);
  a59=(a26*a31);
  a7=(a7+a59);
  a36=(a36+a7);
  a56=(a15*a56);
  a16=(a42*a16);
  a16=(a16-a63);
  a56=(a56+a16);
  a56=(a4*a56);
  a36=(a36+a56);
  if (res[0]!=0) res[0][4]=a36;
  a56=1.9291253163065122e-06;
  a16=(a56*a27);
  a63=-1.5602508050695458e-02;
  a7=-5.7322152652901646e-07;
  a59=(a7*a29);
  a63=(a63-a59);
  a16=(a16+a63);
  a63=6.8380297673999984e-05;
  a59=(a63*a10);
  a32=1.4343700745399996e-04;
  a12=(a32*a9);
  a59=(a59+a12);
  a12=(a23*a59);
  a16=(a16-a12);
  a12=(a24*a16);
  a45=(a56*a9);
  a51=7.6399843959676155e-14;
  a65=(a7*a10);
  a51=(a51-a65);
  a45=(a45+a51);
  a51=(a25*a59);
  a45=(a45+a51);
  a56=(a56*a10);
  a7=(a7*a9);
  a56=(a56+a7);
  a27=(a63*a27);
  a29=(a32*a29);
  a27=(a27-a29);
  a23=(a23*a27);
  a63=(a63*a9);
  a32=(a32*a10);
  a63=(a63-a32);
  a25=(a25*a63);
  a23=(a23-a25);
  a56=(a56+a23);
  a23=(a38*a56);
  a23=(a45-a23);
  a12=(a12+a23);
  a23=(a20*a27);
  a25=(a17*a59);
  a23=(a23+a25);
  a25=(a33*a23);
  a12=(a12-a25);
  a25=(a14*a12);
  a32=(a20*a16);
  a10=(a17*a56);
  a32=(a32+a10);
  a24=(a24*a27);
  a38=(a38*a59);
  a38=(a63-a38);
  a24=(a24+a38);
  a33=(a33*a24);
  a59=(a20*a59);
  a63=(a26*a63);
  a59=(a59+a63);
  a27=(a17*a27);
  a59=(a59-a27);
  a27=(a22*a59);
  a33=(a33-a27);
  a32=(a32+a33);
  a33=(a50*a32);
  a20=(a20*a56);
  a56=(a26*a45);
  a20=(a20+a56);
  a17=(a17*a16);
  a20=(a20-a17);
  a22=(a22*a23);
  a20=(a20+a22);
  a33=(a33+a20);
  a25=(a25-a33);
  a33=(a40*a24);
  a22=(a26*a59);
  a17=(a41*a23);
  a22=(a22-a17);
  a33=(a33+a22);
  a22=(a39*a33);
  a17=(a41*a24);
  a16=(a40*a23);
  a17=(a17+a16);
  a16=(a46*a17);
  a22=(a22-a16);
  a25=(a25+a22);
  a22=(a52*a25);
  a16=(a41*a12);
  a56=(a40*a32);
  a16=(a16+a56);
  a14=(a14*a24);
  a50=(a50*a23);
  a50=(a50+a59);
  a14=(a14-a50);
  a46=(a46*a14);
  a50=(a6*a33);
  a46=(a46-a50);
  a16=(a16+a46);
  a46=(a53*a16);
  a22=(a22-a46);
  a46=(a53*a14);
  a50=(a52*a17);
  a46=(a46+a50);
  a50=(a58*a46);
  a22=(a22-a50);
  a2=(a2*a22);
  a25=(a53*a25);
  a16=(a52*a16);
  a25=(a25+a16);
  a52=(a52*a14);
  a53=(a53*a17);
  a52=(a52-a53);
  a58=(a58*a52);
  a53=(a60*a33);
  a58=(a58-a53);
  a25=(a25+a58);
  a1=(a1*a25);
  a40=(a40*a12);
  a12=(a26*a20);
  a41=(a41*a32);
  a12=(a12-a41);
  a40=(a40+a12);
  a6=(a6*a17);
  a39=(a39*a14);
  a6=(a6-a39);
  a40=(a40+a6);
  a60=(a60*a46);
  a60=(a40+a60);
  a26=(a26*a60);
  a1=(a1+a26);
  a2=(a2+a1);
  a15=(a15*a52);
  a42=(a42*a46);
  a42=(a42-a33);
  a15=(a15+a42);
  a4=(a4*a15);
  a2=(a2+a4);
  if (res[0]!=0) res[0][5]=a2;
  if (res[0]!=0) res[0][6]=a54;
  if (res[0]!=0) res[0][7]=a37;
  if (res[0]!=0) res[0][8]=a47;
  if (res[0]!=0) res[0][9]=a48;
  if (res[0]!=0) res[0][10]=a31;
  if (res[0]!=0) res[0][11]=a60;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a47;
  if (res[0]!=0) res[0][14]=a18;
  if (res[0]!=0) res[0][15]=a44;
  if (res[0]!=0) res[0][16]=a30;
  if (res[0]!=0) res[0][17]=a40;
  if (res[0]!=0) res[0][18]=a8;
  if (res[0]!=0) res[0][19]=a48;
  if (res[0]!=0) res[0][20]=a44;
  if (res[0]!=0) res[0][21]=a19;
  if (res[0]!=0) res[0][22]=a34;
  if (res[0]!=0) res[0][23]=a20;
  if (res[0]!=0) res[0][24]=a36;
  if (res[0]!=0) res[0][25]=a31;
  if (res[0]!=0) res[0][26]=a30;
  if (res[0]!=0) res[0][27]=a34;
  if (res[0]!=0) res[0][28]=a21;
  if (res[0]!=0) res[0][29]=a45;
  if (res[0]!=0) res[0][30]=a2;
  if (res[0]!=0) res[0][31]=a60;
  if (res[0]!=0) res[0][32]=a40;
  if (res[0]!=0) res[0][33]=a20;
  if (res[0]!=0) res[0][34]=a45;
  a45=1.5602508050695458e-02;
  if (res[0]!=0) res[0][35]=a45;
  return 0;
}

CASADI_SYMBOL_EXPORT int M(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int M_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int M_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void M_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int M_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void M_release(int mem) {
}

CASADI_SYMBOL_EXPORT void M_incref(void) {
}

CASADI_SYMBOL_EXPORT void M_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int M_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int M_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real M_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* M_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* M_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* M_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* M_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int M_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
