/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) indy7_v2_M_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};

/* M:(i0[6])->(o0[6x6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a8, a9;
  a0=6.0480470000000001e-02;
  a1=arg[0]? arg[0][1] : 0;
  a2=sin(a1);
  a3=7.4655601000000005e-01;
  a4=1.1373278000000001e-01;
  a5=2.7952270000000001e-02;
  a6=1.7718760000000000e-02;
  a7=5.1850000000000008e-04;
  a8=2.6564000000000004e-04;
  a9=-2.0510348974767112e-10;
  a10=arg[0]? arg[0][5] : 0;
  a11=sin(a10);
  a12=(a9*a11);
  a13=(a8*a12);
  a14=2.6000000000000000e-07;
  a10=cos(a10);
  a15=(a9*a10);
  a16=(a14*a15);
  a13=(a13+a16);
  a16=(a13*a12);
  a17=(a14*a12);
  a18=2.5286000000000004e-04;
  a19=(a18*a15);
  a20=-1.3980000000000000e-05;
  a19=(a19+a20);
  a17=(a17+a19);
  a19=(a17*a15);
  a16=(a16+a19);
  a7=(a7-a16);
  a8=(a8*a11);
  a19=(a14*a10);
  a8=(a8+a19);
  a19=(a8*a11);
  a20=2.8673467866724424e-15;
  a18=(a18*a10);
  a20=(a20-a18);
  a14=(a14*a11);
  a20=(a20-a14);
  a14=(a20*a10);
  a19=(a19-a14);
  a7=(a7-a19);
  a14=5.1274999999999997e-04;
  a7=(a7+a14);
  a6=(a6+a7);
  a7=3.3873141986715449e-01;
  a18=-3.5412299999999998e-03;
  a21=5.1999999999999998e-02;
  a22=-7.1500999999999997e-04;
  a23=(a22*a15);
  a24=3.2191230000000001e-02;
  a23=(a23+a24);
  a23=(a21+a23);
  a18=(a18-a23);
  a24=casadi_sq(a18);
  a25=7.6507619999999998e-02;
  a26=8.5000000000000006e-02;
  a27=-6.6025336122699228e-12;
  a28=(a22*a10);
  a27=(a27-a28);
  a27=(a26+a27);
  a25=(a25-a27);
  a28=casadi_sq(a25);
  a24=(a24+a28);
  a24=(a7*a24);
  a6=(a6+a24);
  a24=3.5834800000000000e-03;
  a19=(a19+a14);
  a24=(a24+a19);
  a19=-2.2537999999999999e-04;
  a22=(a22*a11);
  a19=(a19+a22);
  a28=casadi_sq(a19);
  a29=casadi_sq(a18);
  a28=(a28+a29);
  a28=(a7*a28);
  a24=(a24+a28);
  a6=(a6-a24);
  a28=1.5936160000000001e-02;
  a16=(a16+a14);
  a28=(a28+a16);
  a16=casadi_sq(a19);
  a14=casadi_sq(a25);
  a16=(a16+a14);
  a16=(a7*a16);
  a28=(a28+a16);
  a28=(a28-a24);
  a16=(a6+a28);
  a14=arg[0]? arg[0][4] : 0;
  a29=sin(a14);
  a30=(a9*a29);
  a31=(a30*a6);
  a14=cos(a14);
  a32=(a9*a14);
  a33=9.0399999999999998e-06;
  a13=(a13*a10);
  a17=(a17*a11);
  a13=(a13-a17);
  a17=-6.9900000000000000e-06;
  a34=(a17*a11);
  a13=(a13+a34);
  a33=(a33+a13);
  a13=(a7*a19);
  a13=(a13*a18);
  a33=(a33-a13);
  a13=(a32*a33);
  a34=2.;
  a35=-4.3359999999999998e-05;
  a36=(a17*a12);
  a37=(a8*a10);
  a38=(a20*a11);
  a37=(a37+a38);
  a36=(a36-a37);
  a35=(a35+a36);
  a19=(a7*a19);
  a19=(a19*a25);
  a35=(a35-a19);
  a19=(a34*a35);
  a13=(a13-a19);
  a31=(a31+a13);
  a13=(a31*a30);
  a36=(a30*a33);
  a37=(a32*a28);
  a38=-6.9656000000000004e-04;
  a20=(a20*a15);
  a8=(a8*a12);
  a20=(a20-a8);
  a17=(a17*a10);
  a20=(a20-a17);
  a38=(a38+a20);
  a7=(a7*a18);
  a7=(a7*a25);
  a38=(a38-a7);
  a7=(a38+a38);
  a37=(a37-a7);
  a36=(a36+a37);
  a37=(a36*a32);
  a13=(a13+a37);
  a16=(a16-a13);
  a6=(a29*a6);
  a37=(a14*a33);
  a19=(a9*a19);
  a37=(a37+a19);
  a6=(a6+a37);
  a37=(a6*a29);
  a33=(a29*a33);
  a28=(a14*a28);
  a7=(a9*a7);
  a28=(a28+a7);
  a33=(a33+a28);
  a28=(a33*a14);
  a37=(a37+a28);
  a16=(a16-a37);
  a16=(a16+a24);
  a5=(a5+a16);
  a16=1.1941510182375998e+00;
  a28=-7.1059709999999998e-02;
  a7=-1.1400000000000000e-01;
  a19=-1.9253194201577831e-04;
  a25=1.4574522133384354e-01;
  a22=(a25*a22);
  a19=(a19-a22);
  a22=(a30*a19);
  a18=-3.0251126498559528e-03;
  a23=(a25*a23);
  a18=(a18+a23);
  a23=(a32*a18);
  a20=6.5356999989374401e-02;
  a25=(a25*a27);
  a20=(a20+a25);
  a23=(a23-a20);
  a22=(a22+a23);
  a22=(a7+a22);
  a28=(a28-a22);
  a23=casadi_sq(a28);
  a25=7.6453289999999993e-02;
  a27=8.3500000000000005e-02;
  a17=(a29*a19);
  a8=(a14*a18);
  a39=(a9*a20);
  a8=(a8+a39);
  a17=(a17+a8);
  a17=(a27+a17);
  a25=(a25-a17);
  a8=casadi_sq(a25);
  a23=(a23+a8);
  a23=(a16*a23);
  a5=(a5+a23);
  a23=1.4955140000000000e-02;
  a37=(a37+a24);
  a23=(a23+a37);
  a37=-2.6808000000000002e-04;
  a8=(a14*a19);
  a39=(a29*a18);
  a8=(a8-a39);
  a37=(a37-a8);
  a39=casadi_sq(a37);
  a40=casadi_sq(a28);
  a39=(a39+a40);
  a39=(a16*a39);
  a23=(a23+a39);
  a5=(a5-a23);
  a39=1.4398500000000000e-02;
  a13=(a13+a24);
  a39=(a39+a13);
  a13=casadi_sq(a37);
  a40=casadi_sq(a25);
  a13=(a13+a40);
  a13=(a16*a13);
  a39=(a39+a13);
  a39=(a39-a23);
  a13=(a5+a39);
  a40=-1.0206823934513925e-11;
  a41=arg[0]? arg[0][3] : 0;
  a42=cos(a41);
  a43=(a40*a42);
  a44=2.0510360076997358e-10;
  a41=sin(a41);
  a45=(a44*a41);
  a43=(a43+a45);
  a45=(a43*a5);
  a44=(a44*a42);
  a46=(a40*a41);
  a44=(a44-a46);
  a46=3.9379999999999999e-05;
  a31=(a31*a14);
  a36=(a36*a29);
  a31=(a31-a36);
  a36=(a14*a35);
  a47=(a29*a38);
  a36=(a36-a47);
  a31=(a31+a36);
  a46=(a46+a31);
  a31=(a16*a37);
  a31=(a31*a28);
  a46=(a46-a31);
  a31=(a44*a46);
  a36=-4.7129999999999998e-05;
  a47=(a6*a14);
  a48=(a33*a29);
  a47=(a47-a48);
  a48=(a32*a35);
  a49=(a30*a38);
  a48=(a48-a49);
  a47=(a47-a48);
  a36=(a36+a47);
  a37=(a16*a37);
  a37=(a37*a25);
  a36=(a36-a37);
  a37=(a34*a36);
  a31=(a31-a37);
  a45=(a45+a31);
  a31=(a45*a43);
  a47=(a43*a46);
  a48=(a44*a39);
  a49=-1.2650870000000000e-02;
  a6=(a6*a30);
  a33=(a33*a32);
  a6=(a6+a33);
  a33=(a14*a38);
  a50=(a29*a35);
  a33=(a33+a50);
  a6=(a6-a33);
  a49=(a49+a6);
  a16=(a16*a28);
  a16=(a16*a25);
  a49=(a49-a16);
  a16=(a49+a49);
  a48=(a48-a16);
  a47=(a47+a48);
  a48=(a47*a44);
  a31=(a31+a48);
  a13=(a13-a31);
  a37=(a9*a37);
  a48=(a42*a46);
  a37=(a37-a48);
  a5=(a41*a5);
  a37=(a37-a5);
  a5=(a37*a41);
  a16=(a9*a16);
  a39=(a42*a39);
  a16=(a16-a39);
  a46=(a41*a46);
  a16=(a16-a46);
  a46=(a16*a42);
  a5=(a5+a46);
  a13=(a13+a5);
  a13=(a13+a23);
  a4=(a4+a13);
  a13=1.7269088565134467e+00;
  a46=-1.6802207999999999e-01;
  a39=-2.6700000000000002e-01;
  a48=-1.1766571185642421e-04;
  a25=5.6107985729474696e-01;
  a8=(a25*a8);
  a48=(a48+a8);
  a8=(a43*a48);
  a28=-3.1189538053793889e-02;
  a22=(a25*a22);
  a28=(a28+a22);
  a22=(a44*a28);
  a6=3.3556888957086084e-02;
  a25=(a25*a17);
  a6=(a6+a25);
  a22=(a22-a6);
  a8=(a8+a22);
  a8=(a39+a8);
  a46=(a46-a8);
  a22=casadi_sq(a46);
  a25=-7.0256710000000000e-02;
  a17=-7.4999999999999997e-02;
  a33=(a9*a6);
  a50=(a42*a28);
  a33=(a33-a50);
  a50=(a41*a48);
  a33=(a33-a50);
  a33=(a17+a33);
  a25=(a25-a33);
  a50=casadi_sq(a25);
  a22=(a22+a50);
  a22=(a13*a22);
  a4=(a4+a22);
  a22=1.0021441000000000e-01;
  a5=(a23-a5);
  a22=(a22+a5);
  a5=6.6909999999999995e-05;
  a50=-2.0934551898781983e-21;
  a51=(a50*a41);
  a51=(a51-a42);
  a52=(a51*a48);
  a50=(a50*a42);
  a50=(a41+a50);
  a53=(a50*a28);
  a54=1.0206823934513925e-11;
  a55=(a54*a6);
  a53=(a53+a55);
  a52=(a52+a53);
  a5=(a5-a52);
  a53=casadi_sq(a5);
  a55=casadi_sq(a46);
  a53=(a53+a55);
  a53=(a13*a53);
  a22=(a22+a53);
  a4=(a4-a22);
  a53=1.6272339999999996e-02;
  a31=(a31+a23);
  a53=(a53+a31);
  a31=casadi_sq(a5);
  a55=casadi_sq(a25);
  a31=(a31+a55);
  a31=(a13*a31);
  a53=(a53+a31);
  a53=(a53-a22);
  a31=(a4+a53);
  a55=arg[0]? arg[0][2] : 0;
  a56=cos(a55);
  a57=(a40*a56);
  a55=sin(a55);
  a57=(a57-a55);
  a4=(a57*a4);
  a40=(a40*a55);
  a40=(a40+a56);
  a58=-3.6860000000000003e-05;
  a45=(a45*a51);
  a47=(a47*a50);
  a45=(a45+a47);
  a47=(a41*a49);
  a59=(a42*a36);
  a47=(a47-a59);
  a45=(a45+a47);
  a58=(a58+a45);
  a45=(a13*a5);
  a45=(a45*a46);
  a58=(a58-a45);
  a45=(a40*a58);
  a4=(a4-a45);
  a45=(a4*a57);
  a58=(a57*a58);
  a53=(a40*a53);
  a58=(a58-a53);
  a53=(a58*a40);
  a45=(a45-a53);
  a31=(a31-a45);
  a31=(a31+a22);
  a3=(a3+a31);
  a31=3.3744292548097956e+00;
  a53=2.9071864999999991e-01;
  a47=4.5000000000000001e-01;
  a59=2.3829305383030365e-05;
  a60=6.4386032905349921e-01;
  a52=(a60*a52);
  a59=(a59+a52);
  a52=(a57*a59);
  a61=-5.9839328282946629e-02;
  a8=(a60*a8);
  a61=(a61+a8);
  a8=(a40*a61);
  a52=(a52-a8);
  a52=(a47+a52);
  a53=(a53-a52);
  a8=casadi_sq(a53);
  a62=4.5882509999999987e-02;
  a63=-3.0499999999999999e-02;
  a64=-2.5021201581183733e-02;
  a60=(a60*a33);
  a64=(a64+a60);
  a60=(a63+a64);
  a62=(a62-a60);
  a33=casadi_sq(a62);
  a8=(a8+a33);
  a8=(a31*a8);
  a3=(a3+a8);
  a8=7.2200045999999996e-01;
  a8=(a8+a22);
  a33=-1.0863999999999998e-04;
  a65=(a54*a55);
  a65=(a65-a56);
  a66=(a65*a59);
  a56=(a54*a56);
  a55=(a55+a56);
  a56=(a55*a61);
  a66=(a66+a56);
  a33=(a33-a66);
  a56=casadi_sq(a33);
  a67=casadi_sq(a53);
  a56=(a56+a67);
  a56=(a31*a56);
  a8=(a8+a56);
  a3=(a3-a8);
  a3=(a2*a3);
  a1=cos(a1);
  a56=-3.2714000000000002e-04;
  a4=(a4*a65);
  a58=(a58*a55);
  a4=(a4+a58);
  a56=(a56+a4);
  a4=(a31*a33);
  a4=(a4*a53);
  a56=(a56-a4);
  a4=(a1*a56);
  a58=4.8099999999999997e-06;
  a67=-1.2860000000000001e-05;
  a68=(a37*a51);
  a69=(a16*a50);
  a68=(a68+a69);
  a69=(a44*a36);
  a70=(a43*a49);
  a69=(a69-a70);
  a68=(a68-a69);
  a67=(a67+a68);
  a5=(a13*a5);
  a5=(a5*a25);
  a67=(a67-a5);
  a5=(a34*a67);
  a68=(a5*a65);
  a69=3.3557089999999998e-02;
  a37=(a37*a43);
  a16=(a16*a44);
  a37=(a37+a16);
  a16=(a50*a36);
  a70=(a51*a49);
  a16=(a16-a70);
  a37=(a37+a16);
  a69=(a69+a37);
  a13=(a13*a46);
  a13=(a13*a25);
  a69=(a69-a13);
  a13=(a69+a69);
  a25=(a13*a55);
  a68=(a68+a25);
  a25=(a57*a69);
  a46=(a40*a67);
  a25=(a25+a46);
  a68=(a68+a25);
  a58=(a58+a68);
  a68=(a31*a33);
  a68=(a68*a62);
  a58=(a58-a68);
  a34=(a34*a58);
  a34=(a9*a34);
  a4=(a4+a34);
  a3=(a3+a4);
  a3=(a3*a2);
  a56=(a2*a56);
  a4=3.8504439999999973e-02;
  a45=(a45+a22);
  a4=(a4+a45);
  a33=casadi_sq(a33);
  a45=casadi_sq(a62);
  a33=(a33+a45);
  a33=(a31*a33);
  a4=(a4+a33);
  a4=(a4-a8);
  a4=(a1*a4);
  a33=5.3145310000000001e-02;
  a5=(a5*a57);
  a13=(a13*a40);
  a5=(a5-a13);
  a13=(a55*a67);
  a45=(a65*a69);
  a13=(a13-a45);
  a5=(a5+a13);
  a33=(a33+a5);
  a31=(a31*a53);
  a31=(a31*a62);
  a33=(a33-a31);
  a31=(a33+a33);
  a31=(a9*a31);
  a4=(a4+a31);
  a56=(a56+a4);
  a56=(a56*a1);
  a3=(a3+a56);
  a3=(a3+a8);
  a0=(a0+a3);
  a3=6.2226475454353691e+00;
  a56=-2.7386000000000001e-04;
  a4=-4.8677995699055936e-05;
  a31=5.5193302927967647e-01;
  a66=(a31*a66);
  a4=(a4+a66);
  a66=(a1*a4);
  a62=1.3026142483740194e-01;
  a52=(a31*a52);
  a62=(a62+a52);
  a52=(a2*a62);
  a66=(a66-a52);
  a56=(a56-a66);
  a56=casadi_sq(a56);
  a52=-4.3487669999999999e-02;
  a53=-1.0900000000000000e-01;
  a5=(a9*a2);
  a5=(a5*a4);
  a13=(a9*a1);
  a13=(a13*a62);
  a45=2.0558437264744947e-02;
  a31=(a31*a60);
  a45=(a45+a31);
  a13=(a13-a45);
  a5=(a5+a13);
  a5=(a53+a5);
  a52=(a52-a5);
  a52=casadi_sq(a52);
  a56=(a56+a52);
  a3=(a3*a56);
  a0=(a0+a3);
  a3=2.5084479750000000e+01;
  a56=-1.2489147494861637e-04;
  a52=5.4395868345645082e-01;
  a66=(a52*a66);
  a56=(a56+a66);
  a56=casadi_sq(a56);
  a66=-1.9832174280211407e-02;
  a52=(a52*a5);
  a66=(a66+a52);
  a66=casadi_sq(a66);
  a56=(a56+a66);
  a3=(a3*a56);
  a0=(a0+a3);
  if (res[0]!=0) res[0][0]=a0;
  a0=1.3644920580000001e+01;
  a3=(a0*a4);
  a3=(a3*a45);
  a58=(a58-a3);
  a58=(a2*a58);
  a3=(a0*a62);
  a3=(a3*a45);
  a33=(a33-a3);
  a33=(a1*a33);
  a3=casadi_sq(a4);
  a45=casadi_sq(a62);
  a3=(a3+a45);
  a3=(a0*a3);
  a8=(a8+a3);
  a3=(a9*a8);
  a33=(a33+a3);
  a58=(a58+a33);
  a33=-1.3644920580000001e+01;
  a33=(a33*a62);
  a33=(a1*a33);
  a0=(a0*a4);
  a0=(a2*a0);
  a33=(a33-a0);
  a33=(a53*a33);
  a58=(a58-a33);
  if (res[0]!=0) res[0][1]=a58;
  a33=7.5310823500000001e+00;
  a0=(a33*a59);
  a0=(a0*a64);
  a67=(a67-a0);
  a0=(a65*a67);
  a4=(a33*a61);
  a4=(a4*a64);
  a69=(a69-a4);
  a4=(a55*a69);
  a0=(a0+a4);
  a4=-7.5310823500000001e+00;
  a4=(a4*a61);
  a64=(a57*a4);
  a62=(a33*a59);
  a3=(a40*a62);
  a64=(a64-a3);
  a3=(a63*a64);
  a0=(a0-a3);
  a0=(a2*a0);
  a67=(a57*a67);
  a69=(a40*a69);
  a67=(a67-a69);
  a4=(a65*a4);
  a62=(a55*a62);
  a4=(a4+a62);
  a62=(a63*a4);
  a67=(a67+a62);
  a67=(a1*a67);
  a59=casadi_sq(a59);
  a61=casadi_sq(a61);
  a59=(a59+a61);
  a33=(a33*a59);
  a22=(a22+a33);
  a33=(a47*a4);
  a33=(a22-a33);
  a59=(a9*a33);
  a67=(a67+a59);
  a0=(a0+a67);
  a4=(a1*a4);
  a64=(a2*a64);
  a4=(a4-a64);
  a4=(a53*a4);
  a0=(a0-a4);
  if (res[0]!=0) res[0][2]=a0;
  a4=4.8489651600000006e+00;
  a64=(a4*a48);
  a64=(a64*a6);
  a36=(a36-a64);
  a64=(a51*a36);
  a67=(a4*a28);
  a67=(a67*a6);
  a49=(a49-a67);
  a67=(a50*a49);
  a6=casadi_sq(a48);
  a59=casadi_sq(a28);
  a6=(a6+a59);
  a6=(a4*a6);
  a23=(a23+a6);
  a6=(a54*a23);
  a67=(a67+a6);
  a64=(a64+a67);
  a67=-4.8489651600000006e+00;
  a67=(a67*a28);
  a28=(a41*a67);
  a4=(a4*a48);
  a48=(a42*a4);
  a28=(a28+a48);
  a48=(a39*a28);
  a6=(a43*a67);
  a59=(a44*a4);
  a6=(a6+a59);
  a59=(a17*a6);
  a48=(a48+a59);
  a64=(a64-a48);
  a48=(a65*a64);
  a59=(a43*a36);
  a61=(a44*a49);
  a61=(a61-a23);
  a59=(a59+a61);
  a67=(a51*a67);
  a4=(a50*a4);
  a67=(a67+a4);
  a4=(a17*a67);
  a59=(a59+a4);
  a4=(a55*a59);
  a48=(a48+a4);
  a28=(a47*a28);
  a4=(a57*a67);
  a61=(a40*a6);
  a4=(a4-a61);
  a61=(a63*a4);
  a28=(a28+a61);
  a48=(a48-a28);
  a48=(a2*a48);
  a64=(a57*a64);
  a59=(a40*a59);
  a64=(a64-a59);
  a59=(a65*a67);
  a6=(a55*a6);
  a59=(a59+a6);
  a6=(a63*a59);
  a64=(a64+a6);
  a64=(a1*a64);
  a6=(a9*a23);
  a49=(a42*a49);
  a6=(a6-a49);
  a36=(a41*a36);
  a6=(a6-a36);
  a67=(a39*a67);
  a6=(a6-a67);
  a67=(a47*a59);
  a67=(a6-a67);
  a36=(a9*a67);
  a64=(a64+a36);
  a48=(a48+a64);
  a59=(a1*a59);
  a4=(a2*a4);
  a59=(a59-a4);
  a59=(a53*a59);
  a48=(a48-a59);
  if (res[0]!=0) res[0][3]=a48;
  a59=2.7206566800000003e+00;
  a4=(a59*a19);
  a4=(a4*a20);
  a35=(a35-a4);
  a4=(a14*a35);
  a64=(a59*a18);
  a64=(a64*a20);
  a38=(a38-a64);
  a64=(a29*a38);
  a4=(a4-a64);
  a64=-2.7206566800000003e+00;
  a64=(a64*a18);
  a20=(a29*a64);
  a36=(a59*a19);
  a49=(a14*a36);
  a20=(a20+a49);
  a49=(a7*a20);
  a28=(a30*a64);
  a61=(a32*a36);
  a28=(a28+a61);
  a61=(a27*a28);
  a49=(a49-a61);
  a4=(a4+a49);
  a49=(a51*a4);
  a61=(a30*a35);
  a62=(a32*a38);
  a19=casadi_sq(a19);
  a18=casadi_sq(a18);
  a19=(a19+a18);
  a59=(a59*a19);
  a24=(a24+a59);
  a62=(a62-a24);
  a61=(a61+a62);
  a64=(a14*a64);
  a36=(a29*a36);
  a64=(a64-a36);
  a36=(a27*a64);
  a61=(a61+a36);
  a36=(a50*a61);
  a35=(a29*a35);
  a38=(a14*a38);
  a62=(a9*a24);
  a38=(a38+a62);
  a35=(a35+a38);
  a38=(a7*a64);
  a35=(a35-a38);
  a38=(a54*a35);
  a36=(a36+a38);
  a49=(a49+a36);
  a36=(a9*a20);
  a38=(a42*a28);
  a36=(a36-a38);
  a38=(a41*a64);
  a36=(a36-a38);
  a38=(a39*a36);
  a62=(a43*a64);
  a59=(a44*a28);
  a59=(a59-a20);
  a62=(a62+a59);
  a59=(a17*a62);
  a38=(a38-a59);
  a49=(a49+a38);
  a38=(a65*a49);
  a59=(a43*a4);
  a19=(a44*a61);
  a19=(a19-a35);
  a59=(a59+a19);
  a64=(a51*a64);
  a28=(a50*a28);
  a20=(a54*a20);
  a28=(a28+a20);
  a64=(a64+a28);
  a28=(a17*a64);
  a59=(a59+a28);
  a28=(a55*a59);
  a38=(a38+a28);
  a36=(a47*a36);
  a28=(a57*a64);
  a20=(a40*a62);
  a28=(a28-a20);
  a20=(a63*a28);
  a36=(a36-a20);
  a38=(a38+a36);
  a38=(a2*a38);
  a49=(a57*a49);
  a59=(a40*a59);
  a49=(a49-a59);
  a59=(a65*a64);
  a62=(a55*a62);
  a59=(a59+a62);
  a62=(a63*a59);
  a49=(a49+a62);
  a49=(a1*a49);
  a62=(a9*a35);
  a61=(a42*a61);
  a62=(a62-a61);
  a4=(a41*a4);
  a62=(a62-a4);
  a64=(a39*a64);
  a62=(a62-a64);
  a64=(a47*a59);
  a64=(a62-a64);
  a4=(a9*a64);
  a49=(a49+a4);
  a38=(a38+a49);
  a59=(a1*a59);
  a28=(a2*a28);
  a59=(a59-a28);
  a59=(a53*a59);
  a38=(a38-a59);
  if (res[0]!=0) res[0][4]=a38;
  a59=2.8351770287710000e-04;
  a28=(a59*a10);
  a49=(a29*a28);
  a12=(a59*a12);
  a4=(a14*a12);
  a59=(a59*a11);
  a61=(a9*a59);
  a4=(a4-a61);
  a49=(a49+a4);
  a4=(a7*a49);
  a61=(a30*a28);
  a36=(a32*a12);
  a36=(a36+a59);
  a61=(a61+a36);
  a36=(a27*a61);
  a4=(a4-a36);
  a36=2.1367835823883879e-06;
  a11=(a36*a11);
  a59=(a21*a59);
  a20=(a26*a12);
  a59=(a59+a20);
  a11=(a11+a59);
  a59=(a14*a11);
  a15=(a36*a15);
  a20=5.1295271799273417e-04;
  a15=(a15+a20);
  a26=(a26*a28);
  a15=(a15+a26);
  a26=(a29*a15);
  a59=(a59+a26);
  a4=(a4-a59);
  a59=(a51*a4);
  a32=(a32*a15);
  a26=-1.0520839253586279e-13;
  a36=(a36*a10);
  a26=(a26-a36);
  a21=(a21*a28);
  a26=(a26-a21);
  a32=(a32-a26);
  a30=(a30*a11);
  a32=(a32-a30);
  a28=(a14*a28);
  a12=(a29*a12);
  a28=(a28-a12);
  a27=(a27*a28);
  a32=(a32+a27);
  a27=(a50*a32);
  a14=(a14*a15);
  a15=(a9*a26);
  a14=(a14+a15);
  a29=(a29*a11);
  a14=(a14-a29);
  a7=(a7*a28);
  a14=(a14-a7);
  a7=(a54*a14);
  a27=(a27+a7);
  a59=(a59+a27);
  a27=(a9*a49);
  a7=(a42*a61);
  a27=(a27-a7);
  a7=(a41*a28);
  a27=(a27-a7);
  a7=(a39*a27);
  a29=(a43*a28);
  a11=(a44*a61);
  a11=(a11-a49);
  a29=(a29+a11);
  a11=(a17*a29);
  a7=(a7-a11);
  a59=(a59+a7);
  a7=(a65*a59);
  a43=(a43*a4);
  a44=(a44*a32);
  a44=(a44-a14);
  a43=(a43+a44);
  a51=(a51*a28);
  a50=(a50*a61);
  a54=(a54*a49);
  a50=(a50+a54);
  a51=(a51+a50);
  a17=(a17*a51);
  a43=(a43+a17);
  a17=(a55*a43);
  a7=(a7+a17);
  a27=(a47*a27);
  a17=(a57*a51);
  a50=(a40*a29);
  a17=(a17-a50);
  a50=(a63*a17);
  a27=(a27-a50);
  a7=(a7+a27);
  a7=(a2*a7);
  a57=(a57*a59);
  a40=(a40*a43);
  a57=(a57-a40);
  a65=(a65*a51);
  a55=(a55*a29);
  a65=(a65+a55);
  a63=(a63*a65);
  a57=(a57+a63);
  a57=(a1*a57);
  a63=(a9*a14);
  a42=(a42*a32);
  a63=(a63-a42);
  a41=(a41*a4);
  a63=(a63-a41);
  a39=(a39*a51);
  a63=(a63-a39);
  a47=(a47*a65);
  a47=(a63-a47);
  a9=(a9*a47);
  a57=(a57+a9);
  a7=(a7+a57);
  a1=(a1*a65);
  a2=(a2*a17);
  a1=(a1-a2);
  a53=(a53*a1);
  a7=(a7-a53);
  if (res[0]!=0) res[0][5]=a7;
  if (res[0]!=0) res[0][6]=a58;
  if (res[0]!=0) res[0][7]=a8;
  if (res[0]!=0) res[0][8]=a33;
  if (res[0]!=0) res[0][9]=a67;
  if (res[0]!=0) res[0][10]=a64;
  if (res[0]!=0) res[0][11]=a47;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a33;
  if (res[0]!=0) res[0][14]=a22;
  if (res[0]!=0) res[0][15]=a6;
  if (res[0]!=0) res[0][16]=a62;
  if (res[0]!=0) res[0][17]=a63;
  if (res[0]!=0) res[0][18]=a48;
  if (res[0]!=0) res[0][19]=a67;
  if (res[0]!=0) res[0][20]=a6;
  if (res[0]!=0) res[0][21]=a23;
  if (res[0]!=0) res[0][22]=a35;
  if (res[0]!=0) res[0][23]=a14;
  if (res[0]!=0) res[0][24]=a38;
  if (res[0]!=0) res[0][25]=a64;
  if (res[0]!=0) res[0][26]=a62;
  if (res[0]!=0) res[0][27]=a35;
  if (res[0]!=0) res[0][28]=a24;
  if (res[0]!=0) res[0][29]=a26;
  if (res[0]!=0) res[0][30]=a7;
  if (res[0]!=0) res[0][31]=a47;
  if (res[0]!=0) res[0][32]=a63;
  if (res[0]!=0) res[0][33]=a14;
  if (res[0]!=0) res[0][34]=a26;
  if (res[0]!=0) res[0][35]=a20;
  return 0;
}

CASADI_SYMBOL_EXPORT int M(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int M_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int M_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void M_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int M_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void M_release(int mem) {
}

CASADI_SYMBOL_EXPORT void M_incref(void) {
}

CASADI_SYMBOL_EXPORT void M_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int M_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int M_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real M_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* M_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* M_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* M_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* M_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int M_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int M_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
