/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) indy12_v2_J_com_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[31] = {3, 7, 0, 3, 6, 9, 12, 15, 18, 21, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};

/* jacobianCenterOfMass:(q[7])->(Jacobian CoM[3x7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a9;
  a0=2.3049413390000002e+01;
  a1=8.5569999999999996e-05;
  a2=arg[0]? arg[0][0] : 0;
  a3=sin(a2);
  a4=(a1*a3);
  a5=-4.3281540000000000e-02;
  a2=cos(a2);
  a6=(a5*a2);
  a4=(a4+a6);
  a4=(a0*a4);
  a6=8.9693480700000006e+00;
  a7=-9.5824909999999999e-02;
  a8=(a7*a2);
  a9=8.8479459999999996e-02;
  a10=arg[0]? arg[0][1] : 0;
  a11=sin(a10);
  a12=(a3*a11);
  a13=(a9*a12);
  a8=(a8+a13);
  a13=-1.3600000000000001e-01;
  a14=(a13*a2);
  a8=(a8+a14);
  a8=(a6*a8);
  a15=8.4564522100000001e+00;
  a16=1.7700000000000000e-06;
  a10=cos(a10);
  a17=(a3*a10);
  a18=arg[0]? arg[0][2] : 0;
  a19=cos(a18);
  a20=(a17*a19);
  a18=sin(a18);
  a21=(a2*a18);
  a20=(a20+a21);
  a21=(a16*a20);
  a22=1.8148879999999999e-02;
  a23=(a2*a19);
  a17=(a17*a18);
  a23=(a23-a17);
  a17=(a22*a23);
  a24=2.1567452000000001e-01;
  a25=(a24*a12);
  a17=(a17+a25);
  a21=(a21+a17);
  a17=-1.1100000000000000e-01;
  a25=(a17*a2);
  a26=2.9299999999999998e-01;
  a27=(a26*a12);
  a25=(a25+a27);
  a25=(a14+a25);
  a21=(a21+a25);
  a21=(a15*a21);
  a27=5.1077934300000001e+00;
  a28=-4.8300000000000003e-06;
  a29=arg[0]? arg[0][3] : 0;
  a30=cos(a29);
  a31=(a20*a30);
  a29=sin(a29);
  a32=(a12*a29);
  a31=(a31-a32);
  a32=(a28*a31);
  a33=8.9583410000000002e-02;
  a34=(a33*a23);
  a35=6.6920259999999995e-02;
  a20=(a20*a29);
  a36=(a12*a30);
  a20=(a20+a36);
  a36=(a35*a20);
  a34=(a34+a36);
  a32=(a32+a34);
  a34=1.2950000000000000e-01;
  a36=(a34*a23);
  a37=3.5749999999999998e-01;
  a38=(a37*a12);
  a36=(a36+a38);
  a36=(a25+a36);
  a32=(a32+a36);
  a32=(a27*a32);
  a38=5.0547620799999997e+00;
  a39=1.5551000000000001e-04;
  a40=arg[0]? arg[0][4] : 0;
  a41=cos(a40);
  a42=(a31*a41);
  a40=sin(a40);
  a43=(a23*a40);
  a42=(a42+a43);
  a43=(a39*a42);
  a44=4.6691280000000002e-02;
  a45=(a23*a41);
  a31=(a31*a40);
  a45=(a45-a31);
  a31=(a44*a45);
  a46=2.2088569999999999e-01;
  a47=(a46*a20);
  a31=(a31+a47);
  a43=(a43+a31);
  a31=1.0650000000000000e-01;
  a47=(a31*a23);
  a48=2.0899999999999999e-01;
  a49=(a48*a20);
  a47=(a47+a49);
  a47=(a36+a47);
  a43=(a43+a47);
  a43=(a38*a43);
  a49=3.5417891500000001e+00;
  a50=-1.4038000000000001e-04;
  a51=arg[0]? arg[0][5] : 0;
  a52=cos(a51);
  a53=(a42*a52);
  a51=sin(a51);
  a54=(a20*a51);
  a53=(a53-a54);
  a54=(a50*a53);
  a55=1.4038000000000001e-04;
  a56=(a55*a45);
  a57=2.0349220000000001e-02;
  a42=(a42*a51);
  a58=(a20*a52);
  a42=(a42+a58);
  a58=(a57*a42);
  a56=(a56+a58);
  a54=(a54+a56);
  a56=1.2900000000000000e-01;
  a58=(a56*a45);
  a59=3.6249999999999999e-01;
  a60=(a59*a20);
  a58=(a58+a60);
  a58=(a47+a58);
  a54=(a54+a58);
  a54=(a49*a54);
  a60=3.6068488300000006e+00;
  a61=3.0519246880801490e-04;
  a62=arg[0]? arg[0][6] : 0;
  a63=cos(a62);
  a64=(a53*a63);
  a62=sin(a62);
  a65=(a45*a62);
  a64=(a64+a65);
  a64=(a61*a64);
  a65=-2.3072692489221956e-04;
  a66=(a45*a63);
  a53=(a53*a62);
  a66=(a66-a53);
  a66=(a65*a66);
  a53=1.7228895418171272e-01;
  a67=(a53*a42);
  a66=(a66+a67);
  a64=(a64+a66);
  a66=7.9500000000000001e-02;
  a67=(a66*a45);
  a68=7.4550000000000005e-02;
  a69=(a68*a42);
  a67=(a67+a69);
  a67=(a58+a67);
  a64=(a64+a67);
  a64=(a60*a64);
  a54=(a54+a64);
  a43=(a43+a54);
  a32=(a32+a43);
  a21=(a21+a32);
  a8=(a8+a21);
  a4=(a4+a8);
  a69=5.7786407160000010e+01;
  a4=(a4/a69);
  a4=(-a4);
  if (res[0]!=0) res[0][0]=a4;
  a1=(a1*a2);
  a5=(a5*a3);
  a1=(a1-a5);
  a0=(a0*a1);
  a1=(a2*a11);
  a5=(a9*a1);
  a7=(a7*a3);
  a5=(a5-a7);
  a13=(a13*a3);
  a5=(a5-a13);
  a5=(a6*a5);
  a7=(a2*a10);
  a4=(a7*a19);
  a70=(a3*a18);
  a4=(a4-a70);
  a70=(a16*a4);
  a71=(a24*a1);
  a7=(a7*a18);
  a72=(a3*a19);
  a7=(a7+a72);
  a72=(a22*a7);
  a71=(a71-a72);
  a70=(a70+a71);
  a71=(a26*a1);
  a17=(a17*a3);
  a71=(a71-a17);
  a71=(a71-a13);
  a70=(a70+a71);
  a70=(a15*a70);
  a17=(a4*a30);
  a72=(a1*a29);
  a17=(a17-a72);
  a72=(a28*a17);
  a4=(a4*a29);
  a73=(a1*a30);
  a4=(a4+a73);
  a73=(a35*a4);
  a74=(a33*a7);
  a73=(a73-a74);
  a72=(a72+a73);
  a73=(a37*a1);
  a74=(a34*a7);
  a73=(a73-a74);
  a73=(a71+a73);
  a72=(a72+a73);
  a72=(a27*a72);
  a74=(a17*a41);
  a75=(a7*a40);
  a74=(a74-a75);
  a75=(a39*a74);
  a76=(a46*a4);
  a17=(a17*a40);
  a77=(a7*a41);
  a17=(a17+a77);
  a77=(a44*a17);
  a76=(a76-a77);
  a75=(a75+a76);
  a76=(a48*a4);
  a77=(a31*a7);
  a76=(a76-a77);
  a76=(a73+a76);
  a75=(a75+a76);
  a75=(a38*a75);
  a77=(a74*a52);
  a78=(a4*a51);
  a77=(a77-a78);
  a78=(a50*a77);
  a74=(a74*a51);
  a79=(a4*a52);
  a74=(a74+a79);
  a79=(a57*a74);
  a80=(a55*a17);
  a79=(a79-a80);
  a78=(a78+a79);
  a79=(a59*a4);
  a80=(a56*a17);
  a79=(a79-a80);
  a79=(a76+a79);
  a78=(a78+a79);
  a78=(a49*a78);
  a80=(a77*a63);
  a81=(a17*a62);
  a80=(a80-a81);
  a80=(a61*a80);
  a81=(a53*a74);
  a77=(a77*a62);
  a82=(a17*a63);
  a77=(a77+a82);
  a77=(a65*a77);
  a81=(a81-a77);
  a80=(a80+a81);
  a81=(a68*a74);
  a77=(a66*a17);
  a81=(a81-a77);
  a81=(a79+a81);
  a80=(a80+a81);
  a80=(a60*a80);
  a78=(a78+a80);
  a75=(a75+a78);
  a72=(a72+a75);
  a70=(a70+a72);
  a5=(a5+a70);
  a0=(a0+a5);
  a0=(a0/a69);
  if (res[0]!=0) res[0][1]=a0;
  a0=0.;
  if (res[0]!=0) res[0][2]=a0;
  a9=(a9*a10);
  a0=3.5000000000000003e-01;
  a9=(a9+a0);
  a6=(a6*a9);
  a18=(a11*a18);
  a22=(a22*a18);
  a24=(a24*a10);
  a22=(a22+a24);
  a11=(a11*a19);
  a16=(a16*a11);
  a22=(a22-a16);
  a26=(a26*a10);
  a26=(a0+a26);
  a22=(a22+a26);
  a15=(a15*a22);
  a33=(a33*a18);
  a22=(a10*a30);
  a16=(a11*a29);
  a22=(a22-a16);
  a35=(a35*a22);
  a33=(a33+a35);
  a11=(a11*a30);
  a29=(a10*a29);
  a11=(a11+a29);
  a28=(a28*a11);
  a33=(a33-a28);
  a34=(a34*a18);
  a37=(a37*a10);
  a34=(a34+a37);
  a34=(a26+a34);
  a33=(a33+a34);
  a27=(a27*a33);
  a33=(a18*a40);
  a37=(a11*a41);
  a33=(a33-a37);
  a39=(a39*a33);
  a11=(a11*a40);
  a41=(a18*a41);
  a11=(a11+a41);
  a44=(a44*a11);
  a46=(a46*a22);
  a44=(a44+a46);
  a39=(a39+a44);
  a31=(a31*a18);
  a48=(a48*a22);
  a31=(a31+a48);
  a31=(a34+a31);
  a39=(a39+a31);
  a38=(a38*a39);
  a39=(a33*a52);
  a48=(a22*a51);
  a39=(a39-a48);
  a50=(a50*a39);
  a55=(a55*a11);
  a33=(a33*a51);
  a52=(a22*a52);
  a33=(a33+a52);
  a57=(a57*a33);
  a55=(a55+a57);
  a50=(a50+a55);
  a56=(a56*a11);
  a59=(a59*a22);
  a56=(a56+a59);
  a56=(a31+a56);
  a50=(a50+a56);
  a49=(a49*a50);
  a50=(a39*a63);
  a59=(a11*a62);
  a50=(a50+a59);
  a61=(a61*a50);
  a63=(a11*a63);
  a39=(a39*a62);
  a63=(a63-a39);
  a65=(a65*a63);
  a53=(a53*a33);
  a65=(a65+a53);
  a61=(a61+a65);
  a66=(a66*a11);
  a68=(a68*a33);
  a66=(a66+a68);
  a66=(a56+a66);
  a61=(a61+a66);
  a61=(a60*a61);
  a49=(a49+a61);
  a38=(a38+a49);
  a27=(a27+a38);
  a15=(a15+a27);
  a6=(a6+a15);
  a68=(a6*a2);
  a65=3.4736993770000005e+01;
  a53=(a0*a2);
  a53=(a65*a53);
  a68=(a68-a53);
  a68=(a68/a69);
  if (res[0]!=0) res[0][3]=a68;
  a6=(a6*a3);
  a0=(a0*a3);
  a0=(a65*a0);
  a6=(a6-a0);
  a6=(a6/a69);
  if (res[0]!=0) res[0][4]=a6;
  a14=(a14*a3);
  a13=(a13*a2);
  a14=(a14-a13);
  a65=(a65*a14);
  a5=(a5*a2);
  a8=(a8*a3);
  a5=(a5+a8);
  a65=(a65-a5);
  a65=(a65/a69);
  if (res[0]!=0) res[0][5]=a65;
  a65=2.5767645700000003e+01;
  a5=(a25*a10);
  a8=(a26*a12);
  a5=(a5-a8);
  a5=(a65*a5);
  a8=(a21*a10);
  a3=(a15*a12);
  a8=(a8-a3);
  a5=(a5-a8);
  a5=(a5/a69);
  if (res[0]!=0) res[0][6]=a5;
  a26=(a26*a1);
  a5=(a71*a10);
  a26=(a26-a5);
  a26=(a65*a26);
  a15=(a15*a1);
  a10=(a70*a10);
  a15=(a15-a10);
  a26=(a26-a15);
  a26=(a26/a69);
  if (res[0]!=0) res[0][7]=a26;
  a71=(a71*a12);
  a25=(a25*a1);
  a71=(a71-a25);
  a65=(a65*a71);
  a70=(a70*a12);
  a21=(a21*a1);
  a70=(a70-a21);
  a65=(a65-a70);
  a65=(a65/a69);
  if (res[0]!=0) res[0][8]=a65;
  a65=1.7311193490000001e+01;
  a70=(a36*a18);
  a21=(a34*a23);
  a70=(a70-a21);
  a70=(a65*a70);
  a21=(a32*a18);
  a1=(a27*a23);
  a21=(a21-a1);
  a70=(a70-a21);
  a70=(a70/a69);
  if (res[0]!=0) res[0][9]=a70;
  a27=(a27*a7);
  a70=(a72*a18);
  a27=(a27+a70);
  a34=(a34*a7);
  a18=(a73*a18);
  a34=(a34+a18);
  a34=(a65*a34);
  a27=(a27-a34);
  a27=(a27/a69);
  if (res[0]!=0) res[0][10]=a27;
  a73=(a73*a23);
  a36=(a36*a7);
  a73=(a73+a36);
  a65=(a65*a73);
  a72=(a72*a23);
  a32=(a32*a7);
  a72=(a72+a32);
  a65=(a65-a72);
  a65=(a65/a69);
  if (res[0]!=0) res[0][11]=a65;
  a65=1.2203400060000000e+01;
  a72=(a47*a22);
  a32=(a31*a20);
  a72=(a72-a32);
  a72=(a65*a72);
  a32=(a43*a22);
  a7=(a38*a20);
  a32=(a32-a7);
  a72=(a72-a32);
  a72=(a72/a69);
  if (res[0]!=0) res[0][12]=a72;
  a31=(a31*a4);
  a72=(a76*a22);
  a31=(a31-a72);
  a31=(a65*a31);
  a38=(a38*a4);
  a22=(a75*a22);
  a38=(a38-a22);
  a31=(a31-a38);
  a31=(a31/a69);
  if (res[0]!=0) res[0][13]=a31;
  a76=(a76*a20);
  a47=(a47*a4);
  a76=(a76-a47);
  a65=(a65*a76);
  a75=(a75*a20);
  a43=(a43*a4);
  a75=(a75-a43);
  a65=(a65-a75);
  a65=(a65/a69);
  if (res[0]!=0) res[0][14]=a65;
  a65=7.1486379800000002e+00;
  a75=(a58*a11);
  a43=(a56*a45);
  a75=(a75-a43);
  a75=(a65*a75);
  a43=(a54*a11);
  a4=(a49*a45);
  a43=(a43-a4);
  a75=(a75-a43);
  a75=(a75/a69);
  if (res[0]!=0) res[0][15]=a75;
  a49=(a49*a17);
  a75=(a78*a11);
  a49=(a49+a75);
  a56=(a56*a17);
  a11=(a79*a11);
  a56=(a56+a11);
  a56=(a65*a56);
  a49=(a49-a56);
  a49=(a49/a69);
  if (res[0]!=0) res[0][16]=a49;
  a79=(a79*a45);
  a58=(a58*a17);
  a79=(a79+a58);
  a65=(a65*a79);
  a78=(a78*a45);
  a54=(a54*a17);
  a78=(a78+a54);
  a65=(a65-a78);
  a65=(a65/a69);
  if (res[0]!=0) res[0][17]=a65;
  a65=(a67*a33);
  a78=(a66*a42);
  a65=(a65-a78);
  a65=(a60*a65);
  a78=(a64*a33);
  a54=(a61*a42);
  a78=(a78-a54);
  a65=(a65-a78);
  a65=(a65/a69);
  if (res[0]!=0) res[0][18]=a65;
  a66=(a66*a74);
  a65=(a81*a33);
  a66=(a66-a65);
  a66=(a60*a66);
  a61=(a61*a74);
  a33=(a80*a33);
  a61=(a61-a33);
  a66=(a66-a61);
  a66=(a66/a69);
  if (res[0]!=0) res[0][19]=a66;
  a81=(a81*a42);
  a67=(a67*a74);
  a81=(a81-a67);
  a60=(a60*a81);
  a80=(a80*a42);
  a64=(a64*a74);
  a80=(a80-a64);
  a60=(a60-a80);
  a60=(a60/a69);
  if (res[0]!=0) res[0][20]=a60;
  return 0;
}

CASADI_SYMBOL_EXPORT int jacobianCenterOfMass(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int jacobianCenterOfMass_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int jacobianCenterOfMass_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void jacobianCenterOfMass_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int jacobianCenterOfMass_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void jacobianCenterOfMass_release(int mem) {
}

CASADI_SYMBOL_EXPORT void jacobianCenterOfMass_incref(void) {
}

CASADI_SYMBOL_EXPORT void jacobianCenterOfMass_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int jacobianCenterOfMass_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int jacobianCenterOfMass_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real jacobianCenterOfMass_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* jacobianCenterOfMass_name_in(casadi_int i) {
  switch (i) {
    case 0: return "q";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* jacobianCenterOfMass_name_out(casadi_int i) {
  switch (i) {
    case 0: return "Jacobian CoM";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* jacobianCenterOfMass_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* jacobianCenterOfMass_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int jacobianCenterOfMass_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int jacobianCenterOfMass_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
