/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) turtlebot3_burger_J_id_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[39] = {3, 9, 0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};

/* rnea_jacobian:(q[3],v[3],a[3])->(J_tau[3x9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a3, a4, a5, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  a1=1.0017349200000001e+00;
  a2=arg[2]? arg[2][1] : 0;
  a3=(a1*a2);
  a4=arg[0]? arg[0][2] : 0;
  a5=sin(a4);
  a6=arg[1]? arg[1][2] : 0;
  a4=cos(a4);
  a7=arg[1]? arg[1][1] : 0;
  a8=(a4*a7);
  a9=arg[1]? arg[1][0] : 0;
  a10=(a5*a9);
  a8=(a8-a10);
  a10=(a6*a8);
  a11=arg[2]? arg[2][0] : 0;
  a12=(a4*a11);
  a13=(a5*a2);
  a12=(a12+a13);
  a10=(a10+a12);
  a12=(a5*a10);
  a2=(a4*a2);
  a13=(a5*a11);
  a2=(a2-a13);
  a13=(a4*a9);
  a14=(a5*a7);
  a13=(a13+a14);
  a14=(a6*a13);
  a2=(a2-a14);
  a14=(a4*a2);
  a12=(a12+a14);
  a14=arg[0]? arg[0][0] : 0;
  a15=arg[2]? arg[2][2] : 0;
  a16=(a14*a15);
  a12=(a12-a16);
  a16=-4.0460124920073653e-03;
  a17=(a16*a4);
  a18=-4.3368086899420177e-19;
  a19=(a18*a5);
  a17=(a17-a19);
  a19=(a14+a17);
  a20=(a19*a15);
  a12=(a12+a20);
  a12=(a1*a12);
  a20=(a4*a13);
  a21=(a5*a8);
  a20=(a20-a21);
  a21=arg[0]? arg[0][1] : 0;
  a22=(a21*a6);
  a22=(a20+a22);
  a16=(a16*a5);
  a18=(a18*a4);
  a16=(a16+a18);
  a18=(a21+a16);
  a23=(a18*a6);
  a23=(a22-a23);
  a23=(a1*a23);
  a24=(a6*a23);
  a12=(a12+a24);
  a12=(a3-a12);
  if (res[0]!=0) res[0][6]=a12;
  a10=(a4*a10);
  a2=(a5*a2);
  a10=(a10-a2);
  a2=(a21*a15);
  a10=(a10+a2);
  a15=(a18*a15);
  a10=(a10-a15);
  a10=(a1*a10);
  a5=(a5*a13);
  a4=(a4*a8);
  a5=(a5+a4);
  a4=(a14*a6);
  a4=(a5-a4);
  a8=(a19*a6);
  a8=(a4+a8);
  a8=(a1*a8);
  a13=(a6*a8);
  a10=(a10-a13);
  a11=(a1*a11);
  a10=(a10-a11);
  if (res[0]!=0) res[0][7]=a10;
  a10=(a21*a3);
  a13=(a14*a11);
  a10=(a10+a13);
  a4=(a1*a4);
  a6=(a1*a6);
  a13=(a19*a6);
  a13=(a4+a13);
  a15=(a8-a13);
  a2=(a15*a7);
  a22=(a1*a22);
  a6=(a18*a6);
  a6=(a22-a6);
  a12=(a6-a23);
  a24=(a12*a9);
  a2=(a2-a24);
  a11=(a19*a11);
  a3=(a18*a3);
  a11=(a11+a3);
  a2=(a2-a11);
  a10=(a10+a2);
  if (res[0]!=0) res[0][8]=a10;
  if (res[0]!=0) res[0][9]=a0;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a15;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a12;
  a5=(a5+a7);
  a5=(a1*a5);
  a13=(a13+a8);
  a13=(a5-a13);
  if (res[0]!=0) res[0][15]=a13;
  a6=(a6+a23);
  a20=(a20+a9);
  a20=(a1*a20);
  a6=(a6-a20);
  if (res[0]!=0) res[0][16]=a6;
  a13=(a21*a13);
  a6=(a14*a6);
  a13=(a13-a6);
  a15=(a15*a21);
  a12=(a12*a14);
  a15=(a15-a12);
  a12=(a22*a19);
  a6=(a4*a18);
  a12=(a12+a6);
  a22=(a19*a22);
  a4=(a18*a4);
  a22=(a22+a4);
  a12=(a12+a22);
  a15=(a15+a12);
  a20=(a19*a20);
  a5=(a18*a5);
  a20=(a20+a5);
  a15=(a15-a20);
  a13=(a13+a15);
  if (res[0]!=0) res[0][17]=a13;
  a13=1.0017369199999999e+00;
  if (res[0]!=0) res[0][18]=a13;
  if (res[0]!=0) res[0][19]=a0;
  a16=(a1*a16);
  a13=(-a16);
  if (res[0]!=0) res[0][20]=a13;
  if (res[0]!=0) res[0][21]=a0;
  a0=1.0017359200000000e+00;
  if (res[0]!=0) res[0][22]=a0;
  a1=(a1*a17);
  if (res[0]!=0) res[0][23]=a1;
  if (res[0]!=0) res[0][24]=a13;
  if (res[0]!=0) res[0][25]=a1;
  a13=4.5287417760175004e-03;
  a19=(a19*a1);
  a18=(a18*a16);
  a19=(a19+a18);
  a13=(a13+a19);
  a21=(a21*a16);
  a14=(a14*a1);
  a21=(a21+a14);
  a13=(a13-a21);
  if (res[0]!=0) res[0][26]=a13;
  return 0;
}

CASADI_SYMBOL_EXPORT int rnea_jacobian(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rnea_jacobian_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rnea_jacobian_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rnea_jacobian_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rnea_jacobian_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rnea_jacobian_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rnea_jacobian_incref(void) {
}

CASADI_SYMBOL_EXPORT void rnea_jacobian_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rnea_jacobian_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int rnea_jacobian_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real rnea_jacobian_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rnea_jacobian_name_in(casadi_int i){
  switch (i) {
    case 0: return "q";
    case 1: return "v";
    case 2: return "a";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rnea_jacobian_name_out(casadi_int i){
  switch (i) {
    case 0: return "J_tau";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rnea_jacobian_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rnea_jacobian_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rnea_jacobian_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
