/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) KARM_EM_M_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[59] = {7, 7, 0, 7, 14, 21, 28, 35, 42, 49, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};

/* M:(i0[7])->(o0[7x7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a8, a9;
  a0=1.1149444000000000e-01;
  a1=5.0910599999999997e-03;
  a2=4.7084630000000002e-02;
  a3=3.8261839999999998e-02;
  a4=1.7192470001000000e-02;
  a5=4.3671723688989222e-01;
  a6=3.6990000000000003e-05;
  a7=1.1810000000000000e-05;
  a8=arg[0]? arg[0][6] : 0;
  a9=sin(a8);
  a10=(a7*a9);
  a6=(a6+a10);
  a11=casadi_sq(a6);
  a12=9.0373780000000001e-02;
  a13=8.7999999999999995e-02;
  a8=cos(a8);
  a7=(a7*a8);
  a7=(a13+a7);
  a12=(a12-a7);
  a14=casadi_sq(a12);
  a11=(a11+a14);
  a11=(a5*a11);
  a4=(a4+a11);
  a11=arg[0]? arg[0][5] : 0;
  a14=cos(a11);
  a15=2.;
  a16=1.6300000000000000e-05;
  a17=-2.3999999999999998e-07;
  a18=(a17*a9);
  a19=-4.7999999999999996e-07;
  a20=(a19*a9);
  a18=(a18-a20);
  a16=(a16+a18);
  a18=-1.4911258999999999e-01;
  a20=(a5*a6);
  a20=(a18*a20);
  a16=(a16-a20);
  a20=(a15*a16);
  a20=(a14*a20);
  a11=sin(a11);
  a21=1.0881374999999999e-01;
  a22=-6.9549999999999994e-04;
  a23=-3.4793999999999992e-04;
  a23=(a23*a9);
  a24=(a23*a9);
  a25=-3.4756000000000001e-04;
  a25=(a25*a8);
  a26=(a25*a8);
  a24=(a24+a26);
  a22=(a22-a24);
  a26=1.4176400010000000e-03;
  a22=(a22+a26);
  a21=(a21+a22);
  a22=casadi_sq(a12);
  a27=2.2234564496508097e-02;
  a22=(a22+a27);
  a22=(a5*a22);
  a21=(a21+a22);
  a21=(a21-a4);
  a22=(a11*a21);
  a20=(a20-a22);
  a22=(a20*a11);
  a28=(a4-a22);
  a3=(a3+a28);
  a28=3.5006502886302480e+00;
  a29=5.6610000000000002e-05;
  a30=3.4038114600315574e-05;
  a31=7.9802254654891241e-02;
  a10=(a31*a10);
  a30=(a30-a10);
  a10=(a14*a30);
  a32=2.8810510879430391e-02;
  a33=(a32*a11);
  a10=(a10+a33);
  a29=(a29-a10);
  a33=casadi_sq(a29);
  a34=3.4654329999999997e-02;
  a35=1.0400000000000000e-01;
  a36=8.3161748594314883e-02;
  a31=(a31*a7);
  a36=(a36+a31);
  a31=(a35+a36);
  a34=(a34-a31);
  a7=casadi_sq(a34);
  a33=(a33+a7);
  a33=(a28*a33);
  a3=(a3+a33);
  a33=(a1+a3);
  a7=1.0096299487207760e+00;
  a37=arg[0]? arg[0][4] : 0;
  a38=cos(a37);
  a39=3.3322522908643798e-05;
  a40=4.1136684492768416e-01;
  a10=(a40*a10);
  a39=(a39+a10);
  a10=(a38*a39);
  a37=sin(a37);
  a41=2.0398687604817205e-02;
  a31=(a40*a31);
  a41=(a41+a31);
  a31=(a37*a41);
  a10=(a10-a31);
  a31=casadi_sq(a10);
  a42=8.3413160000000000e-02;
  a43=(a37*a39);
  a44=(a38*a41);
  a43=(a43+a44);
  a43=(a13+a43);
  a42=(a42-a43);
  a44=casadi_sq(a42);
  a31=(a31+a44);
  a31=(a7*a31);
  a33=(a33+a31);
  a31=arg[0]? arg[0][3] : 0;
  a44=cos(a31);
  a45=-8.4100000000000008e-06;
  a20=(a20*a14);
  a20=(a20-a16);
  a45=(a45+a20);
  a20=(a28*a29);
  a16=2.0951316000000000e-01;
  a46=4.0600000000000003e-01;
  a47=(a32*a14);
  a48=(a11*a30);
  a47=(a47-a48);
  a47=(a46+a47);
  a16=(a16-a47);
  a20=(a20*a16);
  a45=(a45-a20);
  a20=(a15*a45);
  a48=(a20*a38);
  a49=5.7437820000000001e-02;
  a50=-7.6964000000000004e-04;
  a19=(a19*a8);
  a17=(a17*a8);
  a19=(a19-a17);
  a50=(a50+a19);
  a19=(a5*a12);
  a18=(a18*a19);
  a50=(a50-a18);
  a18=(a50+a50);
  a18=(a14*a18);
  a19=8.4159999999999994e-05;
  a23=(a23*a8);
  a25=(a25*a9);
  a23=(a23-a25);
  a19=(a19+a23);
  a23=(a5*a6);
  a23=(a23*a12);
  a19=(a19-a23);
  a23=(a11*a19);
  a18=(a18-a23);
  a23=(a14*a50);
  a18=(a18-a23);
  a49=(a49+a18);
  a18=(a28*a34);
  a18=(a18*a16);
  a49=(a49-a18);
  a18=(a49+a49);
  a23=(a18*a37);
  a48=(a48-a23);
  a23=(a38*a45);
  a12=(a37*a49);
  a23=(a23-a12);
  a48=(a48-a23);
  a23=(a7*a10);
  a12=2.2694599999999999e-02;
  a25=1.2900000000000000e-01;
  a17=1.2332639239997092e-01;
  a40=(a40*a47);
  a17=(a17+a40);
  a40=(a25+a17);
  a47=(a12-a40);
  a23=(a23*a47);
  a48=(a48+a23);
  a23=(a15*a48);
  a23=(a44*a23);
  a31=sin(a31);
  a51=6.3946799999999998e-03;
  a52=3.4047401999999999e-01;
  a21=(a21+a22);
  a21=(a21+a4);
  a52=(a52+a21);
  a21=casadi_sq(a34);
  a4=casadi_sq(a16);
  a21=(a21+a4);
  a21=(a28*a21);
  a52=(a52+a21);
  a52=(a52-a3);
  a21=3.2060603999999998e-01;
  a4=1.0731441999999999e-01;
  a24=(a24+a26);
  a4=(a4+a24);
  a6=casadi_sq(a6);
  a6=(a6+a27);
  a5=(a5*a6);
  a4=(a4+a5);
  a21=(a21+a4);
  a5=casadi_sq(a29);
  a16=casadi_sq(a16);
  a5=(a5+a16);
  a5=(a28*a5);
  a21=(a21+a5);
  a21=(a21-a3);
  a5=(a52+a21);
  a52=(a37*a52);
  a16=-1.5240000000000000e-05;
  a6=(a19*a14);
  a27=(a11*a50);
  a6=(a6+a27);
  a16=(a16+a6);
  a28=(a28*a29);
  a28=(a28*a34);
  a16=(a16-a28);
  a28=(a38*a16);
  a52=(a52+a28);
  a28=(a52*a37);
  a16=(a37*a16);
  a21=(a38*a21);
  a16=(a16+a21);
  a21=(a16*a38);
  a28=(a28+a21);
  a5=(a5-a28);
  a5=(a5+a3);
  a5=(a51+a5);
  a21=casadi_sq(a42);
  a34=casadi_sq(a47);
  a21=(a21+a34);
  a21=(a7*a21);
  a5=(a5+a21);
  a5=(a5-a33);
  a21=(a31*a5);
  a23=(a23-a21);
  a21=(a23*a31);
  a34=(a33-a21);
  a2=(a2+a34);
  a34=6.2491008775201111e+00;
  a29=4.6100000000000002e-05;
  a6=9.3016268991604223e-01;
  a27=(a6*a10);
  a24=(a44*a27);
  a26=1.5849298174313896e-03;
  a40=(a6*a40);
  a26=(a26+a40);
  a40=(a31*a26);
  a24=(a24+a40);
  a29=(a29-a24);
  a40=casadi_sq(a29);
  a22=2.8216930000000001e-02;
  a53=5.8253507200027891e-03;
  a6=(a6*a43);
  a53=(a53+a6);
  a6=(a35+a53);
  a22=(a22-a6);
  a43=casadi_sq(a22);
  a40=(a40+a43);
  a40=(a34*a40);
  a2=(a2+a40);
  a1=(a1+a2);
  a40=1.0419251962810741e+00;
  a43=-6.6000000000000003e-06;
  a54=arg[0]? arg[0][2] : 0;
  a55=cos(a54);
  a56=1.8535429545270590e-05;
  a57=5.9792994478805661e-01;
  a24=(a57*a24);
  a56=(a56+a24);
  a24=(a55*a56);
  a54=sin(a54);
  a58=1.1345182603011541e-02;
  a6=(a57*a6);
  a58=(a58+a6);
  a6=(a54*a58);
  a24=(a24-a6);
  a43=(a43-a24);
  a6=casadi_sq(a43);
  a59=-8.3413160000000000e-02;
  a60=-8.7999999999999995e-02;
  a61=(a54*a56);
  a62=(a55*a58);
  a61=(a61+a62);
  a61=(a60+a61);
  a59=(a59-a61);
  a62=casadi_sq(a59);
  a6=(a6+a62);
  a6=(a40*a6);
  a1=(a1+a6);
  a6=arg[0]? arg[0][1] : 0;
  a62=cos(a6);
  a63=-9.3969999999999996e-05;
  a23=(a23*a44);
  a23=(a23-a48);
  a63=(a63+a23);
  a23=(a34*a29);
  a48=4.0811987999999999e-01;
  a64=7.9800000000000004e-01;
  a65=(a44*a26);
  a66=(a31*a27);
  a65=(a65-a66);
  a65=(a64+a65);
  a48=(a48-a65);
  a23=(a23*a48);
  a63=(a63-a23);
  a23=(a15*a63);
  a66=(a23*a55);
  a67=1.1346658000000000e-01;
  a68=1.1198000000000000e-04;
  a20=(a20*a37);
  a18=(a18*a38);
  a20=(a20+a18);
  a18=(a38*a49);
  a69=(a37*a45);
  a18=(a18+a69);
  a20=(a20-a18);
  a68=(a68+a20);
  a20=(a7*a42);
  a20=(a20*a47);
  a68=(a68-a20);
  a20=(a68+a68);
  a20=(a44*a20);
  a52=(a52*a38);
  a16=(a16*a37);
  a52=(a52-a16);
  a16=(a7*a10);
  a16=(a16*a42);
  a52=(a52+a16);
  a16=(a31*a52);
  a20=(a20-a16);
  a16=(a44*a68);
  a20=(a20-a16);
  a67=(a67+a20);
  a20=(a34*a22);
  a20=(a20*a48);
  a67=(a67-a20);
  a20=(a67+a67);
  a16=(a20*a54);
  a66=(a66-a16);
  a16=(a55*a63);
  a42=(a54*a67);
  a16=(a16-a42);
  a66=(a66-a16);
  a16=(a40*a43);
  a42=1.6409278268469168e-01;
  a57=(a57*a65);
  a42=(a42+a57);
  a57=(a25+a42);
  a12=(a12-a57);
  a16=(a16*a12);
  a66=(a66-a16);
  a15=(a15*a66);
  a15=(a62*a15);
  a6=sin(a6);
  a66=1.2966242299999997e+00;
  a5=(a5+a21);
  a5=(a5+a33);
  a66=(a66+a5);
  a5=casadi_sq(a22);
  a33=casadi_sq(a48);
  a5=(a5+a33);
  a5=(a34*a5);
  a66=(a66+a5);
  a66=(a66-a2);
  a5=1.2748573000000001e+00;
  a33=5.3537699999999999e-03;
  a28=(a28+a3);
  a28=(a33+a28);
  a10=casadi_sq(a10);
  a47=casadi_sq(a47);
  a10=(a10+a47);
  a7=(a7*a10);
  a28=(a28+a7);
  a5=(a5+a28);
  a7=casadi_sq(a29);
  a48=casadi_sq(a48);
  a7=(a7+a48);
  a7=(a34*a7);
  a5=(a5+a7);
  a5=(a5-a2);
  a7=(a66+a5);
  a66=(a54*a66);
  a48=-1.2210000000000000e-05;
  a10=(a52*a44);
  a47=(a31*a68);
  a10=(a10+a47);
  a48=(a48+a10);
  a34=(a34*a29);
  a34=(a34*a22);
  a48=(a48-a34);
  a34=(a55*a48);
  a66=(a66+a34);
  a34=(a66*a54);
  a48=(a54*a48);
  a5=(a55*a5);
  a48=(a48+a5);
  a5=(a48*a55);
  a34=(a34+a5);
  a7=(a7-a34);
  a7=(a7+a2);
  a51=(a51+a7);
  a7=casadi_sq(a59);
  a5=casadi_sq(a12);
  a7=(a7+a5);
  a7=(a40*a7);
  a51=(a51+a7);
  a51=(a51-a1);
  a51=(a6*a51);
  a15=(a15-a51);
  a15=(a15*a6);
  a1=(a1-a15);
  a0=(a0+a1);
  a1=6.4187584841784808e+00;
  a15=1.1700000000000000e-05;
  a51=-2.6455439079680571e-07;
  a7=9.5991600139442335e-01;
  a24=(a7*a24);
  a51=(a51+a24);
  a24=(a62*a51);
  a5=9.0969031475411914e-04;
  a57=(a7*a57);
  a5=(a5+a57);
  a57=(a6*a5);
  a24=(a24+a57);
  a15=(a15-a24);
  a15=casadi_sq(a15);
  a57=-3.7847999999999999e-04;
  a22=-1.0400000000000000e-01;
  a29=-3.3435329891267395e-03;
  a7=(a7*a61);
  a29=(a29+a7);
  a7=(a22+a29);
  a57=(a57-a7);
  a57=casadi_sq(a57);
  a15=(a15+a57);
  a1=(a1*a15);
  a0=(a0+a1);
  a1=3.5491929339999999e+01;
  a15=2.7733496447054521e-06;
  a57=7.6296156882859389e-01;
  a24=(a57*a24);
  a15=(a15+a24);
  a15=casadi_sq(a15);
  a24=-8.9714305429753797e-05;
  a57=(a57*a7);
  a24=(a24+a57);
  a24=casadi_sq(a24);
  a15=(a15+a24);
  a1=(a1*a15);
  a0=(a0+a1);
  a1=3.1744000000000003e+00;
  a0=(a0+a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=-1.1198000000000000e-04;
  a23=(a23*a54);
  a20=(a20*a55);
  a23=(a23+a20);
  a20=(a55*a67);
  a15=(a54*a63);
  a20=(a20+a15);
  a23=(a23-a20);
  a0=(a0+a23);
  a23=(a40*a59);
  a23=(a23*a12);
  a0=(a0-a23);
  a23=2.7078978090000000e+01;
  a20=(a23*a29);
  a20=(a20*a5);
  a0=(a0-a20);
  a0=(a62*a0);
  a66=(a66*a55);
  a48=(a48*a54);
  a66=(a66-a48);
  a48=(a40*a43);
  a48=(a48*a59);
  a66=(a66-a48);
  a48=(a23*a51);
  a48=(a48*a29);
  a66=(a66-a48);
  a66=(a6*a66);
  a0=(a0-a66);
  a66=(a23*a5);
  a66=(a62*a66);
  a48=-2.7078978090000000e+01;
  a48=(a48*a51);
  a48=(a6*a48);
  a66=(a66+a48);
  a66=(a22*a66);
  a0=(a0-a66);
  if (res[0]!=0) res[0][1]=a0;
  a66=2.5993544369999999e+01;
  a48=casadi_sq(a56);
  a29=casadi_sq(a58);
  a48=(a48+a29);
  a48=(a66*a48);
  a48=(a2+a48);
  a29=-2.5993544369999999e+01;
  a29=(a29*a58);
  a59=(a55*a29);
  a20=(a66*a56);
  a15=(a54*a20);
  a59=(a59-a15);
  a15=(a60*a59);
  a15=(a48-a15);
  a15=(a62*a15);
  a56=(a66*a56);
  a56=(a56*a42);
  a63=(a63-a56);
  a56=(a55*a63);
  a66=(a66*a58);
  a66=(a66*a42);
  a67=(a67-a66);
  a66=(a54*a67);
  a56=(a56-a66);
  a29=(a54*a29);
  a20=(a55*a20);
  a29=(a29+a20);
  a29=(a25*a29);
  a56=(a56-a29);
  a56=(a6*a56);
  a15=(a15-a56);
  a56=(a62*a59);
  a56=(a22*a56);
  a15=(a15-a56);
  if (res[0]!=0) res[0][2]=a15;
  a56=1.5542318549999999e+01;
  a29=(a56*a53);
  a29=(a29*a26);
  a68=(a68-a29);
  a29=(a44*a68);
  a20=(a56*a27);
  a20=(a20*a53);
  a52=(a52-a20);
  a20=(a31*a52);
  a29=(a29-a20);
  a20=(a56*a26);
  a53=(a44*a20);
  a66=-1.5542318549999999e+01;
  a66=(a66*a27);
  a42=(a31*a66);
  a53=(a53+a42);
  a42=(a35*a53);
  a29=(a29-a42);
  a42=(a55*a53);
  a58=(a60*a42);
  a58=(a29-a58);
  a58=(a62*a58);
  a52=(a44*a52);
  a68=(a31*a68);
  a52=(a52+a68);
  a66=(a44*a66);
  a20=(a31*a20);
  a66=(a66-a20);
  a20=(a35*a66);
  a52=(a52+a20);
  a20=(a55*a52);
  a27=casadi_sq(a27);
  a26=casadi_sq(a26);
  a27=(a27+a26);
  a56=(a56*a27);
  a28=(a28+a56);
  a56=(a64*a53);
  a56=(a28+a56);
  a27=(a54*a56);
  a20=(a20-a27);
  a27=(a60*a66);
  a53=(a54*a53);
  a53=(a25*a53);
  a27=(a27-a53);
  a20=(a20+a27);
  a20=(a6*a20);
  a58=(a58-a20);
  a20=(a62*a42);
  a66=(a6*a66);
  a20=(a20+a66);
  a20=(a22*a20);
  a58=(a58-a20);
  if (res[0]!=0) res[0][3]=a58;
  a20=1.4456884830000000e+01;
  a66=casadi_sq(a39);
  a27=casadi_sq(a41);
  a66=(a66+a27);
  a66=(a20*a66);
  a3=(a3+a66);
  a66=-1.4456884830000000e+01;
  a66=(a66*a41);
  a27=(a38*a66);
  a53=(a20*a39);
  a26=(a37*a53);
  a27=(a27-a26);
  a26=(a13*a27);
  a26=(a3-a26);
  a68=(a44*a26);
  a39=(a20*a39);
  a39=(a39*a17);
  a45=(a45-a39);
  a39=(a38*a45);
  a20=(a20*a41);
  a20=(a20*a17);
  a49=(a49-a20);
  a20=(a37*a49);
  a39=(a39-a20);
  a66=(a37*a66);
  a53=(a38*a53);
  a66=(a66+a53);
  a53=(a25*a66);
  a39=(a39-a53);
  a53=(a31*a39);
  a68=(a68-a53);
  a53=(a44*a27);
  a20=(a35*a53);
  a68=(a68-a20);
  a20=(a55*a53);
  a17=(a54*a66);
  a20=(a20-a17);
  a17=(a60*a20);
  a17=(a68-a17);
  a17=(a62*a17);
  a39=(a44*a39);
  a26=(a31*a26);
  a39=(a39+a26);
  a26=(a31*a27);
  a41=(a35*a26);
  a24=(a64*a66);
  a41=(a41+a24);
  a39=(a39-a41);
  a41=(a55*a39);
  a45=(a37*a45);
  a49=(a38*a49);
  a45=(a45+a49);
  a27=(a25*a27);
  a45=(a45+a27);
  a27=(a64*a53);
  a27=(a45+a27);
  a49=(a54*a27);
  a41=(a41-a49);
  a49=(a60*a26);
  a53=(a54*a53);
  a66=(a55*a66);
  a53=(a53+a66);
  a53=(a25*a53);
  a49=(a49+a53);
  a41=(a41-a49);
  a41=(a6*a41);
  a17=(a17-a41);
  a41=(a62*a20);
  a26=(a6*a26);
  a41=(a41-a26);
  a41=(a22*a41);
  a17=(a17-a41);
  if (res[0]!=0) res[0][4]=a17;
  a41=5.9470830999999995e+00;
  a26=(a41*a36);
  a32=(a32*a26);
  a50=(a50-a32);
  a32=(a14*a50);
  a26=(a41*a30);
  a26=(a26*a36);
  a19=(a19-a26);
  a26=(a11*a19);
  a32=(a32-a26);
  a26=1.7133850235342660e-01;
  a36=(a26*a14);
  a49=-5.9470830999999995e+00;
  a49=(a49*a30);
  a53=(a11*a49);
  a36=(a36+a53);
  a53=(a35*a36);
  a32=(a32-a53);
  a53=(a38*a36);
  a66=(a13*a53);
  a66=(a32-a66);
  a24=(a44*a66);
  a19=(a14*a19);
  a50=(a11*a50);
  a19=(a19+a50);
  a49=(a14*a49);
  a26=(a26*a11);
  a49=(a49-a26);
  a26=(a35*a49);
  a19=(a19+a26);
  a26=(a38*a19);
  a30=casadi_sq(a30);
  a50=8.3004553713377687e-04;
  a30=(a30+a50);
  a41=(a41*a30);
  a4=(a4+a41);
  a41=(a46*a36);
  a41=(a4+a41);
  a30=(a37*a41);
  a26=(a26-a30);
  a30=(a13*a49);
  a36=(a37*a36);
  a50=(a25*a36);
  a30=(a30-a50);
  a26=(a26+a30);
  a30=(a31*a26);
  a24=(a24-a30);
  a30=(a44*a53);
  a50=(a31*a49);
  a30=(a30+a50);
  a50=(a35*a30);
  a24=(a24-a50);
  a50=(a55*a30);
  a57=(a54*a36);
  a50=(a50-a57);
  a57=(a60*a50);
  a57=(a24-a57);
  a57=(a62*a57);
  a26=(a44*a26);
  a66=(a31*a66);
  a26=(a26+a66);
  a49=(a44*a49);
  a66=(a31*a53);
  a49=(a49-a66);
  a66=(a35*a49);
  a7=(a64*a36);
  a66=(a66-a7);
  a26=(a26+a66);
  a66=(a55*a26);
  a19=(a37*a19);
  a41=(a38*a41);
  a19=(a19+a41);
  a53=(a25*a53);
  a19=(a19+a53);
  a53=(a64*a30);
  a53=(a19+a53);
  a41=(a54*a53);
  a66=(a66-a41);
  a41=(a60*a49);
  a30=(a54*a30);
  a36=(a55*a36);
  a30=(a30+a36);
  a30=(a25*a30);
  a41=(a41-a30);
  a66=(a66+a41);
  a66=(a6*a66);
  a57=(a57-a66);
  a66=(a62*a50);
  a49=(a6*a49);
  a66=(a66+a49);
  a66=(a22*a66);
  a57=(a57-a66);
  if (res[0]!=0) res[0][5]=a57;
  a66=-4.9235335953450907e-07;
  a49=(a66*a9);
  a41=1.2100000000000000e-01;
  a30=-5.6049154584000006e-06;
  a9=(a30*a9);
  a36=(a41*a9);
  a49=(a49+a36);
  a36=(a11*a49);
  a7=1.4176400671940515e-03;
  a30=(a30*a8);
  a61=(a13*a30);
  a7=(a7-a61);
  a61=(a14*a7);
  a36=(a36+a61);
  a61=(a14*a30);
  a10=(a35*a61);
  a36=(a36-a10);
  a10=(a38*a61);
  a47=(a37*a9);
  a10=(a10-a47);
  a47=(a13*a10);
  a47=(a36-a47);
  a21=(a44*a47);
  a7=(a11*a7);
  a14=(a14*a49);
  a7=(a7-a14);
  a11=(a11*a30);
  a14=(a35*a11);
  a49=(a46*a9);
  a14=(a14+a49);
  a7=(a7-a14);
  a14=(a38*a7);
  a66=(a66*a8);
  a41=(a41*a30);
  a66=(a66+a41);
  a46=(a46*a61);
  a46=(a66+a46);
  a41=(a37*a46);
  a14=(a14-a41);
  a13=(a13*a11);
  a61=(a37*a61);
  a9=(a38*a9);
  a61=(a61+a9);
  a9=(a25*a61);
  a13=(a13+a9);
  a14=(a14-a13);
  a13=(a31*a14);
  a21=(a21-a13);
  a13=(a44*a10);
  a9=(a31*a11);
  a13=(a13-a9);
  a9=(a35*a13);
  a21=(a21-a9);
  a9=(a55*a13);
  a41=(a54*a61);
  a9=(a9-a41);
  a41=(a60*a9);
  a41=(a21-a41);
  a41=(a62*a41);
  a14=(a44*a14);
  a47=(a31*a47);
  a14=(a14+a47);
  a31=(a31*a10);
  a44=(a44*a11);
  a31=(a31+a44);
  a35=(a35*a31);
  a44=(a64*a61);
  a35=(a35+a44);
  a14=(a14-a35);
  a35=(a55*a14);
  a37=(a37*a7);
  a38=(a38*a46);
  a37=(a37+a38);
  a10=(a25*a10);
  a37=(a37+a10);
  a64=(a64*a13);
  a64=(a37+a64);
  a10=(a54*a64);
  a35=(a35-a10);
  a60=(a60*a31);
  a13=(a54*a13);
  a61=(a55*a61);
  a13=(a13+a61);
  a13=(a25*a13);
  a60=(a60+a13);
  a35=(a35-a60);
  a35=(a6*a35);
  a41=(a41-a35);
  a62=(a62*a9);
  a6=(a6*a31);
  a62=(a62-a6);
  a22=(a22*a62);
  a41=(a41-a22);
  if (res[0]!=0) res[0][6]=a41;
  if (res[0]!=0) res[0][7]=a0;
  a34=(a34+a2);
  a33=(a33+a34);
  a43=casadi_sq(a43);
  a12=casadi_sq(a12);
  a43=(a43+a12);
  a40=(a40*a43);
  a33=(a33+a40);
  a51=casadi_sq(a51);
  a5=casadi_sq(a5);
  a51=(a51+a5);
  a23=(a23*a51);
  a33=(a33+a23);
  a33=(a33+a1);
  if (res[0]!=0) res[0][8]=a33;
  a63=(a54*a63);
  a67=(a55*a67);
  a63=(a63+a67);
  a59=(a25*a59);
  a63=(a63+a59);
  if (res[0]!=0) res[0][9]=a63;
  a52=(a54*a52);
  a56=(a55*a56);
  a52=(a52+a56);
  a42=(a25*a42);
  a52=(a52+a42);
  if (res[0]!=0) res[0][10]=a52;
  a39=(a54*a39);
  a27=(a55*a27);
  a39=(a39+a27);
  a20=(a25*a20);
  a39=(a39+a20);
  if (res[0]!=0) res[0][11]=a39;
  a26=(a54*a26);
  a53=(a55*a53);
  a26=(a26+a53);
  a50=(a25*a50);
  a26=(a26+a50);
  if (res[0]!=0) res[0][12]=a26;
  a54=(a54*a14);
  a55=(a55*a64);
  a54=(a54+a55);
  a25=(a25*a9);
  a54=(a54+a25);
  if (res[0]!=0) res[0][13]=a54;
  if (res[0]!=0) res[0][14]=a15;
  if (res[0]!=0) res[0][15]=a63;
  a48=(a48+a1);
  if (res[0]!=0) res[0][16]=a48;
  if (res[0]!=0) res[0][17]=a29;
  if (res[0]!=0) res[0][18]=a68;
  if (res[0]!=0) res[0][19]=a24;
  if (res[0]!=0) res[0][20]=a21;
  if (res[0]!=0) res[0][21]=a58;
  if (res[0]!=0) res[0][22]=a52;
  if (res[0]!=0) res[0][23]=a29;
  a28=(a28+a1);
  if (res[0]!=0) res[0][24]=a28;
  if (res[0]!=0) res[0][25]=a45;
  if (res[0]!=0) res[0][26]=a19;
  if (res[0]!=0) res[0][27]=a37;
  if (res[0]!=0) res[0][28]=a17;
  if (res[0]!=0) res[0][29]=a39;
  if (res[0]!=0) res[0][30]=a68;
  if (res[0]!=0) res[0][31]=a45;
  a3=(a3+a1);
  if (res[0]!=0) res[0][32]=a3;
  if (res[0]!=0) res[0][33]=a32;
  if (res[0]!=0) res[0][34]=a36;
  if (res[0]!=0) res[0][35]=a57;
  if (res[0]!=0) res[0][36]=a26;
  if (res[0]!=0) res[0][37]=a24;
  if (res[0]!=0) res[0][38]=a19;
  if (res[0]!=0) res[0][39]=a32;
  a4=(a4+a1);
  if (res[0]!=0) res[0][40]=a4;
  if (res[0]!=0) res[0][41]=a66;
  if (res[0]!=0) res[0][42]=a41;
  if (res[0]!=0) res[0][43]=a54;
  if (res[0]!=0) res[0][44]=a21;
  if (res[0]!=0) res[0][45]=a37;
  if (res[0]!=0) res[0][46]=a36;
  if (res[0]!=0) res[0][47]=a66;
  a66=3.1758176400671942e+00;
  if (res[0]!=0) res[0][48]=a66;
  return 0;
}

CASADI_SYMBOL_EXPORT int M(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int M_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int M_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void M_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int M_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void M_release(int mem) {
}

CASADI_SYMBOL_EXPORT void M_incref(void) {
}

CASADI_SYMBOL_EXPORT void M_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int M_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int M_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real M_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* M_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* M_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* M_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* M_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int M_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int M_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
