/* This file was automatically generated by CasADi 3.6.3+.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) KARM_EM_id_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};

/* rnea:(q[7],dq[7],ddq[7])->(tau[7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a100, a101, a102, a103, a104, a105, a106, a107, a108, a109, a11, a110, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
  a0=1.1149444000000000e-01;
  a1=arg[2]? arg[2][0] : 0;
  a0=(a0*a1);
  a2=1.1700000000000000e-05;
  a3=8.4129512500000008e+00;
  a4=(a2*a1);
  a4=(a3*a4);
  a2=(a2*a4);
  a4=-3.7847999999999999e-04;
  a5=(a4*a1);
  a3=(a3*a5);
  a4=(a4*a3);
  a2=(a2+a4);
  a0=(a0+a2);
  a2=arg[0]? arg[0][1] : 0;
  a4=cos(a2);
  a3=-9.3969999999999996e-05;
  a5=arg[1]? arg[1][2] : 0;
  a6=arg[0]? arg[0][2] : 0;
  a7=sin(a6);
  a2=sin(a2);
  a8=arg[1]? arg[1][0] : 0;
  a9=(a2*a8);
  a10=(a7*a9);
  a6=cos(a6);
  a11=arg[1]? arg[1][1] : 0;
  a12=(a6*a11);
  a10=(a10+a12);
  a12=(a5*a10);
  a13=arg[2]? arg[2][1] : 0;
  a14=(a7*a13);
  a15=(a4*a8);
  a16=(a11*a15);
  a17=(a2*a1);
  a16=(a16+a17);
  a17=(a6*a16);
  a14=(a14-a17);
  a12=(a12+a14);
  a14=(a3*a12);
  a17=1.1346658000000000e-01;
  a18=(a7*a16);
  a19=(a6*a13);
  a18=(a18+a19);
  a19=(a7*a11);
  a20=(a6*a9);
  a19=(a19-a20);
  a20=(a5*a19);
  a18=(a18-a20);
  a20=(a17*a18);
  a14=(a14+a20);
  a20=4.7084630000000002e-02;
  a21=arg[2]? arg[2][2] : 0;
  a22=(a4*a1);
  a23=(a11*a9);
  a22=(a22-a23);
  a21=(a21+a22);
  a23=(a20*a21);
  a14=(a14+a23);
  a23=4.6100000000000002e-05;
  a24=1.0451225819999999e+01;
  a25=1.2900000000000000e-01;
  a26=(a25*a16);
  a27=(a6*a26);
  a28=-1.0400000000000000e-01;
  a8=(a28*a8);
  a29=(a2*a8);
  a30=(a11*a29);
  a1=(a28*a1);
  a31=(a4*a1);
  a32=9.8100000000000005e+00;
  a33=(a32*a2);
  a31=(a31+a33);
  a30=(a30-a31);
  a31=-8.7999999999999995e-02;
  a22=(a31*a22);
  a13=(a25*a13);
  a22=(a22-a13);
  a30=(a30-a22);
  a22=(a7*a30);
  a27=(a27-a22);
  a22=(a25*a9);
  a13=(a7*a22);
  a8=(a4*a8);
  a33=(a31*a15);
  a34=(a25*a11);
  a33=(a33-a34);
  a33=(a8+a33);
  a34=(a6*a33);
  a13=(a13-a34);
  a34=(a5*a13);
  a27=(a27-a34);
  a34=4.0811987999999999e-01;
  a35=(a34*a12);
  a36=(a23*a21);
  a35=(a35-a36);
  a35=(a27-a35);
  a35=(a24*a35);
  a36=(a23*a35);
  a37=2.8216930000000001e-02;
  a33=(a7*a33);
  a22=(a6*a22);
  a33=(a33+a22);
  a22=(a5*a33);
  a30=(a6*a30);
  a26=(a7*a26);
  a30=(a30+a26);
  a22=(a22+a30);
  a30=(a37*a21);
  a26=(a34*a18);
  a30=(a30-a26);
  a30=(a22-a30);
  a30=(a24*a30);
  a26=(a37*a30);
  a36=(a36-a26);
  a14=(a14+a36);
  a36=-1.2210000000000000e-05;
  a26=(a36*a19);
  a38=1.2748573000000001e+00;
  a39=(a38*a10);
  a26=(a26+a39);
  a5=(a5+a15);
  a15=(a17*a5);
  a26=(a26+a15);
  a15=(a37*a5);
  a39=(a34*a10);
  a15=(a15-a39);
  a15=(a13-a15);
  a15=(a24*a15);
  a39=(a34*a15);
  a9=(a31*a9);
  a29=(a29+a9);
  a9=(a23*a10);
  a40=(a37*a19);
  a9=(a9-a40);
  a9=(a29+a9);
  a9=(a24*a9);
  a40=(a23*a9);
  a39=(a39+a40);
  a26=(a26+a39);
  a39=(a19*a26);
  a40=1.2966242299999997e+00;
  a41=(a40*a19);
  a42=(a36*a10);
  a41=(a41+a42);
  a42=(a3*a5);
  a41=(a41+a42);
  a42=(a37*a9);
  a43=(a34*a19);
  a44=(a23*a5);
  a43=(a43-a44);
  a43=(a33-a43);
  a43=(a24*a43);
  a44=(a34*a43);
  a42=(a42+a44);
  a41=(a41-a42);
  a42=(a10*a41);
  a39=(a39-a42);
  a42=(a13*a43);
  a44=(a33*a15);
  a42=(a42-a44);
  a39=(a39+a42);
  a14=(a14+a39);
  a39=arg[0]? arg[0][3] : 0;
  a42=cos(a39);
  a44=1.1198000000000000e-04;
  a45=arg[2]? arg[2][3] : 0;
  a45=(a45+a18);
  a46=(a44*a45);
  a47=5.0910599999999997e-03;
  a48=arg[1]? arg[1][3] : 0;
  a49=(a42*a19);
  a39=sin(a39);
  a50=(a39*a5);
  a49=(a49-a50);
  a50=(a48*a49);
  a51=(a39*a12);
  a52=(a42*a21);
  a51=(a51+a52);
  a50=(a50+a51);
  a51=(a47*a50);
  a46=(a46+a51);
  a51=8.3413160000000000e-02;
  a52=1.0854337199999999e+00;
  a53=1.0400000000000000e-01;
  a54=(a53*a21);
  a55=7.9800000000000004e-01;
  a56=(a55*a18);
  a54=(a54-a56);
  a22=(a22-a54);
  a54=(a42*a22);
  a32=(a32*a4);
  a1=(a2*a1);
  a32=(a32-a1);
  a11=(a11*a8);
  a32=(a32-a11);
  a16=(a31*a16);
  a32=(a32-a16);
  a16=(a53*a12);
  a16=(a32+a16);
  a11=(a39*a16);
  a54=(a54-a11);
  a11=(a53*a5);
  a8=(a55*a10);
  a11=(a11-a8);
  a11=(a13-a11);
  a8=(a39*a11);
  a1=(a53*a19);
  a1=(a1-a29);
  a56=(a42*a1);
  a8=(a8+a56);
  a56=(a48*a8);
  a54=(a54-a56);
  a56=(a51*a50);
  a57=2.2694599999999999e-02;
  a58=(a57*a45);
  a56=(a56-a58);
  a56=(a54-a56);
  a56=(a52*a56);
  a58=(a51*a56);
  a46=(a46-a58);
  a58=5.3537699999999999e-03;
  a59=(a48+a10);
  a60=(a58*a59);
  a61=(a39*a19);
  a62=(a42*a5);
  a61=(a61+a62);
  a62=(a44*a61);
  a60=(a60+a62);
  a11=(a42*a11);
  a1=(a39*a1);
  a11=(a11-a1);
  a1=(a51*a61);
  a62=(a57*a59);
  a1=(a1-a62);
  a1=(a11-a1);
  a1=(a52*a1);
  a62=(a57*a1);
  a60=(a60+a62);
  a62=(a49*a60);
  a63=6.3946799999999998e-03;
  a64=(a63*a49);
  a65=(a51*a49);
  a65=(a8+a65);
  a65=(a52*a65);
  a66=(a51*a65);
  a67=(a55*a19);
  a67=(a33-a67);
  a68=(a57*a49);
  a68=(a67-a68);
  a68=(a52*a68);
  a69=(a57*a68);
  a66=(a66-a69);
  a64=(a64+a66);
  a66=(a59*a64);
  a62=(a62-a66);
  a66=(a11*a68);
  a69=(a67*a1);
  a66=(a66-a69);
  a62=(a62+a66);
  a46=(a46+a62);
  a62=arg[0]? arg[0][5] : 0;
  a66=cos(a62);
  a69=1.6300000000000000e-05;
  a70=arg[1]? arg[1][4] : 0;
  a71=arg[0]? arg[0][4] : 0;
  a72=cos(a71);
  a73=(a72*a59);
  a71=sin(a71);
  a74=(a71*a49);
  a73=(a73-a74);
  a74=(a70*a73);
  a75=(a42*a12);
  a76=(a39*a21);
  a75=(a75-a76);
  a76=(a48*a61);
  a75=(a75-a76);
  a76=(a72*a75);
  a77=(a71*a45);
  a76=(a76+a77);
  a74=(a74+a76);
  a76=(a66*a74);
  a62=sin(a62);
  a77=arg[2]? arg[2][4] : 0;
  a77=(a77+a50);
  a78=(a62*a77);
  a76=(a76-a78);
  a78=arg[1]? arg[1][5] : 0;
  a79=(a72*a49);
  a80=(a71*a59);
  a79=(a79+a80);
  a80=(a62*a79);
  a81=(a70+a61);
  a82=(a66*a81);
  a80=(a80+a82);
  a82=(a78*a80);
  a76=(a76-a82);
  a82=(a69*a76);
  a83=-7.6964000000000004e-04;
  a84=arg[2]? arg[2][5] : 0;
  a85=(a72*a45);
  a86=(a71*a75);
  a85=(a85-a86);
  a86=(a70*a79);
  a85=(a85-a86);
  a84=(a84+a85);
  a86=(a83*a84);
  a82=(a82+a86);
  a86=1.5774830000000000e-02;
  a87=(a66*a79);
  a88=(a62*a81);
  a87=(a87-a88);
  a88=(a78*a87);
  a89=(a62*a74);
  a90=(a66*a77);
  a89=(a89+a90);
  a88=(a88+a89);
  a89=(a86*a88);
  a82=(a82+a89);
  a89=3.6990000000000003e-05;
  a90=5.4724924599999998e+00;
  a91=(a55*a12);
  a27=(a27-a91);
  a91=(a25*a75);
  a91=(a27-a91);
  a92=(a72*a91);
  a93=8.7999999999999995e-02;
  a94=(a93*a50);
  a95=(a25*a45);
  a94=(a94-a95);
  a54=(a54-a94);
  a94=(a71*a54);
  a92=(a92-a94);
  a94=(a93*a61);
  a95=(a25*a59);
  a94=(a94-a95);
  a94=(a11-a94);
  a95=(a72*a94);
  a96=(a25*a49);
  a96=(a67-a96);
  a97=(a71*a96);
  a95=(a95+a97);
  a97=(a70*a95);
  a92=(a92-a97);
  a97=4.0600000000000003e-01;
  a98=(a97*a74);
  a92=(a92-a98);
  a98=1.6910990000000001e-02;
  a99=(a98*a76);
  a100=(a89*a88);
  a99=(a99-a100);
  a92=(a92-a99);
  a92=(a90*a92);
  a99=(a89*a92);
  a100=9.0373780000000001e-02;
  a96=(a72*a96);
  a94=(a71*a94);
  a96=(a96-a94);
  a70=(a70*a96);
  a54=(a72*a54);
  a91=(a71*a91);
  a54=(a54+a91);
  a70=(a70+a54);
  a77=(a53*a77);
  a85=(a97*a85);
  a77=(a77-a85);
  a70=(a70-a77);
  a77=(a66*a70);
  a48=(a48*a11);
  a22=(a39*a22);
  a16=(a42*a16);
  a22=(a22+a16);
  a48=(a48+a22);
  a22=(a93*a75);
  a22=(a48+a22);
  a74=(a53*a74);
  a22=(a22+a74);
  a74=(a62*a22);
  a77=(a77-a74);
  a81=(a53*a81);
  a74=(a97*a73);
  a81=(a81-a74);
  a95=(a95-a81);
  a81=(a62*a95);
  a74=(a93*a49);
  a74=(a8+a74);
  a16=(a53*a79);
  a74=(a74+a16);
  a16=(a66*a74);
  a81=(a81+a16);
  a16=(a78*a81);
  a77=(a77-a16);
  a16=(a100*a88);
  a85=(a98*a84);
  a16=(a16-a85);
  a77=(a77-a16);
  a77=(a90*a77);
  a16=(a100*a77);
  a99=(a99-a16);
  a82=(a82+a99);
  a99=8.4159999999999994e-05;
  a16=(a99*a87);
  a85=1.0731441999999999e-01;
  a73=(a78+a73);
  a54=(a85*a73);
  a16=(a16+a54);
  a54=(a83*a80);
  a16=(a16+a54);
  a95=(a66*a95);
  a74=(a62*a74);
  a95=(a95-a74);
  a74=(a100*a80);
  a54=(a98*a73);
  a74=(a74-a54);
  a74=(a95-a74);
  a74=(a90*a74);
  a54=(a98*a74);
  a91=(a89*a73);
  a94=(a100*a87);
  a91=(a91-a94);
  a91=(a81-a91);
  a91=(a90*a91);
  a94=(a89*a91);
  a54=(a54-a94);
  a16=(a16+a54);
  a54=(a87*a16);
  a94=1.0881374999999999e-01;
  a101=(a94*a87);
  a102=(a99*a73);
  a101=(a101+a102);
  a102=(a69*a80);
  a101=(a101+a102);
  a102=(a100*a91);
  a79=(a97*a79);
  a96=(a96-a79);
  a79=(a98*a87);
  a103=(a89*a80);
  a79=(a79-a103);
  a79=(a96-a79);
  a79=(a90*a79);
  a103=(a98*a79);
  a102=(a102-a103);
  a101=(a101+a102);
  a102=(a73*a101);
  a54=(a54-a102);
  a102=(a95*a79);
  a103=(a96*a74);
  a102=(a102-a103);
  a54=(a54+a102);
  a82=(a82+a54);
  a54=9.9999999999999998e-13;
  a102=arg[2]? arg[2][6] : 0;
  a102=(a102+a88);
  a102=(a54*a102);
  a103=arg[0]? arg[0][6] : 0;
  a104=cos(a103);
  a105=(a104*a87);
  a103=sin(a103);
  a106=(a103*a73);
  a105=(a105+a106);
  a106=(a104*a73);
  a107=(a103*a87);
  a106=(a106-a107);
  a107=(a54*a106);
  a108=(a105*a107);
  a109=(a54*a105);
  a110=(a106*a109);
  a108=(a108-a110);
  a102=(a102+a108);
  a82=(a82+a102);
  a108=(a66*a82);
  a94=(a94*a76);
  a110=(a99*a84);
  a94=(a94+a110);
  a110=(a69*a88);
  a94=(a94+a110);
  a78=(a78*a95);
  a70=(a62*a70);
  a22=(a66*a22);
  a70=(a70+a22);
  a78=(a78+a70);
  a70=(a89*a84);
  a22=(a100*a76);
  a70=(a70-a22);
  a78=(a78-a70);
  a90=(a90*a78);
  a78=(a100*a90);
  a70=(a98*a92);
  a78=(a78-a70);
  a94=(a94+a78);
  a69=(a69*a87);
  a78=(a83*a73);
  a69=(a69+a78);
  a86=(a86*a80);
  a69=(a69+a86);
  a86=(a89*a79);
  a100=(a100*a74);
  a86=(a86-a100);
  a69=(a69+a86);
  a86=(a73*a69);
  a16=(a80*a16);
  a86=(a86-a16);
  a96=(a96*a91);
  a16=(a81*a79);
  a96=(a96-a16);
  a86=(a86+a96);
  a94=(a94+a86);
  a86=arg[1]? arg[1][6] : 0;
  a96=(a86*a106);
  a16=(a104*a76);
  a100=(a103*a84);
  a16=(a16+a100);
  a96=(a96+a16);
  a96=(a54*a96);
  a16=(a86+a80);
  a100=(a54*a16);
  a106=(a106*a100);
  a107=(a16*a107);
  a106=(a106-a107);
  a96=(a96+a106);
  a106=(a104*a96);
  a107=(a104*a84);
  a78=(a103*a76);
  a107=(a107-a78);
  a86=(a86*a105);
  a107=(a107-a86);
  a54=(a54*a107);
  a16=(a16*a109);
  a105=(a105*a100);
  a16=(a16-a105);
  a54=(a54+a16);
  a16=(a103*a54);
  a106=(a106-a16);
  a94=(a94+a106);
  a106=(a62*a94);
  a108=(a108-a106);
  a106=(a73*a91);
  a16=(a80*a79);
  a106=(a106-a16);
  a106=(a77+a106);
  a16=(a66*a106);
  a79=(a87*a79);
  a73=(a73*a74);
  a79=(a79-a73);
  a79=(a90+a79);
  a73=(a62*a79);
  a16=(a16+a73);
  a73=(a53*a16);
  a108=(a108-a73);
  a73=(a72*a16);
  a105=(a80*a74);
  a100=(a87*a91);
  a105=(a105-a100);
  a92=(a92+a105);
  a105=(a71*a92);
  a73=(a73-a105);
  a105=(a93*a73);
  a105=(a108-a105);
  a46=(a46+a105);
  a105=(a42*a46);
  a63=(a63*a75);
  a100=(a51*a75);
  a48=(a48+a100);
  a48=(a52*a48);
  a100=(a51*a48);
  a75=(a57*a75);
  a27=(a27-a75);
  a52=(a52*a27);
  a27=(a57*a52);
  a100=(a100-a27);
  a63=(a63+a100);
  a100=(a44*a59);
  a47=(a47*a61);
  a100=(a100+a47);
  a51=(a51*a1);
  a100=(a100-a51);
  a51=(a59*a100);
  a60=(a61*a60);
  a51=(a51-a60);
  a67=(a67*a65);
  a60=(a8*a68);
  a67=(a67-a60);
  a51=(a51+a67);
  a63=(a63+a51);
  a94=(a66*a94);
  a82=(a62*a82);
  a94=(a94+a82);
  a66=(a66*a79);
  a62=(a62*a106);
  a66=(a66-a62);
  a62=(a53*a66);
  a106=(a97*a92);
  a62=(a62-a106);
  a94=(a94+a62);
  a62=(a72*a94);
  a99=(a99*a76);
  a85=(a85*a84);
  a99=(a99+a85);
  a83=(a83*a88);
  a99=(a99+a83);
  a98=(a98*a77);
  a89=(a89*a90);
  a98=(a98-a89);
  a99=(a99+a98);
  a80=(a80*a101);
  a87=(a87*a69);
  a80=(a80-a87);
  a81=(a81*a74);
  a95=(a95*a91);
  a81=(a81-a95);
  a80=(a80+a81);
  a99=(a99+a80);
  a103=(a103*a96);
  a104=(a104*a54);
  a103=(a103+a104);
  a99=(a99+a103);
  a97=(a97*a16);
  a97=(a99+a97);
  a103=(a71*a97);
  a62=(a62-a103);
  a93=(a93*a66);
  a16=(a71*a16);
  a92=(a72*a92);
  a16=(a16+a92);
  a92=(a25*a16);
  a93=(a93-a92);
  a62=(a62+a93);
  a63=(a63+a62);
  a62=(a39*a63);
  a105=(a105-a62);
  a62=(a59*a65);
  a93=(a61*a68);
  a62=(a62-a93);
  a62=(a56+a62);
  a62=(a62+a73);
  a93=(a42*a62);
  a68=(a49*a68);
  a59=(a59*a1);
  a68=(a68-a59);
  a48=(a48+a68);
  a48=(a48+a66);
  a66=(a39*a48);
  a93=(a93+a66);
  a66=(a53*a93);
  a105=(a105-a66);
  a14=(a14+a105);
  a105=(a10*a9);
  a66=(a5*a43);
  a105=(a105+a66);
  a105=(a30-a105);
  a105=(a105+a93);
  a66=(a6*a105);
  a68=(a5*a15);
  a59=(a19*a9);
  a68=(a68+a59);
  a68=(a35+a68);
  a59=(a61*a1);
  a92=(a49*a65);
  a59=(a59-a92);
  a52=(a52+a59);
  a52=(a52+a16);
  a68=(a68+a52);
  a16=(a7*a68);
  a66=(a66-a16);
  a16=(a31*a66);
  a16=(a14-a16);
  a16=(a4*a16);
  a40=(a40*a12);
  a59=(a36*a18);
  a40=(a40+a59);
  a59=(a3*a21);
  a40=(a40+a59);
  a59=(a23*a18);
  a92=(a37*a12);
  a59=(a59-a92);
  a32=(a32-a59);
  a24=(a24*a32);
  a32=(a37*a24);
  a35=(a34*a35);
  a32=(a32-a35);
  a40=(a40+a32);
  a3=(a3*a19);
  a32=(a17*a10);
  a3=(a3+a32);
  a20=(a20*a5);
  a3=(a3+a20);
  a20=(a23*a43);
  a37=(a37*a15);
  a20=(a20-a37);
  a3=(a3+a20);
  a20=(a10*a3);
  a26=(a5*a26);
  a20=(a20-a26);
  a26=(a29*a43);
  a33=(a33*a9);
  a26=(a26-a33);
  a20=(a20+a26);
  a40=(a40+a20);
  a63=(a42*a63);
  a46=(a39*a46);
  a63=(a63+a46);
  a42=(a42*a48);
  a39=(a39*a62);
  a42=(a42-a39);
  a53=(a53*a42);
  a52=(a55*a52);
  a53=(a53-a52);
  a63=(a63+a53);
  a40=(a40+a63);
  a63=(a6*a40);
  a36=(a36*a12);
  a38=(a38*a18);
  a36=(a36+a38);
  a17=(a17*a21);
  a36=(a36+a17);
  a34=(a34*a30);
  a23=(a23*a24);
  a34=(a34-a23);
  a36=(a36+a34);
  a5=(a5*a41);
  a3=(a19*a3);
  a5=(a5-a3);
  a13=(a13*a9);
  a29=(a29*a15);
  a13=(a13-a29);
  a5=(a5+a13);
  a36=(a36+a5);
  a58=(a58*a45);
  a44=(a44*a50);
  a58=(a58+a44);
  a57=(a57*a56);
  a58=(a58+a57);
  a61=(a61*a64);
  a49=(a49*a100);
  a61=(a61-a49);
  a8=(a8*a1);
  a11=(a11*a65);
  a8=(a8-a11);
  a61=(a61+a8);
  a58=(a58+a61);
  a71=(a71*a94);
  a72=(a72*a97);
  a71=(a71+a72);
  a73=(a25*a73);
  a71=(a71+a73);
  a58=(a58+a71);
  a55=(a55*a93);
  a55=(a58+a55);
  a36=(a36+a55);
  a55=(a7*a36);
  a63=(a63-a55);
  a19=(a19*a43);
  a10=(a10*a15);
  a19=(a19-a10);
  a24=(a24+a19);
  a24=(a24+a42);
  a31=(a31*a24);
  a105=(a7*a105);
  a68=(a6*a68);
  a105=(a105+a68);
  a105=(a25*a105);
  a31=(a31-a105);
  a63=(a63+a31);
  a63=(a2*a63);
  a16=(a16-a63);
  a4=(a4*a66);
  a2=(a2*a24);
  a4=(a4+a2);
  a28=(a28*a4);
  a16=(a16-a28);
  a0=(a0+a16);
  if (res[0]!=0) res[0][0]=a0;
  a7=(a7*a40);
  a6=(a6*a36);
  a7=(a7+a6);
  a25=(a25*a66);
  a7=(a7+a25);
  if (res[0]!=0) res[0][1]=a7;
  if (res[0]!=0) res[0][2]=a14;
  if (res[0]!=0) res[0][3]=a58;
  if (res[0]!=0) res[0][4]=a108;
  if (res[0]!=0) res[0][5]=a99;
  if (res[0]!=0) res[0][6]=a102;
  return 0;
}

CASADI_SYMBOL_EXPORT int rnea(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rnea_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rnea_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rnea_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rnea_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rnea_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rnea_incref(void) {
}

CASADI_SYMBOL_EXPORT void rnea_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rnea_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int rnea_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real rnea_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rnea_name_in(casadi_int i) {
  switch (i) {
    case 0: return "q";
    case 1: return "dq";
    case 2: return "ddq";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rnea_name_out(casadi_int i) {
  switch (i) {
    case 0: return "tau";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rnea_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rnea_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rnea_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
