/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) g1_29dof_fk_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[33] = {29, 1, 0, 29, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};

/* fk_T:(q[29])->(T_pelvis_contour_joint[4x4],T_left_hand_palm_joint[4x4],T_right_hand_palm_joint[4x4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a8, a9;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a1;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a1;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a1;
  if (res[0]!=0) res[0][9]=a1;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a1;
  if (res[0]!=0) res[0][12]=a1;
  if (res[0]!=0) res[0][13]=a1;
  if (res[0]!=0) res[0][14]=a1;
  if (res[0]!=0) res[0][15]=a0;
  a2=arg[0]? arg[0][12] : 0;
  a3=cos(a2);
  a4=arg[0]? arg[0][14] : 0;
  a5=cos(a4);
  a6=(a3*a5);
  a2=sin(a2);
  a7=arg[0]? arg[0][13] : 0;
  a8=sin(a7);
  a9=(a2*a8);
  a4=sin(a4);
  a10=(a9*a4);
  a6=(a6-a10);
  a10=9.9999998013693969e-01;
  a11=arg[0]? arg[0][15] : 0;
  a12=cos(a11);
  a13=(a10*a12);
  a14=-4.1736579859221520e-10;
  a11=sin(a11);
  a15=(a14*a11);
  a13=(a13-a15);
  a15=(a6*a13);
  a16=(a3*a4);
  a17=(a9*a5);
  a16=(a16+a17);
  a17=-5.4948999972347917e-05;
  a18=(a17*a12);
  a19=9.6124589346272193e-01;
  a20=(a19*a11);
  a18=(a18-a20);
  a20=(a16*a18);
  a7=cos(a7);
  a21=(a2*a7);
  a22=-1.9158999853865032e-04;
  a23=(a22*a12);
  a24=-2.7569245963764316e-01;
  a25=(a24*a11);
  a23=(a23-a25);
  a25=(a21*a23);
  a20=(a20-a25);
  a15=(a15+a20);
  a20=arg[0]? arg[0][17] : 0;
  a25=cos(a20);
  a26=(a15*a25);
  a27=1.9931412428081187e-04;
  a28=(a27*a6);
  a29=2.7569245416162719e-01;
  a30=(a29*a16);
  a31=9.6124587436941389e-01;
  a32=(a31*a21);
  a30=(a30-a32);
  a28=(a28+a30);
  a30=9.6126243473093342e-01;
  a32=arg[0]? arg[0][16] : 0;
  a33=cos(a32);
  a34=(a30*a33);
  a35=2.7563477932793234e-01;
  a32=sin(a32);
  a36=(a35*a32);
  a34=(a34+a36);
  a36=(a28*a34);
  a37=(a10*a11);
  a38=(a14*a12);
  a37=(a37+a38);
  a38=(a6*a37);
  a39=(a17*a11);
  a40=(a19*a12);
  a39=(a39+a40);
  a40=(a16*a39);
  a22=(a22*a11);
  a24=(a24*a12);
  a22=(a22+a24);
  a24=(a21*a22);
  a40=(a40-a24);
  a38=(a38+a40);
  a40=-2.7563477932793234e-01;
  a24=(a40*a33);
  a12=(a30*a32);
  a24=(a24+a12);
  a12=(a38*a24);
  a36=(a36+a12);
  a20=sin(a20);
  a12=(a36*a20);
  a26=(a26+a12);
  a12=arg[0]? arg[0][18] : 0;
  a11=cos(a12);
  a41=(a26*a11);
  a42=(a35*a33);
  a43=(a30*a32);
  a42=(a42-a43);
  a43=(a28*a42);
  a33=(a30*a33);
  a32=(a40*a32);
  a33=(a33-a32);
  a32=(a38*a33);
  a43=(a43+a32);
  a12=sin(a12);
  a32=(a43*a12);
  a41=(a41-a32);
  a32=arg[0]? arg[0][20] : 0;
  a44=cos(a32);
  a45=(a41*a44);
  a46=(a26*a12);
  a47=(a43*a11);
  a46=(a46+a47);
  a47=arg[0]? arg[0][19] : 0;
  a48=cos(a47);
  a49=(a46*a48);
  a50=(a36*a25);
  a15=(a15*a20);
  a50=(a50-a15);
  a47=sin(a47);
  a15=(a50*a47);
  a49=(a49-a15);
  a32=sin(a32);
  a15=(a49*a32);
  a45=(a45-a15);
  a15=arg[0]? arg[0][21] : 0;
  a51=cos(a15);
  a52=(a45*a51);
  a53=(a50*a48);
  a54=(a46*a47);
  a53=(a53+a54);
  a15=sin(a15);
  a54=(a53*a15);
  a52=(a52+a54);
  if (res[1]!=0) res[1][0]=a52;
  a54=(a2*a5);
  a55=(a3*a8);
  a56=(a55*a4);
  a54=(a54+a56);
  a56=(a54*a13);
  a57=(a3*a7);
  a58=(a57*a23);
  a59=(a2*a4);
  a60=(a55*a5);
  a59=(a59-a60);
  a60=(a59*a18);
  a58=(a58+a60);
  a56=(a56+a58);
  a58=(a56*a25);
  a60=(a27*a54);
  a61=(a31*a57);
  a62=(a29*a59);
  a61=(a61+a62);
  a60=(a60+a61);
  a61=(a60*a34);
  a62=(a54*a37);
  a63=(a57*a22);
  a64=(a59*a39);
  a63=(a63+a64);
  a62=(a62+a63);
  a63=(a62*a24);
  a61=(a61+a63);
  a63=(a61*a20);
  a58=(a58+a63);
  a63=(a58*a11);
  a64=(a60*a42);
  a65=(a62*a33);
  a64=(a64+a65);
  a65=(a64*a12);
  a63=(a63-a65);
  a65=(a63*a44);
  a66=(a58*a12);
  a67=(a64*a11);
  a66=(a66+a67);
  a67=(a66*a48);
  a68=(a61*a25);
  a56=(a56*a20);
  a68=(a68-a56);
  a56=(a68*a47);
  a67=(a67-a56);
  a56=(a67*a32);
  a65=(a65-a56);
  a56=(a65*a51);
  a69=(a68*a48);
  a70=(a66*a47);
  a69=(a69+a70);
  a70=(a69*a15);
  a56=(a56+a70);
  if (res[1]!=0) res[1][1]=a56;
  a23=(a8*a23);
  a5=(a7*a5);
  a18=(a5*a18);
  a23=(a23+a18);
  a4=(a7*a4);
  a13=(a4*a13);
  a23=(a23-a13);
  a13=(a23*a25);
  a18=(a31*a8);
  a29=(a29*a5);
  a18=(a18+a29);
  a27=(a27*a4);
  a18=(a18-a27);
  a34=(a18*a34);
  a22=(a8*a22);
  a39=(a5*a39);
  a22=(a22+a39);
  a37=(a4*a37);
  a22=(a22-a37);
  a24=(a22*a24);
  a34=(a34+a24);
  a24=(a34*a20);
  a13=(a13+a24);
  a24=(a13*a11);
  a42=(a18*a42);
  a33=(a22*a33);
  a42=(a42+a33);
  a33=(a42*a12);
  a24=(a24-a33);
  a33=(a24*a44);
  a12=(a13*a12);
  a11=(a42*a11);
  a12=(a12+a11);
  a11=(a12*a48);
  a25=(a34*a25);
  a23=(a23*a20);
  a25=(a25-a23);
  a23=(a25*a47);
  a11=(a11-a23);
  a23=(a11*a32);
  a33=(a33-a23);
  a23=(a33*a51);
  a48=(a25*a48);
  a47=(a12*a47);
  a48=(a48+a47);
  a47=(a48*a15);
  a23=(a23+a47);
  if (res[1]!=0) res[1][2]=a23;
  if (res[1]!=0) res[1][3]=a1;
  a53=(a53*a51);
  a47=(a45*a15);
  a53=(a53-a47);
  if (res[1]!=0) res[1][4]=a53;
  a69=(a69*a51);
  a47=(a65*a15);
  a69=(a69-a47);
  if (res[1]!=0) res[1][5]=a69;
  a48=(a48*a51);
  a15=(a33*a15);
  a48=(a48-a15);
  if (res[1]!=0) res[1][6]=a48;
  if (res[1]!=0) res[1][7]=a1;
  a15=(a41*a32);
  a49=(a49*a44);
  a15=(a15+a49);
  if (res[1]!=0) res[1][8]=a15;
  a15=(a63*a32);
  a67=(a67*a44);
  a15=(a15+a67);
  if (res[1]!=0) res[1][9]=a15;
  a32=(a24*a32);
  a11=(a11*a44);
  a32=(a32+a11);
  if (res[1]!=0) res[1][10]=a32;
  if (res[1]!=0) res[1][11]=a1;
  a32=-3.9635000000000000e-03;
  a3=(a32*a3);
  a11=1.9000000000000000e-02;
  a9=(a11*a9);
  a3=(a3+a9);
  a9=3.9563000000000003e-03;
  a44=(a9*a6);
  a15=2.3777999999999999e-01;
  a67=(a15*a16);
  a49=1.0022000000000000e-01;
  a51=(a49*a21);
  a67=(a67-a51);
  a44=(a44+a67);
  a44=(a3+a44);
  a67=3.7999999999999999e-02;
  a28=(a67*a28);
  a51=-1.3831000000000000e-02;
  a38=(a51*a38);
  a28=(a28+a38);
  a44=(a44+a28);
  a28=6.2399999999999999e-03;
  a36=(a28*a36);
  a38=-1.0320000000000000e-01;
  a47=(a38*a43);
  a36=(a36+a47);
  a44=(a44+a36);
  a36=1.5782999999999998e-02;
  a26=(a36*a26);
  a47=-8.0518000000000006e-02;
  a43=(a47*a43);
  a26=(a26+a43);
  a44=(a44+a26);
  a26=1.0000000000000001e-01;
  a43=(a26*a41);
  a20=1.8879100000000000e-03;
  a50=(a20*a50);
  a37=-1.0000000000000000e-02;
  a46=(a37*a46);
  a50=(a50+a46);
  a43=(a43+a50);
  a44=(a44+a43);
  a41=(a67*a41);
  a44=(a44+a41);
  a41=4.5999999999999999e-02;
  a45=(a41*a45);
  a44=(a44+a45);
  a45=4.1500000000000002e-02;
  a52=(a45*a52);
  a43=3.0000000000000001e-03;
  a53=(a43*a53);
  a52=(a52+a53);
  a44=(a44+a52);
  if (res[1]!=0) res[1][12]=a44;
  a32=(a32*a2);
  a55=(a11*a55);
  a32=(a32-a55);
  a55=(a9*a54);
  a2=(a49*a57);
  a44=(a15*a59);
  a2=(a2+a44);
  a55=(a55+a2);
  a55=(a32+a55);
  a60=(a67*a60);
  a62=(a51*a62);
  a60=(a60+a62);
  a55=(a55+a60);
  a61=(a28*a61);
  a60=(a38*a64);
  a61=(a61+a60);
  a55=(a55+a61);
  a58=(a36*a58);
  a64=(a47*a64);
  a58=(a58+a64);
  a55=(a55+a58);
  a58=(a26*a63);
  a68=(a20*a68);
  a66=(a37*a66);
  a68=(a68+a66);
  a58=(a58+a68);
  a55=(a55+a58);
  a63=(a67*a63);
  a55=(a55+a63);
  a65=(a41*a65);
  a55=(a55+a65);
  a56=(a45*a56);
  a69=(a43*a69);
  a56=(a56+a69);
  a55=(a55+a56);
  if (res[1]!=0) res[1][13]=a55;
  a55=3.5000000000000003e-02;
  a11=(a11*a7);
  a55=(a55+a11);
  a49=(a49*a8);
  a11=(a15*a5);
  a49=(a49+a11);
  a11=(a9*a4);
  a49=(a49-a11);
  a49=(a55+a49);
  a18=(a67*a18);
  a22=(a51*a22);
  a18=(a18+a22);
  a49=(a49+a18);
  a28=(a28*a34);
  a34=(a38*a42);
  a28=(a28+a34);
  a49=(a49+a28);
  a13=(a36*a13);
  a42=(a47*a42);
  a13=(a13+a42);
  a49=(a49+a13);
  a13=(a26*a24);
  a20=(a20*a25);
  a12=(a37*a12);
  a20=(a20+a12);
  a13=(a13+a20);
  a49=(a49+a13);
  a24=(a67*a24);
  a49=(a49+a24);
  a33=(a41*a33);
  a49=(a49+a33);
  a23=(a45*a23);
  a43=(a43*a48);
  a23=(a23+a43);
  a49=(a49+a23);
  if (res[1]!=0) res[1][14]=a49;
  if (res[1]!=0) res[1][15]=a0;
  a49=arg[0]? arg[0][22] : 0;
  a23=cos(a49);
  a43=(a10*a23);
  a49=sin(a49);
  a48=(a14*a49);
  a43=(a43-a48);
  a48=(a6*a43);
  a33=(a17*a23);
  a24=(a19*a49);
  a33=(a33-a24);
  a24=(a16*a33);
  a13=1.9158999853865032e-04;
  a20=(a13*a23);
  a12=2.7569245963764316e-01;
  a25=(a12*a49);
  a20=(a20-a25);
  a25=(a21*a20);
  a24=(a24-a25);
  a48=(a48+a24);
  a24=arg[0]? arg[0][24] : 0;
  a25=cos(a24);
  a42=(a48*a25);
  a28=-1.9931412428081187e-04;
  a34=(a28*a6);
  a18=-2.7569245416162719e-01;
  a22=(a18*a16);
  a11=(a31*a21);
  a22=(a22-a11);
  a34=(a34+a22);
  a22=arg[0]? arg[0][23] : 0;
  a11=cos(a22);
  a7=(a30*a11);
  a22=sin(a22);
  a56=(a40*a22);
  a7=(a7+a56);
  a56=(a34*a7);
  a10=(a10*a49);
  a14=(a14*a23);
  a10=(a10+a14);
  a14=(a6*a10);
  a17=(a17*a49);
  a19=(a19*a23);
  a17=(a17+a19);
  a19=(a16*a17);
  a13=(a13*a49);
  a12=(a12*a23);
  a13=(a13+a12);
  a12=(a21*a13);
  a19=(a19-a12);
  a14=(a14+a19);
  a19=(a35*a11);
  a12=(a30*a22);
  a19=(a19+a12);
  a12=(a14*a19);
  a56=(a56+a12);
  a24=sin(a24);
  a12=(a56*a24);
  a42=(a42+a12);
  a12=arg[0]? arg[0][25] : 0;
  a23=cos(a12);
  a49=(a42*a23);
  a40=(a40*a11);
  a69=(a30*a22);
  a40=(a40-a69);
  a69=(a34*a40);
  a30=(a30*a11);
  a35=(a35*a22);
  a30=(a30-a35);
  a35=(a14*a30);
  a69=(a69+a35);
  a12=sin(a12);
  a35=(a69*a12);
  a49=(a49-a35);
  a35=arg[0]? arg[0][27] : 0;
  a22=cos(a35);
  a11=(a49*a22);
  a65=(a42*a12);
  a63=(a69*a23);
  a65=(a65+a63);
  a63=arg[0]? arg[0][26] : 0;
  a58=cos(a63);
  a68=(a65*a58);
  a66=(a56*a25);
  a48=(a48*a24);
  a66=(a66-a48);
  a63=sin(a63);
  a48=(a66*a63);
  a68=(a68-a48);
  a35=sin(a35);
  a48=(a68*a35);
  a11=(a11-a48);
  a48=arg[0]? arg[0][28] : 0;
  a64=cos(a48);
  a61=(a11*a64);
  a60=(a66*a58);
  a62=(a65*a63);
  a60=(a60+a62);
  a48=sin(a48);
  a62=(a60*a48);
  a61=(a61+a62);
  if (res[2]!=0) res[2][0]=a61;
  a62=(a54*a43);
  a2=(a57*a20);
  a44=(a59*a33);
  a2=(a2+a44);
  a62=(a62+a2);
  a2=(a62*a25);
  a44=(a28*a54);
  a52=(a31*a57);
  a53=(a18*a59);
  a52=(a52+a53);
  a44=(a44+a52);
  a52=(a44*a7);
  a53=(a54*a10);
  a50=(a57*a13);
  a46=(a59*a17);
  a50=(a50+a46);
  a53=(a53+a50);
  a50=(a53*a19);
  a52=(a52+a50);
  a50=(a52*a24);
  a2=(a2+a50);
  a50=(a2*a23);
  a46=(a44*a40);
  a39=(a53*a30);
  a46=(a46+a39);
  a39=(a46*a12);
  a50=(a50-a39);
  a39=(a50*a22);
  a27=(a2*a12);
  a29=(a46*a23);
  a27=(a27+a29);
  a29=(a27*a58);
  a70=(a52*a25);
  a62=(a62*a24);
  a70=(a70-a62);
  a62=(a70*a63);
  a29=(a29-a62);
  a62=(a29*a35);
  a39=(a39-a62);
  a62=(a39*a64);
  a71=(a70*a58);
  a72=(a27*a63);
  a71=(a71+a72);
  a72=(a71*a48);
  a62=(a62+a72);
  if (res[2]!=0) res[2][1]=a62;
  a20=(a8*a20);
  a33=(a5*a33);
  a20=(a20+a33);
  a43=(a4*a43);
  a20=(a20-a43);
  a43=(a20*a25);
  a31=(a31*a8);
  a18=(a18*a5);
  a31=(a31+a18);
  a28=(a28*a4);
  a31=(a31-a28);
  a7=(a31*a7);
  a13=(a8*a13);
  a17=(a5*a17);
  a13=(a13+a17);
  a10=(a4*a10);
  a13=(a13-a10);
  a19=(a13*a19);
  a7=(a7+a19);
  a19=(a7*a24);
  a43=(a43+a19);
  a19=(a43*a23);
  a40=(a31*a40);
  a30=(a13*a30);
  a40=(a40+a30);
  a30=(a40*a12);
  a19=(a19-a30);
  a30=(a19*a22);
  a12=(a43*a12);
  a23=(a40*a23);
  a12=(a12+a23);
  a23=(a12*a58);
  a25=(a7*a25);
  a20=(a20*a24);
  a25=(a25-a20);
  a20=(a25*a63);
  a23=(a23-a20);
  a20=(a23*a35);
  a30=(a30-a20);
  a20=(a30*a64);
  a58=(a25*a58);
  a63=(a12*a63);
  a58=(a58+a63);
  a63=(a58*a48);
  a20=(a20+a63);
  if (res[2]!=0) res[2][2]=a20;
  if (res[2]!=0) res[2][3]=a1;
  a60=(a60*a64);
  a63=(a11*a48);
  a60=(a60-a63);
  if (res[2]!=0) res[2][4]=a60;
  a71=(a71*a64);
  a63=(a39*a48);
  a71=(a71-a63);
  if (res[2]!=0) res[2][5]=a71;
  a58=(a58*a64);
  a48=(a30*a48);
  a58=(a58-a48);
  if (res[2]!=0) res[2][6]=a58;
  if (res[2]!=0) res[2][7]=a1;
  a48=(a49*a35);
  a68=(a68*a22);
  a48=(a48+a68);
  if (res[2]!=0) res[2][8]=a48;
  a48=(a50*a35);
  a29=(a29*a22);
  a48=(a48+a29);
  if (res[2]!=0) res[2][9]=a48;
  a35=(a19*a35);
  a23=(a23*a22);
  a35=(a35+a23);
  if (res[2]!=0) res[2][10]=a35;
  if (res[2]!=0) res[2][11]=a1;
  a6=(a9*a6);
  a16=(a15*a16);
  a1=-1.0020999999999999e-01;
  a21=(a1*a21);
  a16=(a16-a21);
  a6=(a6+a16);
  a3=(a3+a6);
  a6=-3.7999999999999999e-02;
  a34=(a6*a34);
  a14=(a51*a14);
  a34=(a34+a14);
  a3=(a3+a34);
  a34=-6.2399999999999999e-03;
  a56=(a34*a56);
  a14=(a38*a69);
  a56=(a56+a14);
  a3=(a3+a56);
  a42=(a36*a42);
  a69=(a47*a69);
  a42=(a42+a69);
  a3=(a3+a42);
  a42=(a26*a49);
  a69=-1.8879100000000000e-03;
  a66=(a69*a66);
  a65=(a37*a65);
  a66=(a66+a65);
  a42=(a42+a66);
  a3=(a3+a42);
  a49=(a67*a49);
  a3=(a3+a49);
  a11=(a41*a11);
  a3=(a3+a11);
  a61=(a45*a61);
  a11=-3.0000000000000001e-03;
  a60=(a11*a60);
  a61=(a61+a60);
  a3=(a3+a61);
  if (res[2]!=0) res[2][12]=a3;
  a54=(a9*a54);
  a57=(a1*a57);
  a59=(a15*a59);
  a57=(a57+a59);
  a54=(a54+a57);
  a32=(a32+a54);
  a44=(a6*a44);
  a53=(a51*a53);
  a44=(a44+a53);
  a32=(a32+a44);
  a52=(a34*a52);
  a44=(a38*a46);
  a52=(a52+a44);
  a32=(a32+a52);
  a2=(a36*a2);
  a46=(a47*a46);
  a2=(a2+a46);
  a32=(a32+a2);
  a2=(a26*a50);
  a70=(a69*a70);
  a27=(a37*a27);
  a70=(a70+a27);
  a2=(a2+a70);
  a32=(a32+a2);
  a50=(a67*a50);
  a32=(a32+a50);
  a39=(a41*a39);
  a32=(a32+a39);
  a62=(a45*a62);
  a71=(a11*a71);
  a62=(a62+a71);
  a32=(a32+a62);
  if (res[2]!=0) res[2][13]=a32;
  a1=(a1*a8);
  a15=(a15*a5);
  a1=(a1+a15);
  a9=(a9*a4);
  a1=(a1-a9);
  a55=(a55+a1);
  a6=(a6*a31);
  a51=(a51*a13);
  a6=(a6+a51);
  a55=(a55+a6);
  a34=(a34*a7);
  a38=(a38*a40);
  a34=(a34+a38);
  a55=(a55+a34);
  a36=(a36*a43);
  a47=(a47*a40);
  a36=(a36+a47);
  a55=(a55+a36);
  a26=(a26*a19);
  a69=(a69*a25);
  a37=(a37*a12);
  a69=(a69+a37);
  a26=(a26+a69);
  a55=(a55+a26);
  a67=(a67*a19);
  a55=(a55+a67);
  a41=(a41*a30);
  a55=(a55+a41);
  a45=(a45*a20);
  a11=(a11*a58);
  a45=(a45+a11);
  a55=(a55+a45);
  if (res[2]!=0) res[2][14]=a55;
  if (res[2]!=0) res[2][15]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int fk_T(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int fk_T_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int fk_T_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fk_T_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int fk_T_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fk_T_release(int mem) {
}

CASADI_SYMBOL_EXPORT void fk_T_incref(void) {
}

CASADI_SYMBOL_EXPORT void fk_T_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int fk_T_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int fk_T_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real fk_T_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fk_T_name_in(casadi_int i) {
  switch (i) {
    case 0: return "q";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fk_T_name_out(casadi_int i) {
  switch (i) {
    case 0: return "T_pelvis_contour_joint";
    case 1: return "T_left_hand_palm_joint";
    case 2: return "T_right_hand_palm_joint";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fk_T_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fk_T_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int fk_T_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int fk_T_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
