/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) g1_29dof_J_s_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[33] = {29, 1, 0, 29, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28};
static const casadi_int casadi_s1[206] = {6, 29, 0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96, 102, 108, 114, 120, 126, 132, 138, 144, 150, 156, 162, 168, 174, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};

/* J_s:(q[29])->(J_s[6x29]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a4, a5, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  if (res[0]!=0) res[0][9]=a0;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a0;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a0;
  if (res[0]!=0) res[0][15]=a0;
  if (res[0]!=0) res[0][16]=a0;
  if (res[0]!=0) res[0][17]=a0;
  if (res[0]!=0) res[0][18]=a0;
  if (res[0]!=0) res[0][19]=a0;
  if (res[0]!=0) res[0][20]=a0;
  if (res[0]!=0) res[0][21]=a0;
  if (res[0]!=0) res[0][22]=a0;
  if (res[0]!=0) res[0][23]=a0;
  if (res[0]!=0) res[0][24]=a0;
  if (res[0]!=0) res[0][25]=a0;
  if (res[0]!=0) res[0][26]=a0;
  if (res[0]!=0) res[0][27]=a0;
  if (res[0]!=0) res[0][28]=a0;
  if (res[0]!=0) res[0][29]=a0;
  if (res[0]!=0) res[0][30]=a0;
  if (res[0]!=0) res[0][31]=a0;
  if (res[0]!=0) res[0][32]=a0;
  if (res[0]!=0) res[0][33]=a0;
  if (res[0]!=0) res[0][34]=a0;
  if (res[0]!=0) res[0][35]=a0;
  if (res[0]!=0) res[0][36]=a0;
  if (res[0]!=0) res[0][37]=a0;
  if (res[0]!=0) res[0][38]=a0;
  if (res[0]!=0) res[0][39]=a0;
  if (res[0]!=0) res[0][40]=a0;
  if (res[0]!=0) res[0][41]=a0;
  if (res[0]!=0) res[0][42]=a0;
  if (res[0]!=0) res[0][43]=a0;
  if (res[0]!=0) res[0][44]=a0;
  if (res[0]!=0) res[0][45]=a0;
  if (res[0]!=0) res[0][46]=a0;
  if (res[0]!=0) res[0][47]=a0;
  if (res[0]!=0) res[0][48]=a0;
  if (res[0]!=0) res[0][49]=a0;
  if (res[0]!=0) res[0][50]=a0;
  if (res[0]!=0) res[0][51]=a0;
  if (res[0]!=0) res[0][52]=a0;
  if (res[0]!=0) res[0][53]=a0;
  if (res[0]!=0) res[0][54]=a0;
  if (res[0]!=0) res[0][55]=a0;
  if (res[0]!=0) res[0][56]=a0;
  if (res[0]!=0) res[0][57]=a0;
  if (res[0]!=0) res[0][58]=a0;
  if (res[0]!=0) res[0][59]=a0;
  if (res[0]!=0) res[0][60]=a0;
  if (res[0]!=0) res[0][61]=a0;
  if (res[0]!=0) res[0][62]=a0;
  if (res[0]!=0) res[0][63]=a0;
  if (res[0]!=0) res[0][64]=a0;
  if (res[0]!=0) res[0][65]=a0;
  if (res[0]!=0) res[0][66]=a0;
  if (res[0]!=0) res[0][67]=a0;
  if (res[0]!=0) res[0][68]=a0;
  if (res[0]!=0) res[0][69]=a0;
  if (res[0]!=0) res[0][70]=a0;
  if (res[0]!=0) res[0][71]=a0;
  if (res[0]!=0) res[0][72]=a0;
  if (res[0]!=0) res[0][73]=a0;
  if (res[0]!=0) res[0][74]=a0;
  if (res[0]!=0) res[0][75]=a0;
  if (res[0]!=0) res[0][76]=a0;
  a1=1.;
  if (res[0]!=0) res[0][77]=a1;
  a1=3.5000000000000003e-02;
  a2=arg[0]? arg[0][12] : 0;
  a3=sin(a2);
  a4=(a1*a3);
  a4=(-a4);
  if (res[0]!=0) res[0][78]=a4;
  a2=cos(a2);
  a4=(a1*a2);
  if (res[0]!=0) res[0][79]=a4;
  a4=-3.9635000000000000e-03;
  a5=(a4*a2);
  a6=(a5*a3);
  a4=(a4*a3);
  a7=(a4*a2);
  a6=(a6-a7);
  if (res[0]!=0) res[0][80]=a6;
  if (res[0]!=0) res[0][81]=a2;
  if (res[0]!=0) res[0][82]=a3;
  if (res[0]!=0) res[0][83]=a0;
  a6=1.9000000000000000e-02;
  a7=arg[0]? arg[0][13] : 0;
  a8=sin(a7);
  a9=(a2*a8);
  a10=(a6*a9);
  a4=(a4-a10);
  a10=(a4*a8);
  a7=cos(a7);
  a11=(a6*a7);
  a1=(a1+a11);
  a11=(a2*a7);
  a12=(a1*a11);
  a10=(a10-a12);
  if (res[0]!=0) res[0][84]=a10;
  a10=(a3*a7);
  a12=(a1*a10);
  a13=(a3*a8);
  a6=(a6*a13);
  a5=(a5+a6);
  a6=(a5*a8);
  a12=(a12+a6);
  a12=(-a12);
  if (res[0]!=0) res[0][85]=a12;
  a12=(a5*a11);
  a6=(a4*a10);
  a12=(a12+a6);
  if (res[0]!=0) res[0][86]=a12;
  a12=(-a10);
  if (res[0]!=0) res[0][87]=a12;
  if (res[0]!=0) res[0][88]=a11;
  if (res[0]!=0) res[0][89]=a8;
  a12=3.9563000000000003e-03;
  a6=arg[0]? arg[0][14] : 0;
  a14=cos(a6);
  a15=(a3*a14);
  a6=sin(a6);
  a16=(a9*a6);
  a15=(a15+a16);
  a16=(a12*a15);
  a17=1.0022000000000000e-01;
  a18=(a17*a11);
  a19=2.3777999999999999e-01;
  a3=(a3*a6);
  a9=(a9*a14);
  a3=(a3-a9);
  a9=(a19*a3);
  a18=(a18+a9);
  a16=(a16+a18);
  a4=(a4+a16);
  a16=9.6124587436941389e-01;
  a18=(a16*a8);
  a9=2.7569245416162719e-01;
  a20=(a7*a14);
  a21=(a9*a20);
  a18=(a18+a21);
  a21=1.9931412428081187e-04;
  a7=(a7*a6);
  a22=(a21*a7);
  a18=(a18-a22);
  a22=(a4*a18);
  a23=(a17*a8);
  a24=(a19*a20);
  a23=(a23+a24);
  a24=(a12*a7);
  a23=(a23-a24);
  a1=(a1+a23);
  a23=(a21*a15);
  a24=(a16*a11);
  a25=(a9*a3);
  a24=(a24+a25);
  a23=(a23+a24);
  a24=(a1*a23);
  a22=(a22-a24);
  if (res[0]!=0) res[0][90]=a22;
  a22=(a2*a14);
  a24=(a13*a6);
  a22=(a22-a24);
  a21=(a21*a22);
  a2=(a2*a6);
  a13=(a13*a14);
  a2=(a2+a13);
  a9=(a9*a2);
  a16=(a16*a10);
  a9=(a9-a16);
  a21=(a21+a9);
  a9=(a1*a21);
  a12=(a12*a22);
  a19=(a19*a2);
  a17=(a17*a10);
  a19=(a19-a17);
  a12=(a12+a19);
  a5=(a5+a12);
  a12=(a5*a18);
  a9=(a9-a12);
  if (res[0]!=0) res[0][91]=a9;
  a9=(a5*a23);
  a12=(a4*a21);
  a9=(a9-a12);
  if (res[0]!=0) res[0][92]=a9;
  if (res[0]!=0) res[0][93]=a21;
  if (res[0]!=0) res[0][94]=a23;
  if (res[0]!=0) res[0][95]=a18;
  a9=3.7999999999999999e-02;
  a12=(a9*a23);
  a19=-1.3831000000000000e-02;
  a17=9.9999998013693969e-01;
  a16=arg[0]? arg[0][15] : 0;
  a13=sin(a16);
  a14=(a17*a13);
  a6=-4.1736579859221520e-10;
  a16=cos(a16);
  a24=(a6*a16);
  a14=(a14+a24);
  a24=(a15*a14);
  a25=-1.9158999853865032e-04;
  a26=(a25*a13);
  a27=-2.7569245963764316e-01;
  a28=(a27*a16);
  a26=(a26+a28);
  a28=(a11*a26);
  a29=-5.4948999972347917e-05;
  a30=(a29*a13);
  a31=9.6124589346272193e-01;
  a32=(a31*a16);
  a30=(a30+a32);
  a32=(a3*a30);
  a28=(a28+a32);
  a24=(a24+a28);
  a28=(a19*a24);
  a12=(a12+a28);
  a4=(a4+a12);
  a25=(a25*a16);
  a27=(a27*a13);
  a25=(a25-a27);
  a27=(a8*a25);
  a29=(a29*a16);
  a31=(a31*a13);
  a29=(a29-a31);
  a31=(a20*a29);
  a27=(a27+a31);
  a17=(a17*a16);
  a6=(a6*a13);
  a17=(a17-a6);
  a6=(a7*a17);
  a27=(a27-a6);
  a6=(a4*a27);
  a13=(a9*a18);
  a8=(a8*a26);
  a20=(a20*a30);
  a8=(a8+a20);
  a7=(a7*a14);
  a8=(a8-a7);
  a7=(a19*a8);
  a13=(a13+a7);
  a1=(a1+a13);
  a15=(a15*a17);
  a11=(a11*a25);
  a3=(a3*a29);
  a11=(a11+a3);
  a15=(a15+a11);
  a11=(a1*a15);
  a6=(a6-a11);
  if (res[0]!=0) res[0][96]=a6;
  a17=(a22*a17);
  a29=(a2*a29);
  a25=(a10*a25);
  a29=(a29-a25);
  a17=(a17+a29);
  a29=(a1*a17);
  a25=(a9*a21);
  a22=(a22*a14);
  a2=(a2*a30);
  a10=(a10*a26);
  a2=(a2-a10);
  a22=(a22+a2);
  a19=(a19*a22);
  a25=(a25+a19);
  a5=(a5+a25);
  a25=(a5*a27);
  a29=(a29-a25);
  if (res[0]!=0) res[0][97]=a29;
  a29=(a5*a15);
  a25=(a4*a17);
  a29=(a29-a25);
  if (res[0]!=0) res[0][98]=a29;
  if (res[0]!=0) res[0][99]=a17;
  if (res[0]!=0) res[0][100]=a15;
  if (res[0]!=0) res[0][101]=a27;
  a29=6.2399999999999999e-03;
  a25=9.6126243473093342e-01;
  a19=arg[0]? arg[0][16] : 0;
  a2=cos(a19);
  a10=(a25*a2);
  a26=2.7563477932793234e-01;
  a19=sin(a19);
  a30=(a26*a19);
  a10=(a10+a30);
  a30=(a23*a10);
  a14=-2.7563477932793234e-01;
  a6=(a14*a2);
  a11=(a25*a19);
  a6=(a6+a11);
  a11=(a24*a6);
  a30=(a30+a11);
  a11=(a29*a30);
  a3=-1.0320000000000000e-01;
  a26=(a26*a2);
  a13=(a25*a19);
  a26=(a26-a13);
  a23=(a23*a26);
  a25=(a25*a2);
  a14=(a14*a19);
  a25=(a25-a14);
  a24=(a24*a25);
  a23=(a23+a24);
  a24=(a3*a23);
  a11=(a11+a24);
  a4=(a4+a11);
  a11=(a18*a26);
  a24=(a8*a25);
  a11=(a11+a24);
  a24=(a4*a11);
  a18=(a18*a10);
  a8=(a8*a6);
  a18=(a18+a8);
  a8=(a29*a18);
  a14=(a3*a11);
  a8=(a8+a14);
  a1=(a1+a8);
  a8=(a1*a23);
  a24=(a24-a8);
  if (res[0]!=0) res[0][102]=a24;
  a26=(a21*a26);
  a25=(a22*a25);
  a26=(a26+a25);
  a25=(a1*a26);
  a21=(a21*a10);
  a22=(a22*a6);
  a21=(a21+a22);
  a29=(a29*a21);
  a3=(a3*a26);
  a29=(a29+a3);
  a5=(a5+a29);
  a29=(a5*a11);
  a25=(a25-a29);
  if (res[0]!=0) res[0][103]=a25;
  a25=(a5*a23);
  a29=(a4*a26);
  a25=(a25-a29);
  if (res[0]!=0) res[0][104]=a25;
  if (res[0]!=0) res[0][105]=a26;
  if (res[0]!=0) res[0][106]=a23;
  if (res[0]!=0) res[0][107]=a11;
  a25=1.5782999999999998e-02;
  a29=arg[0]? arg[0][17] : 0;
  a3=cos(a29);
  a22=(a15*a3);
  a29=sin(a29);
  a6=(a30*a29);
  a22=(a22+a6);
  a6=(a25*a22);
  a10=-8.0518000000000006e-02;
  a24=(a10*a23);
  a6=(a6+a24);
  a4=(a4+a6);
  a6=(a18*a3);
  a24=(a27*a29);
  a6=(a6-a24);
  a24=(a4*a6);
  a27=(a27*a3);
  a18=(a18*a29);
  a27=(a27+a18);
  a18=(a25*a27);
  a8=(a10*a11);
  a18=(a18+a8);
  a1=(a1+a18);
  a30=(a30*a3);
  a15=(a15*a29);
  a30=(a30-a15);
  a15=(a1*a30);
  a24=(a24-a15);
  if (res[0]!=0) res[0][108]=a24;
  a24=(a21*a3);
  a15=(a17*a29);
  a24=(a24-a15);
  a15=(a1*a24);
  a17=(a17*a3);
  a21=(a21*a29);
  a17=(a17+a21);
  a25=(a25*a17);
  a10=(a10*a26);
  a25=(a25+a10);
  a5=(a5+a25);
  a25=(a5*a6);
  a15=(a15-a25);
  if (res[0]!=0) res[0][109]=a15;
  a15=(a5*a30);
  a25=(a4*a24);
  a15=(a15-a25);
  if (res[0]!=0) res[0][110]=a15;
  if (res[0]!=0) res[0][111]=a24;
  if (res[0]!=0) res[0][112]=a30;
  if (res[0]!=0) res[0][113]=a6;
  a15=1.0000000000000001e-01;
  a25=arg[0]? arg[0][18] : 0;
  a10=cos(a25);
  a21=(a22*a10);
  a25=sin(a25);
  a29=(a23*a25);
  a21=(a21-a29);
  a29=(a15*a21);
  a3=1.8879100000000000e-03;
  a18=(a3*a30);
  a8=-1.0000000000000000e-02;
  a22=(a22*a25);
  a23=(a23*a10);
  a22=(a22+a23);
  a23=(a8*a22);
  a18=(a18+a23);
  a29=(a29+a18);
  a4=(a4+a29);
  a29=(a27*a10);
  a18=(a11*a25);
  a29=(a29-a18);
  a18=(a4*a29);
  a23=(a15*a29);
  a14=(a3*a6);
  a27=(a27*a25);
  a11=(a11*a10);
  a27=(a27+a11);
  a11=(a8*a27);
  a14=(a14+a11);
  a23=(a23+a14);
  a1=(a1+a23);
  a23=(a1*a21);
  a18=(a18-a23);
  if (res[0]!=0) res[0][114]=a18;
  a18=(a17*a10);
  a23=(a26*a25);
  a18=(a18-a23);
  a23=(a1*a18);
  a15=(a15*a18);
  a3=(a3*a24);
  a17=(a17*a25);
  a26=(a26*a10);
  a17=(a17+a26);
  a8=(a8*a17);
  a3=(a3+a8);
  a15=(a15+a3);
  a5=(a5+a15);
  a15=(a5*a29);
  a23=(a23-a15);
  if (res[0]!=0) res[0][115]=a23;
  a23=(a5*a21);
  a15=(a4*a18);
  a23=(a23-a15);
  if (res[0]!=0) res[0][116]=a23;
  if (res[0]!=0) res[0][117]=a18;
  if (res[0]!=0) res[0][118]=a21;
  if (res[0]!=0) res[0][119]=a29;
  a23=(a9*a21);
  a4=(a4+a23);
  a23=arg[0]? arg[0][19] : 0;
  a15=cos(a23);
  a3=(a6*a15);
  a23=sin(a23);
  a8=(a27*a23);
  a3=(a3+a8);
  a8=(a4*a3);
  a26=(a9*a29);
  a1=(a1+a26);
  a26=(a30*a15);
  a10=(a22*a23);
  a26=(a26+a10);
  a10=(a1*a26);
  a8=(a8-a10);
  if (res[0]!=0) res[0][120]=a8;
  a8=(a24*a15);
  a10=(a17*a23);
  a8=(a8+a10);
  a10=(a1*a8);
  a9=(a9*a18);
  a5=(a5+a9);
  a9=(a5*a3);
  a10=(a10-a9);
  if (res[0]!=0) res[0][121]=a10;
  a10=(a5*a26);
  a9=(a4*a8);
  a10=(a10-a9);
  if (res[0]!=0) res[0][122]=a10;
  if (res[0]!=0) res[0][123]=a8;
  if (res[0]!=0) res[0][124]=a26;
  if (res[0]!=0) res[0][125]=a3;
  a3=4.5999999999999999e-02;
  a26=arg[0]? arg[0][20] : 0;
  a8=cos(a26);
  a10=(a21*a8);
  a22=(a22*a15);
  a30=(a30*a23);
  a22=(a22-a30);
  a26=sin(a26);
  a30=(a22*a26);
  a10=(a10-a30);
  a10=(a3*a10);
  a4=(a4+a10);
  a10=(a29*a26);
  a27=(a27*a15);
  a6=(a6*a23);
  a27=(a27-a6);
  a6=(a27*a8);
  a10=(a10+a6);
  a6=(a4*a10);
  a29=(a29*a8);
  a27=(a27*a26);
  a29=(a29-a27);
  a29=(a3*a29);
  a1=(a1+a29);
  a21=(a21*a26);
  a22=(a22*a8);
  a21=(a21+a22);
  a22=(a1*a21);
  a6=(a6-a22);
  if (res[0]!=0) res[0][126]=a6;
  a6=(a18*a26);
  a17=(a17*a15);
  a24=(a24*a23);
  a17=(a17-a24);
  a24=(a17*a8);
  a6=(a6+a24);
  a1=(a1*a6);
  a18=(a18*a8);
  a17=(a17*a26);
  a18=(a18-a17);
  a3=(a3*a18);
  a5=(a5+a3);
  a3=(a5*a10);
  a1=(a1-a3);
  if (res[0]!=0) res[0][127]=a1;
  a5=(a5*a21);
  a4=(a4*a6);
  a5=(a5-a4);
  if (res[0]!=0) res[0][128]=a5;
  if (res[0]!=0) res[0][129]=a6;
  if (res[0]!=0) res[0][130]=a21;
  if (res[0]!=0) res[0][131]=a10;
  if (res[0]!=0) res[0][132]=a0;
  if (res[0]!=0) res[0][133]=a0;
  if (res[0]!=0) res[0][134]=a0;
  if (res[0]!=0) res[0][135]=a0;
  if (res[0]!=0) res[0][136]=a0;
  if (res[0]!=0) res[0][137]=a0;
  if (res[0]!=0) res[0][138]=a0;
  if (res[0]!=0) res[0][139]=a0;
  if (res[0]!=0) res[0][140]=a0;
  if (res[0]!=0) res[0][141]=a0;
  if (res[0]!=0) res[0][142]=a0;
  if (res[0]!=0) res[0][143]=a0;
  if (res[0]!=0) res[0][144]=a0;
  if (res[0]!=0) res[0][145]=a0;
  if (res[0]!=0) res[0][146]=a0;
  if (res[0]!=0) res[0][147]=a0;
  if (res[0]!=0) res[0][148]=a0;
  if (res[0]!=0) res[0][149]=a0;
  if (res[0]!=0) res[0][150]=a0;
  if (res[0]!=0) res[0][151]=a0;
  if (res[0]!=0) res[0][152]=a0;
  if (res[0]!=0) res[0][153]=a0;
  if (res[0]!=0) res[0][154]=a0;
  if (res[0]!=0) res[0][155]=a0;
  if (res[0]!=0) res[0][156]=a0;
  if (res[0]!=0) res[0][157]=a0;
  if (res[0]!=0) res[0][158]=a0;
  if (res[0]!=0) res[0][159]=a0;
  if (res[0]!=0) res[0][160]=a0;
  if (res[0]!=0) res[0][161]=a0;
  if (res[0]!=0) res[0][162]=a0;
  if (res[0]!=0) res[0][163]=a0;
  if (res[0]!=0) res[0][164]=a0;
  if (res[0]!=0) res[0][165]=a0;
  if (res[0]!=0) res[0][166]=a0;
  if (res[0]!=0) res[0][167]=a0;
  if (res[0]!=0) res[0][168]=a0;
  if (res[0]!=0) res[0][169]=a0;
  if (res[0]!=0) res[0][170]=a0;
  if (res[0]!=0) res[0][171]=a0;
  if (res[0]!=0) res[0][172]=a0;
  if (res[0]!=0) res[0][173]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int J_s(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int J_s_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int J_s_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void J_s_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int J_s_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void J_s_release(int mem) {
}

CASADI_SYMBOL_EXPORT void J_s_incref(void) {
}

CASADI_SYMBOL_EXPORT void J_s_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int J_s_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int J_s_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real J_s_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* J_s_name_in(casadi_int i) {
  switch (i) {
    case 0: return "q";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* J_s_name_out(casadi_int i) {
  switch (i) {
    case 0: return "J_s";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* J_s_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* J_s_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int J_s_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int J_s_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
