/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) space_arm_J_s_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[94] = {6, 13, 0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};

/* J_s:(q[13])->(J_s[6x13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a3, a4, a5, a6, a7, a8, a9;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a1;
  if (res[0]!=0) res[0][5]=a1;
  if (res[0]!=0) res[0][6]=a1;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a1;
  if (res[0]!=0) res[0][9]=a1;
  if (res[0]!=0) res[0][10]=a1;
  if (res[0]!=0) res[0][11]=a1;
  if (res[0]!=0) res[0][12]=a1;
  if (res[0]!=0) res[0][13]=a1;
  if (res[0]!=0) res[0][14]=a0;
  if (res[0]!=0) res[0][15]=a1;
  if (res[0]!=0) res[0][16]=a1;
  if (res[0]!=0) res[0][17]=a1;
  if (res[0]!=0) res[0][18]=a1;
  a2=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][19]=a2;
  a3=arg[0]? arg[0][1] : 0;
  a4=(-a3);
  if (res[0]!=0) res[0][20]=a4;
  if (res[0]!=0) res[0][21]=a0;
  if (res[0]!=0) res[0][22]=a1;
  if (res[0]!=0) res[0][23]=a1;
  a0=arg[0]? arg[0][3] : 0;
  a4=sin(a0);
  a5=(a3*a4);
  a0=cos(a0);
  a6=(a2*a0);
  a5=(a5-a6);
  if (res[0]!=0) res[0][24]=a5;
  a5=arg[0]? arg[0][0] : 0;
  a6=(a5*a4);
  a6=(-a6);
  if (res[0]!=0) res[0][25]=a6;
  a6=(a5*a0);
  if (res[0]!=0) res[0][26]=a6;
  if (res[0]!=0) res[0][27]=a1;
  if (res[0]!=0) res[0][28]=a0;
  if (res[0]!=0) res[0][29]=a4;
  a1=arg[0]? arg[0][4] : 0;
  a6=cos(a1);
  a7=(a0*a6);
  a8=(a3*a7);
  a9=(a4*a6);
  a10=(a2*a9);
  a8=(a8+a10);
  if (res[0]!=0) res[0][30]=a8;
  a1=sin(a1);
  a8=(a2*a1);
  a10=(a5*a7);
  a8=(a8-a10);
  if (res[0]!=0) res[0][31]=a8;
  a8=(a5*a9);
  a10=(a3*a1);
  a8=(a8+a10);
  a8=(-a8);
  if (res[0]!=0) res[0][32]=a8;
  if (res[0]!=0) res[0][33]=a1;
  a8=(-a9);
  if (res[0]!=0) res[0][34]=a8;
  if (res[0]!=0) res[0][35]=a7;
  a10=-2.2869999999999999e-01;
  a11=(a10*a9);
  a3=(a3-a11);
  a11=(a3*a7);
  a12=(a10*a7);
  a2=(a2+a12);
  a12=(a2*a9);
  a11=(a11+a12);
  if (res[0]!=0) res[0][36]=a11;
  a11=(a2*a1);
  a10=(a10*a1);
  a5=(a5+a10);
  a10=(a5*a7);
  a11=(a11-a10);
  if (res[0]!=0) res[0][37]=a11;
  a11=(a5*a9);
  a10=(a3*a1);
  a11=(a11+a10);
  a11=(-a11);
  if (res[0]!=0) res[0][38]=a11;
  if (res[0]!=0) res[0][39]=a1;
  if (res[0]!=0) res[0][40]=a8;
  if (res[0]!=0) res[0][41]=a7;
  a8=-5.3999999999999999e-02;
  a11=(a8*a9);
  a3=(a3-a11);
  a11=arg[0]? arg[0][5] : 0;
  a10=sin(a11);
  a12=(a4*a10);
  a13=(a0*a1);
  a11=cos(a11);
  a14=(a13*a11);
  a12=(a12-a14);
  a14=arg[0]? arg[0][6] : 0;
  a15=cos(a14);
  a16=(a12*a15);
  a13=(a13*a10);
  a17=(a4*a11);
  a13=(a13+a17);
  a14=sin(a14);
  a17=(a13*a14);
  a16=(a16+a17);
  a17=(a3*a16);
  a18=(a8*a7);
  a2=(a2+a18);
  a4=(a4*a1);
  a18=(a4*a11);
  a19=(a0*a10);
  a18=(a18+a19);
  a19=(a18*a15);
  a0=(a0*a11);
  a4=(a4*a10);
  a0=(a0-a4);
  a4=(a0*a14);
  a19=(a19+a4);
  a4=(a2*a19);
  a17=(a17-a4);
  if (res[0]!=0) res[0][42]=a17;
  a11=(a6*a11);
  a17=(a11*a15);
  a6=(a6*a10);
  a10=(a6*a14);
  a17=(a17-a10);
  a10=(a2*a17);
  a4=(a8*a1);
  a5=(a5+a4);
  a4=(a5*a16);
  a10=(a10-a4);
  if (res[0]!=0) res[0][43]=a10;
  a10=(a5*a19);
  a4=(a3*a17);
  a10=(a10-a4);
  if (res[0]!=0) res[0][44]=a10;
  if (res[0]!=0) res[0][45]=a17;
  if (res[0]!=0) res[0][46]=a19;
  if (res[0]!=0) res[0][47]=a16;
  a10=-1.4580000000000001e-01;
  a0=(a0*a15);
  a18=(a18*a14);
  a0=(a0-a18);
  a18=arg[0]? arg[0][7] : 0;
  a4=sin(a18);
  a20=(a0*a4);
  a18=cos(a18);
  a21=(a9*a18);
  a20=(a20+a21);
  a21=(a10*a20);
  a3=(a3-a21);
  a21=(a7*a18);
  a13=(a13*a15);
  a12=(a12*a14);
  a13=(a13-a12);
  a12=(a13*a4);
  a21=(a21-a12);
  a12=(a3*a21);
  a22=(a10*a21);
  a2=(a2+a22);
  a22=(a2*a20);
  a12=(a12+a22);
  if (res[0]!=0) res[0][48]=a12;
  a11=(a11*a14);
  a6=(a6*a15);
  a11=(a11+a6);
  a6=(a11*a4);
  a15=(a1*a18);
  a6=(a6+a15);
  a15=(a2*a6);
  a14=(a10*a6);
  a5=(a5+a14);
  a14=(a5*a21);
  a15=(a15-a14);
  if (res[0]!=0) res[0][49]=a15;
  a15=(a5*a20);
  a14=(a3*a6);
  a15=(a15+a14);
  a15=(-a15);
  if (res[0]!=0) res[0][50]=a15;
  if (res[0]!=0) res[0][51]=a6;
  a15=(-a20);
  if (res[0]!=0) res[0][52]=a15;
  if (res[0]!=0) res[0][53]=a21;
  a15=-1.5420000000000000e-01;
  a14=(a15*a20);
  a3=(a3-a14);
  a14=arg[0]? arg[0][8] : 0;
  a12=cos(a14);
  a22=(a16*a12);
  a13=(a13*a18);
  a7=(a7*a4);
  a13=(a13+a7);
  a14=sin(a14);
  a7=(a13*a14);
  a22=(a22+a7);
  a7=(a3*a22);
  a23=(a15*a21);
  a2=(a2+a23);
  a23=(a19*a12);
  a0=(a0*a18);
  a9=(a9*a4);
  a0=(a0-a9);
  a9=(a0*a14);
  a23=(a23+a9);
  a9=(a2*a23);
  a7=(a7-a9);
  if (res[0]!=0) res[0][54]=a7;
  a7=(a17*a12);
  a1=(a1*a4);
  a11=(a11*a18);
  a1=(a1-a11);
  a11=(a1*a14);
  a7=(a7+a11);
  a11=(a2*a7);
  a18=(a15*a6);
  a5=(a5+a18);
  a18=(a5*a22);
  a11=(a11-a18);
  if (res[0]!=0) res[0][55]=a11;
  a11=(a5*a23);
  a18=(a3*a7);
  a11=(a11-a18);
  if (res[0]!=0) res[0][56]=a11;
  if (res[0]!=0) res[0][57]=a7;
  if (res[0]!=0) res[0][58]=a23;
  if (res[0]!=0) res[0][59]=a22;
  a0=(a0*a12);
  a19=(a19*a14);
  a0=(a0-a19);
  a19=arg[0]? arg[0][9] : 0;
  a11=sin(a19);
  a18=(a0*a11);
  a19=cos(a19);
  a4=(a20*a19);
  a18=(a18+a4);
  a4=(a10*a18);
  a3=(a3-a4);
  a4=(a21*a19);
  a13=(a13*a12);
  a16=(a16*a14);
  a13=(a13-a16);
  a16=(a13*a11);
  a4=(a4-a16);
  a16=(a3*a4);
  a9=(a10*a4);
  a2=(a2+a9);
  a9=(a2*a18);
  a16=(a16+a9);
  if (res[0]!=0) res[0][60]=a16;
  a16=(a6*a19);
  a1=(a1*a12);
  a17=(a17*a14);
  a1=(a1-a17);
  a17=(a1*a11);
  a16=(a16-a17);
  a17=(a2*a16);
  a10=(a10*a16);
  a5=(a5+a10);
  a10=(a5*a4);
  a17=(a17-a10);
  if (res[0]!=0) res[0][61]=a17;
  a17=(a5*a18);
  a10=(a3*a16);
  a17=(a17+a10);
  a17=(-a17);
  if (res[0]!=0) res[0][62]=a17;
  if (res[0]!=0) res[0][63]=a16;
  a17=(-a18);
  if (res[0]!=0) res[0][64]=a17;
  if (res[0]!=0) res[0][65]=a4;
  a17=(a15*a18);
  a3=(a3-a17);
  a17=arg[0]? arg[0][10] : 0;
  a10=cos(a17);
  a14=(a22*a10);
  a13=(a13*a19);
  a21=(a21*a11);
  a13=(a13+a21);
  a17=sin(a17);
  a21=(a13*a17);
  a14=(a14+a21);
  a21=(a3*a14);
  a12=(a15*a4);
  a2=(a2+a12);
  a12=(a23*a10);
  a0=(a0*a19);
  a20=(a20*a11);
  a0=(a0-a20);
  a20=(a0*a17);
  a12=(a12+a20);
  a20=(a2*a12);
  a21=(a21-a20);
  if (res[0]!=0) res[0][66]=a21;
  a21=(a7*a10);
  a1=(a1*a19);
  a6=(a6*a11);
  a1=(a1+a6);
  a6=(a1*a17);
  a21=(a21+a6);
  a6=(a2*a21);
  a15=(a15*a16);
  a5=(a5+a15);
  a15=(a5*a14);
  a6=(a6-a15);
  if (res[0]!=0) res[0][67]=a6;
  a6=(a5*a12);
  a15=(a3*a21);
  a6=(a6-a15);
  if (res[0]!=0) res[0][68]=a6;
  if (res[0]!=0) res[0][69]=a21;
  if (res[0]!=0) res[0][70]=a12;
  if (res[0]!=0) res[0][71]=a14;
  a0=(a0*a10);
  a23=(a23*a17);
  a0=(a0-a23);
  a23=arg[0]? arg[0][11] : 0;
  a14=sin(a23);
  a0=(a0*a14);
  a23=cos(a23);
  a18=(a18*a23);
  a0=(a0+a18);
  a18=(a8*a0);
  a3=(a3-a18);
  a4=(a4*a23);
  a13=(a13*a10);
  a22=(a22*a17);
  a13=(a13-a22);
  a13=(a13*a14);
  a4=(a4-a13);
  a13=(a3*a4);
  a22=(a8*a4);
  a2=(a2+a22);
  a22=(a2*a0);
  a13=(a13+a22);
  if (res[0]!=0) res[0][72]=a13;
  a16=(a16*a23);
  a1=(a1*a10);
  a7=(a7*a17);
  a1=(a1-a7);
  a1=(a1*a14);
  a16=(a16-a1);
  a2=(a2*a16);
  a8=(a8*a16);
  a5=(a5+a8);
  a8=(a5*a4);
  a2=(a2-a8);
  if (res[0]!=0) res[0][73]=a2;
  a5=(a5*a0);
  a3=(a3*a16);
  a5=(a5+a3);
  a5=(-a5);
  if (res[0]!=0) res[0][74]=a5;
  if (res[0]!=0) res[0][75]=a16;
  a0=(-a0);
  if (res[0]!=0) res[0][76]=a0;
  if (res[0]!=0) res[0][77]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int J_s(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int J_s_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int J_s_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void J_s_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int J_s_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void J_s_release(int mem) {
}

CASADI_SYMBOL_EXPORT void J_s_incref(void) {
}

CASADI_SYMBOL_EXPORT void J_s_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int J_s_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int J_s_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real J_s_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* J_s_name_in(casadi_int i) {
  switch (i) {
    case 0: return "q";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* J_s_name_out(casadi_int i) {
  switch (i) {
    case 0: return "J_s";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* J_s_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* J_s_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int J_s_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int J_s_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
